<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Components\Madlibs\**" />
    <Compile Remove="Functions\**" />
    <Compile Remove="IDXDBPartials\**" />
    <Content Remove="Components\Madlibs\**" />
    <Content Remove="Functions\**" />
    <Content Remove="IDXDBPartials\**" />
    <Content Remove="wwwroot\css\splide\**" />
    <EmbeddedResource Remove="Components\Madlibs\**" />
    <EmbeddedResource Remove="Functions\**" />
    <EmbeddedResource Remove="IDXDBPartials\**" />
    <EmbeddedResource Remove="wwwroot\css\splide\**" />
    <None Remove="Components\Madlibs\**" />
    <None Remove="Functions\**" />
    <None Remove="IDXDBPartials\**" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Remove="wwwroot\images\cloud-up-arrow.svg" />
  </ItemGroup>
  
  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\images\cloud-up-arrow.svg" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
    <PackageReference Include="Blazored.Video" Version="1.0.1" />
    <PackageReference Include="BlazorIndexedDB" Version="0.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.10" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  
  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>
  
  <!-- Update offline.html to ensure it's copied properly -->
  <ItemGroup>
    <Content Update="wwwroot\css\all.min.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\css\bootstrap-icons.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\css\layout.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\css\open-iconic-bootstrap.min.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\css\site.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\css\theme.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\fonts\bootstrap-icons.woff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\fonts\bootstrap-icons.woff2">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\offline.html" Condition="Exists('wwwroot\offline.html')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="wwwroot\images\cloud-up-arrow.svg" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ICS.DesignSystem\ICS.DesignSystem.csproj" />
    <ProjectReference Include="..\ICS.Portal.Auth.Models\ICS.Portal.Auth.Models.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="wwwroot\css\root.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\appsshot1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\appsshot2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\icon-150.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\icon-192.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\icon-300-trans.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\icon-512.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\images\SliderIcon.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\staticwebapp.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\updateManager.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <!-- Ensure all module JavaScript files are included in service worker assets -->
  <ItemGroup>
    <Content Update="wwwroot\modules\**\*.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	<ItemGroup>
		<Content Update="wwwroot\js\**\*.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>