// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AttributeList
//     Last Modified On: 8/23/2024 9:02:07 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the AttributeList service.
    /// </summary>
    public partial class AttributeListInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AttributeListInput.
        /// </summary>
        public AttributeListInput() { }

        /// <summary>
        /// Parameterized constructor for AttributeListInput.
        /// </summary>
        /// <param name="Context">Maps to parameter @Context.</param>
        /// <param name="DataTypeId">Maps to parameter @DataTypeId.</param>
        /// <param name="Active">Maps to parameter @Active.</param>
        /// <param name="Consumable">Maps to parameter @Consumable.</param>
        /// <param name="Item">Maps to parameter @Item.</param>
        /// <param name="Checklist">Maps to parameter @Checklist.</param>
        public AttributeListInput(int? Context, int? DataTypeId, bool? Active, bool? Consumable, bool? Item, bool? Checklist)
        {
            this.Context = Context;
            this.DataTypeId = DataTypeId;
            this.Active = Active;
            this.Consumable = Consumable;
            this.Item = Item;
            this.Checklist = Checklist;
        }

        #endregion Constructors

        #region Fields

        private int? _Context;
        /// <summary>
        /// Maps to parameter @Context.
        /// </summary>
        public int? Context
        {
            get => _Context;
            set => _Context = value;
        }

        private int? _DataTypeId;
        /// <summary>
        /// Maps to parameter @DataTypeId.
        /// </summary>
        public int? DataTypeId
        {
            get => _DataTypeId;
            set => _DataTypeId = value;
        }

        private bool? _Active;
        /// <summary>
        /// Maps to parameter @Active.
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        private bool? _Consumable;
        /// <summary>
        /// Maps to parameter @Consumable.
        /// </summary>
        public bool? Consumable
        {
            get => _Consumable;
            set => _Consumable = value;
        }

        private bool? _Item;
        /// <summary>
        /// Maps to parameter @Item.
        /// </summary>
        public bool? Item
        {
            get => _Item;
            set => _Item = value;
        }

        private bool? _Checklist;
        /// <summary>
        /// Maps to parameter @Checklist.
        /// </summary>
        public bool? Checklist
        {
            get => _Checklist;
            set => _Checklist = value;
        }

        #endregion

    }
}