// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AttributeContextList
//     Last Modified On: 7/11/2024 7:19:28 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for AttributeContextList service.
    /// </summary>
    public partial class AttributeContextListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of AttributeContextListResult.
        /// </summary>
        public List<AttributeContextListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for AttributeContextList service.
    /// </summary>


    public partial class AttributeContextListResult
	{
        /// <summary>
        /// Result set object for AttributeContextList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        public AttributeContextListResult(int Id, string Description)
        {
             this.Id = Id;
             this.Description = Description;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }
    }

    #endregion Result Set Objects

}
