// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: BinderListJobs
//     Last Modified On: 12/10/2025 4:09:40 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the BinderListJobs service.
    /// </summary>
    public partial class BinderListJobsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for BinderListJobsInput.
        /// </summary>
        public BinderListJobsInput() { }

        /// <summary>
        /// Parameterized constructor for BinderListJobsInput.
        /// </summary>
        /// <param name="StatusFilter">Maps to parameter @StatusFilter.</param>
        /// <param name="SetTypeFilter">Maps to parameter @SetTypeFilter.</param>
        /// <param name="StartDateFrom">Maps to parameter @StartDateFrom.</param>
        /// <param name="StartDateTo">Maps to parameter @StartDateTo.</param>
        public BinderListJobsInput(string? StatusFilter, string? SetTypeFilter, DateTime? StartDateFrom, DateTime? StartDateTo)
        {
            this.StatusFilter = StatusFilter;
            this.SetTypeFilter = SetTypeFilter;
            this.StartDateFrom = StartDateFrom;
            this.StartDateTo = StartDateTo;
        }

        #endregion Constructors

        #region Fields

        private string? _StatusFilter = null;
        /// <summary>
        /// Maps to parameter @StatusFilter.
        /// </summary>
        public string? StatusFilter
        {
            get => _StatusFilter;
            set => _StatusFilter = value;
        }

        private string? _SetTypeFilter = null;
        /// <summary>
        /// Maps to parameter @SetTypeFilter.
        /// </summary>
        public string? SetTypeFilter
        {
            get => _SetTypeFilter;
            set => _SetTypeFilter = value;
        }

        private DateTime? _StartDateFrom = null;
        /// <summary>
        /// Maps to parameter @StartDateFrom.
        /// </summary>
        public DateTime? StartDateFrom
        {
            get => _StartDateFrom;
            set => _StartDateFrom = value;
        }

        private DateTime? _StartDateTo = null;
        /// <summary>
        /// Maps to parameter @StartDateTo.
        /// </summary>
        public DateTime? StartDateTo
        {
            get => _StartDateTo;
            set => _StartDateTo = value;
        }

        #endregion

    }
}