// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: BluonCacheById
//     Last Modified On: 7/26/2025 1:06:43 AM
//     Written By: ICS
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for BluonCacheById service.
    /// </summary>
    public partial class BluonCacheByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of BluonCacheByIdResult.
        /// </summary>
        public BluonCacheByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for BluonCacheById service.
    /// </summary>


    public partial class BluonCacheByIdResult
	{
        /// <summary>
        /// Result set object for BluonCacheById.
        /// </summary>
        /// <param name="UrlHash">Maps to table value column UrlHash.</param>
        /// <param name="Url">Maps to table value column Url.</param>
        /// <param name="JsonData">Maps to table value column JsonData.</param>
        /// <param name="CreatedAt">Maps to table value column CreatedAt.</param>
        /// <param name="ExpiresAt">Maps to table value column ExpiresAt.</param>
        public BluonCacheByIdResult(int UrlHash, string? Url, string? JsonData, DateTime? CreatedAt, DateTime? ExpiresAt)
        {
             this.UrlHash = UrlHash;
             this.Url = Url;
             this.JsonData = JsonData;
             this.CreatedAt = CreatedAt;
             this.ExpiresAt = ExpiresAt;
        }


        /// <summary>
        /// Maps to table value column UrlHash.
        /// </summary>
        public int UrlHash { set; get; }

        /// <summary>
        /// Maps to table value column Url.
        /// </summary>
        public string? Url { set; get; }

        /// <summary>
        /// Maps to table value column JsonData.
        /// </summary>
        public string? JsonData { set; get; }

        /// <summary>
        /// Maps to table value column CreatedAt.
        /// </summary>
        public DateTime? CreatedAt { set; get; }

        /// <summary>
        /// Maps to table value column ExpiresAt.
        /// </summary>
        public DateTime? ExpiresAt { set; get; }
    }

    #endregion Result Set Objects

}
