// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CheckOffsetDispatch
//     Last Modified On: 2/5/2025 4:27:57 AM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable
    /// <summary>
    /// Output object for CheckOffsetDispatch service.
    /// </summary>
    public partial class CheckOffsetDispatchOutput
    {
        #region Output Parameters

        /// <summary>
        /// Maps to parameter @NumFound.
        /// </summary>
        public int? NumFound { set; get; }
        /// <summary>
        /// Maps to parameter @NumQualified.
        /// </summary>
        public int? NumQualified { set; get; }
        /// <summary>
        /// Maps to parameter @DispatchNumsFound.
        /// </summary>
        public string? DispatchNumsFound { set; get; }
        /// <summary>
        /// Maps to parameter @QualifiedZones.
        /// </summary>
        public string? QualifiedZones { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Actual return value for the routine.
        /// </summary>
        public int? ReturnValue { set; get; }

        #endregion Return Value

    }





}
