// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CheckOffsetDispatch
//     Last Modified On: 2/5/2025 4:27:57 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the CheckOffsetDispatch service.
    /// </summary>
    public partial class CheckOffsetDispatchInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CheckOffsetDispatchInput.
        /// </summary>
        public CheckOffsetDispatchInput() { }

        /// <summary>
        /// Parameterized constructor for CheckOffsetDispatchInput.
        /// </summary>
        /// <param name="OfType">OfType,1=L30 2=DTW 3=DTH 4=LUN</param>
        /// <param name="ForZones">ForZones,comma-delim list of zones names to override all and run these specifically</param>
        /// <param name="ForDate">ForDate,Optional datetime of when to make this template dispatch for</param>
        public CheckOffsetDispatchInput(int? OfType, string? ForZones, DateTime? ForDate)
        {
            this.OfType = OfType;
            this.ForZones = ForZones;
            this.ForDate = ForDate;
        }

        #endregion Constructors

        #region Fields

        private int? _OfType;
        /// <summary>
        /// OfType,1=L30 2=DTW 3=DTH 4=LUN
        /// </summary>
        [Required]
        public int? OfType
        {
            get => _OfType;
            set => _OfType = value;
        }

        private string? _ForZones;
        /// <summary>
        /// ForZones,comma-delim list of zones names to override all and run these specifically
        /// </summary>
        public string? ForZones
        {
            get => _ForZones;
            set => _ForZones = value;
        }

        private DateTime? _ForDate;
        /// <summary>
        /// ForDate,Optional datetime of when to make this template dispatch for
        /// </summary>
        public DateTime? ForDate
        {
            get => _ForDate;
            set => _ForDate = value;
        }

        #endregion

    }
}