// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerLocationAttributeById
//     Last Modified On: 5/29/2024 2:46:28 PM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for CustomerLocationAttributeById service.
    /// </summary>
    public partial class CustomerLocationAttributeByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of CustomerLocationAttributeByIdResult.
        /// </summary>
        public CustomerLocationAttributeByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for CustomerLocationAttributeById service.
    /// </summary>


    public partial class CustomerLocationAttributeByIdResult
	{
        /// <summary>
        /// Result set object for CustomerLocationAttributeById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Context">Maps to table value column Context.</param>
        /// <param name="AttributeName">Maps to table value column AttributeName.</param>
        /// <param name="DataTypeId">Maps to table value column DataTypeId.</param>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="CustomerName">Maps to table value column CustomerName.</param>
        /// <param name="CustomerLocationId">Maps to table value column CustomerLocationId.</param>
        /// <param name="LocName">Maps to table value column LocName.</param>
        /// <param name="DataType">Maps to table value column DataType.</param>
        /// <param name="AttributeContextName">Maps to table value column AttributeContextName.</param>
        /// <param name="AttributeId">Maps to table value column AttributeId.</param>
        /// <param name="Required">Maps to table value column Required.</param>
        /// <param name="DisplayOrder">Maps to table value column DisplayOrder.</param>
        /// <param name="LastModifiedBy">Maps to table value column LastModifiedBy.</param>
        /// <param name="LastModifiedDate">Maps to table value column LastModifiedDate.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        public CustomerLocationAttributeByIdResult(int Id, int Context, string AttributeName, int DataTypeId, int CustomerId, string CustomerName, int CustomerLocationId, string LocName, string DataType, string AttributeContextName, int AttributeId, bool Required, int DisplayOrder, int LastModifiedBy, DateTime LastModifiedDate, bool Active)
        {
             this.Id = Id;
             this.Context = Context;
             this.AttributeName = AttributeName;
             this.DataTypeId = DataTypeId;
             this.CustomerId = CustomerId;
             this.CustomerName = CustomerName;
             this.CustomerLocationId = CustomerLocationId;
             this.LocName = LocName;
             this.DataType = DataType;
             this.AttributeContextName = AttributeContextName;
             this.AttributeId = AttributeId;
             this.Required = Required;
             this.DisplayOrder = DisplayOrder;
             this.LastModifiedBy = LastModifiedBy;
             this.LastModifiedDate = LastModifiedDate;
             this.Active = Active;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Context.
        /// </summary>
        public int Context { set; get; }

        /// <summary>
        /// Maps to table value column AttributeName.
        /// </summary>
        public string AttributeName { set; get; }

        /// <summary>
        /// Maps to table value column DataTypeId.
        /// </summary>
        public int DataTypeId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerName.
        /// </summary>
        public string CustomerName { set; get; }

        /// <summary>
        /// Maps to table value column CustomerLocationId.
        /// </summary>
        public int CustomerLocationId { set; get; }

        /// <summary>
        /// Maps to table value column LocName.
        /// </summary>
        public string LocName { set; get; }

        /// <summary>
        /// Maps to table value column DataType.
        /// </summary>
        public string DataType { set; get; }

        /// <summary>
        /// Maps to table value column AttributeContextName.
        /// </summary>
        public string AttributeContextName { set; get; }

        /// <summary>
        /// Maps to table value column AttributeId.
        /// </summary>
        public int AttributeId { set; get; }

        /// <summary>
        /// Maps to table value column Required.
        /// </summary>
        public bool Required { set; get; }

        /// <summary>
        /// Maps to table value column DisplayOrder.
        /// </summary>
        public int DisplayOrder { set; get; }

        /// <summary>
        /// Maps to table value column LastModifiedBy.
        /// </summary>
        public int LastModifiedBy { set; get; }

        /// <summary>
        /// Maps to table value column LastModifiedDate.
        /// </summary>
        public DateTime LastModifiedDate { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }
    }

    #endregion Result Set Objects

}
