// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerLookup
//     Last Modified On: 9/28/2023 5:17:00 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the CustomerLookup service.
    /// </summary>
    public partial class CustomerLookupInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for CustomerLookupInput.
        /// </summary>
        public CustomerLookupInput() { }

        /// <summary>
        /// Parameterized constructor for CustomerLookupInput.
        /// </summary>
        /// <param name="SearchTerm">SearchTerm</param>
        /// <param name="CustomerId">CustomerId</param>
        /// <param name="CustNo">LocationId</param>
        public CustomerLookupInput(string? SearchTerm, int? CustomerId, int? CustNo)
        {
            this.SearchTerm = SearchTerm;
            this.CustomerId = CustomerId;
            this.CustNo = CustNo;
        }

        #endregion Constructors

        #region Fields

        private string? _SearchTerm;
        /// <summary>
        /// SearchTerm
        /// </summary>
        public string? SearchTerm
        {
            get => _SearchTerm;
            set => _SearchTerm = value;
        }

        private int? _CustomerId;
        /// <summary>
        /// CustomerId
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private int? _CustNo;
        /// <summary>
        /// LocationId
        /// </summary>
        public int? CustNo
        {
            get => _CustNo;
            set => _CustNo = value;
        }

        #endregion

    }
}