// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DataServiceList
//     Last Modified On: 1/17/2024 9:42:42 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for DataServiceList service.
    /// </summary>
    public partial class DataServiceListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of DataServiceListResult.
        /// </summary>
        public List<DataServiceListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for DataServiceList service.
    /// </summary>


    public partial class DataServiceListResult
	{
        /// <summary>
        /// Result set object for DataServiceList.
        /// </summary>
        /// <param name="DataServiceId">Maps to table value column DataServiceId.</param>
        /// <param name="Decription">Maps to table value column Decription.</param>
        /// <param name="Enum">Maps to table value column Enum.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Procedure">Maps to table value column Procedure.</param>
        /// <param name="Schema">Maps to table value column Schema.</param>
        /// <param name="Activities">Maps to table value column Activities.</param>
        /// <param name="ProcessingActive">Maps to table value column ProcessingActive.</param>
        public DataServiceListResult(int DataServiceId, string Decription, string Enum, string Name, string Procedure, string Schema, string? Activities, bool ProcessingActive)
        {
             this.DataServiceId = DataServiceId;
             this.Decription = Decription;
             this.Enum = Enum;
             this.Name = Name;
             this.Procedure = Procedure;
             this.Schema = Schema;
             this.Activities = Activities;
             this.ProcessingActive = ProcessingActive;
        }


        /// <summary>
        /// Maps to table value column DataServiceId.
        /// </summary>
        public int DataServiceId { set; get; }

        /// <summary>
        /// Maps to table value column Decription.
        /// </summary>
        public string Decription { set; get; }

        /// <summary>
        /// Maps to table value column Enum.
        /// </summary>
        public string Enum { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Procedure.
        /// </summary>
        public string Procedure { set; get; }

        /// <summary>
        /// Maps to table value column Schema.
        /// </summary>
        public string Schema { set; get; }

        /// <summary>
        /// Maps to table value column Activities.
        /// </summary>
        public string? Activities { set; get; }

        /// <summary>
        /// Maps to table value column ProcessingActive.
        /// </summary>
        public bool ProcessingActive { set; get; }
    }

    #endregion Result Set Objects

}
