// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DispatchCriticalJobsAlert
//     Last Modified On: 6/11/2025 12:32:27 AM
//     Written By: kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for DispatchCriticalJobsAlert service.
    /// </summary>
    public partial class DispatchCriticalJobsAlertOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of DispatchCriticalJobsAlertResult.
        /// </summary>
        public List<DispatchCriticalJobsAlertResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for DispatchCriticalJobsAlert service.
    /// </summary>


    public partial class DispatchCriticalJobsAlertResult
	{
        /// <summary>
        /// Result set object for DispatchCriticalJobsAlert.
        /// </summary>
        /// <param name="DispatchId">Maps to table value column DispatchId.</param>
        /// <param name="ZoneName">Maps to table value column ZoneName.</param>
        /// <param name="CustomerAddress">Maps to table value column CustomerAddress.</param>
        /// <param name="CustomerName">Maps to table value column CustomerName.</param>
        /// <param name="ClientWorkOrder">Maps to table value column ClientWorkOrder.</param>
        /// <param name="PurchaseOrderNumber">Maps to table value column PurchaseOrderNumber.</param>
        /// <param name="Tasks">Maps to table value column Tasks.</param>
        /// <param name="Priority">Maps to table value column Priority.</param>
        /// <param name="PriorityCategory">Maps to table value column PriorityCategory.</param>
        /// <param name="DueDate">Maps to table value column DueDate.</param>
        /// <param name="MinutesUntilDue">Maps to table value column MinutesUntilDue.</param>
        /// <param name="Urgency">Maps to table value column Urgency.</param>
        /// <param name="AssignedTechId">Maps to table value column AssignedTechId.</param>
        /// <param name="AssignedTechnician">Maps to table value column AssignedTechnician.</param>
        /// <param name="TechLatitude">Maps to table value column TechLatitude.</param>
        /// <param name="TechLongitude">Maps to table value column TechLongitude.</param>
        /// <param name="TechLastAddress">Maps to table value column TechLastAddress.</param>
        /// <param name="VehicleSpeed">Maps to table value column VehicleSpeed.</param>
        /// <param name="TechIsOnJob">Maps to table value column TechIsOnJob.</param>
        /// <param name="TechDistanceInMiles">Maps to table value column TechDistanceInMiles.</param>
        /// <param name="EstimatedTravelMinutes">Maps to table value column EstimatedTravelMinutes.</param>
        public DispatchCriticalJobsAlertResult(int DispatchId, string ZoneName, string CustomerAddress, string CustomerName, string ClientWorkOrder, string? PurchaseOrderNumber, string? Tasks, string Priority, string PriorityCategory, DateTimeOffset? DueDate, int? MinutesUntilDue, string Urgency, int? AssignedTechId, string AssignedTechnician, decimal? TechLatitude, decimal? TechLongitude, string? TechLastAddress, double? VehicleSpeed, bool? TechIsOnJob, double? TechDistanceInMiles, double? EstimatedTravelMinutes)
        {
             this.DispatchId = DispatchId;
             this.ZoneName = ZoneName;
             this.CustomerAddress = CustomerAddress;
             this.CustomerName = CustomerName;
             this.ClientWorkOrder = ClientWorkOrder;
             this.PurchaseOrderNumber = PurchaseOrderNumber;
             this.Tasks = Tasks;
             this.Priority = Priority;
             this.PriorityCategory = PriorityCategory;
             this.DueDate = DueDate;
             this.MinutesUntilDue = MinutesUntilDue;
             this.Urgency = Urgency;
             this.AssignedTechId = AssignedTechId;
             this.AssignedTechnician = AssignedTechnician;
             this.TechLatitude = TechLatitude;
             this.TechLongitude = TechLongitude;
             this.TechLastAddress = TechLastAddress;
             this.VehicleSpeed = VehicleSpeed;
             this.TechIsOnJob = TechIsOnJob;
             this.TechDistanceInMiles = TechDistanceInMiles;
             this.EstimatedTravelMinutes = EstimatedTravelMinutes;
        }


        /// <summary>
        /// Maps to table value column DispatchId.
        /// </summary>
        public int DispatchId { set; get; }

        /// <summary>
        /// Maps to table value column ZoneName.
        /// </summary>
        public string ZoneName { set; get; }

        /// <summary>
        /// Maps to table value column CustomerAddress.
        /// </summary>
        public string CustomerAddress { set; get; }

        /// <summary>
        /// Maps to table value column CustomerName.
        /// </summary>
        public string CustomerName { set; get; }

        /// <summary>
        /// Maps to table value column ClientWorkOrder.
        /// </summary>
        public string ClientWorkOrder { set; get; }

        /// <summary>
        /// Maps to table value column PurchaseOrderNumber.
        /// </summary>
        public string? PurchaseOrderNumber { set; get; }

        /// <summary>
        /// Maps to table value column Tasks.
        /// </summary>
        public string? Tasks { set; get; }

        /// <summary>
        /// Maps to table value column Priority.
        /// </summary>
        public string Priority { set; get; }

        /// <summary>
        /// Maps to table value column PriorityCategory.
        /// </summary>
        public string PriorityCategory { set; get; }

        /// <summary>
        /// Maps to table value column DueDate.
        /// </summary>
        public DateTimeOffset? DueDate { set; get; }

        /// <summary>
        /// Maps to table value column MinutesUntilDue.
        /// </summary>
        public int? MinutesUntilDue { set; get; }

        /// <summary>
        /// Maps to table value column Urgency.
        /// </summary>
        public string Urgency { set; get; }

        /// <summary>
        /// Maps to table value column AssignedTechId.
        /// </summary>
        public int? AssignedTechId { set; get; }

        /// <summary>
        /// Maps to table value column AssignedTechnician.
        /// </summary>
        public string AssignedTechnician { set; get; }

        /// <summary>
        /// Maps to table value column TechLatitude.
        /// </summary>
        public decimal? TechLatitude { set; get; }

        /// <summary>
        /// Maps to table value column TechLongitude.
        /// </summary>
        public decimal? TechLongitude { set; get; }

        /// <summary>
        /// Maps to table value column TechLastAddress.
        /// </summary>
        public string? TechLastAddress { set; get; }

        /// <summary>
        /// Maps to table value column VehicleSpeed.
        /// </summary>
        public double? VehicleSpeed { set; get; }

        /// <summary>
        /// Maps to table value column TechIsOnJob.
        /// </summary>
        public bool? TechIsOnJob { set; get; }

        /// <summary>
        /// Maps to table value column TechDistanceInMiles.
        /// </summary>
        public double? TechDistanceInMiles { set; get; }

        /// <summary>
        /// Maps to table value column EstimatedTravelMinutes.
        /// </summary>
        public double? EstimatedTravelMinutes { set; get; }
    }

    #endregion Result Set Objects

}
