// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DispatchList
//     Last Modified On: 1/2/2025 6:29:05 PM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the DispatchList service.
    /// </summary>
    public partial class DispatchListInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for DispatchListInput.
        /// </summary>
        public DispatchListInput() { }

        /// <summary>
        /// Parameterized constructor for DispatchListInput.
        /// </summary>
        /// <param name="EmployeeId">EmployeeId</param>
        /// <param name="StatusExclude">StatusExclude</param>
        /// <param name="DateFilter">DateFilter</param>
        public DispatchListInput(int? EmployeeId, string? StatusExclude, DateTime? DateFilter)
        {
            this.EmployeeId = EmployeeId;
            this.StatusExclude = StatusExclude;
            this.DateFilter = DateFilter;
        }

        #endregion Constructors

        #region Fields

        private int? _EmployeeId;
        /// <summary>
        /// EmployeeId
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private string? _StatusExclude;
        /// <summary>
        /// StatusExclude
        /// </summary>
        public string? StatusExclude
        {
            get => _StatusExclude;
            set => _StatusExclude = value;
        }

        private DateTime? _DateFilter;
        /// <summary>
        /// DateFilter
        /// </summary>
        public DateTime? DateFilter
        {
            get => _DateFilter;
            set => _DateFilter = value;
        }

        #endregion

    }
}