// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DynamicGroupsQuery
//     Last Modified On: 4/8/2025 11:59:58 PM
//     Written By: kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the DynamicGroupsQuery service.
    /// </summary>
    public partial class DynamicGroupsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for DynamicGroupsQueryInput.
        /// </summary>
        public DynamicGroupsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for DynamicGroupsQueryInput.
        /// </summary>
        /// <param name="EntityTypeId">EntityTypeId</param>
        /// <param name="Name">Name</param>
        /// <param name="Active">Active</param>
        public DynamicGroupsQueryInput(int? EntityTypeId, string? Name, bool? Active)
        {
            this.EntityTypeId = EntityTypeId;
            this.Name = Name;
            this.Active = Active;
        }

        #endregion Constructors

        #region Fields

        private int? _EntityTypeId = null;
        /// <summary>
        /// EntityTypeId
        /// </summary>
        public int? EntityTypeId
        {
            get => _EntityTypeId;
            set => _EntityTypeId = value;
        }

        private string? _Name = null;
        /// <summary>
        /// Name
        /// </summary>
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private bool? _Active = null;
        /// <summary>
        /// Active
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        #endregion

    }
}