// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DynamicGroupMatch
//     Last Modified On: 1/12/2026 11:22:30 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the DynamicGroupMatch service.
    /// </summary>
    public partial class DynamicGroupMatchInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for DynamicGroupMatchInput.
        /// </summary>
        public DynamicGroupMatchInput() { }

        /// <summary>
        /// Parameterized constructor for DynamicGroupMatchInput.
        /// </summary>
        /// <param name="DynGrpId">DynGrpId,Specific Rule to Run</param>
        /// <param name="EntityTypeId">EntityTypeId,Specific EntityType</param>
        /// <param name="ActualValue">ActualValue,Specific ActualValue if to return only finaloutput</param>
        public DynamicGroupMatchInput(int? DynGrpId, int? EntityTypeId, int? ActualValue)
        {
            this.DynGrpId = DynGrpId;
            this.EntityTypeId = EntityTypeId;
            this.ActualValue = ActualValue;
        }

        #endregion Constructors

        #region Fields

        private int? _DynGrpId = 0;
        /// <summary>
        /// DynGrpId,Specific Rule to Run
        /// </summary>
        public int? DynGrpId
        {
            get => _DynGrpId;
            set => _DynGrpId = value;
        }

        private int? _EntityTypeId = 0;
        /// <summary>
        /// EntityTypeId,Specific EntityType
        /// </summary>
        public int? EntityTypeId
        {
            get => _EntityTypeId;
            set => _EntityTypeId = value;
        }

        private int? _ActualValue = 0;
        /// <summary>
        /// ActualValue,Specific ActualValue if to return only finaloutput
        /// </summary>
        public int? ActualValue
        {
            get => _ActualValue;
            set => _ActualValue = value;
        }

        #endregion

    }
}