// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DynamicGroupsQuery
//     Last Modified On: 4/8/2025 11:59:58 PM
//     Written By: kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for DynamicGroupsQuery service.
    /// </summary>
    public partial class DynamicGroupsQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of DynamicGroupsQueryResult.
        /// </summary>
        public List<DynamicGroupsQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for DynamicGroupsQuery service.
    /// </summary>


    public partial class DynamicGroupsQueryResult
	{
        /// <summary>
        /// Result set object for DynamicGroupsQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="EntityTypeId">Maps to table value column EntityTypeId.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Pattern">Maps to table value column Pattern.</param>
        /// <param name="PatternExclude">Maps to table value column PatternExclude.</param>
        /// <param name="PatternDelim">Maps to table value column PatternDelim.</param>
        /// <param name="DeepSearch">Maps to table value column DeepSearch.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        /// <param name="CreatedBy">Maps to table value column CreatedBy.</param>
        /// <param name="CreatedDate">Maps to table value column CreatedDate.</param>
        /// <param name="ModifiedBy">Maps to table value column ModifiedBy.</param>
        /// <param name="ModifiedDate">Maps to table value column ModifiedDate.</param>
        public DynamicGroupsQueryResult(int Id, int EntityTypeId, string Name, string Pattern, string? PatternExclude, string PatternDelim, bool DeepSearch, bool Active, string? Notes, int CreatedBy, DateTime CreatedDate, int ModifiedBy, DateTime ModifiedDate)
        {
             this.Id = Id;
             this.EntityTypeId = EntityTypeId;
             this.Name = Name;
             this.Pattern = Pattern;
             this.PatternExclude = PatternExclude;
             this.PatternDelim = PatternDelim;
             this.DeepSearch = DeepSearch;
             this.Active = Active;
             this.Notes = Notes;
             this.CreatedBy = CreatedBy;
             this.CreatedDate = CreatedDate;
             this.ModifiedBy = ModifiedBy;
             this.ModifiedDate = ModifiedDate;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column EntityTypeId.
        /// </summary>
        public int EntityTypeId { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Pattern.
        /// </summary>
        public string Pattern { set; get; }

        /// <summary>
        /// Maps to table value column PatternExclude.
        /// </summary>
        public string? PatternExclude { set; get; }

        /// <summary>
        /// Maps to table value column PatternDelim.
        /// </summary>
        public string PatternDelim { set; get; }

        /// <summary>
        /// Maps to table value column DeepSearch.
        /// </summary>
        public bool DeepSearch { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }

        /// <summary>
        /// Maps to table value column CreatedBy.
        /// </summary>
        public int CreatedBy { set; get; }

        /// <summary>
        /// Maps to table value column CreatedDate.
        /// </summary>
        public DateTime CreatedDate { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedBy.
        /// </summary>
        public int ModifiedBy { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedDate.
        /// </summary>
        public DateTime ModifiedDate { set; get; }
    }

    #endregion Result Set Objects

}
