// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: EquipmentTypeQuery
//     Last Modified On: 4/16/2025 4:44:22 PM
//     Written By: Kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for EquipmentTypeQuery service.
    /// </summary>
    public partial class EquipmentTypeQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of EquipmentTypeQueryResult.
        /// </summary>
        public List<EquipmentTypeQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for EquipmentTypeQuery service.
    /// </summary>


    public partial class EquipmentTypeQueryResult
	{
        /// <summary>
        /// Result set object for EquipmentTypeQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="TypeName">Maps to table value column TypeName.</param>
        /// <param name="ESCEqType">Maps to table value column ESCEqType.</param>
        /// <param name="EntityId">Maps to table value column EntityId.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="Category">Maps to table value column Category.</param>
        public EquipmentTypeQueryResult(int Id, string TypeName, string? ESCEqType, int EntityId, string Description, bool Active, int Category)
        {
             this.Id = Id;
             this.TypeName = TypeName;
             this.ESCEqType = ESCEqType;
             this.EntityId = EntityId;
             this.Description = Description;
             this.Active = Active;
             this.Category = Category;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column TypeName.
        /// </summary>
        public string TypeName { set; get; }

        /// <summary>
        /// Maps to table value column ESCEqType.
        /// </summary>
        public string? ESCEqType { set; get; }

        /// <summary>
        /// Maps to table value column EntityId.
        /// </summary>
        public int EntityId { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column Category.
        /// </summary>
        public int Category { set; get; }
    }

    #endregion Result Set Objects

}
