// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: EquipmentMfgById
//     Last Modified On: 3/5/2024 10:53:38 PM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the EquipmentMfgById service.
    /// </summary>
    public partial class EquipmentMfgByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for EquipmentMfgByIdInput.
        /// </summary>
        public EquipmentMfgByIdInput() { }

        /// <summary>
        /// Parameterized constructor for EquipmentMfgByIdInput.
        /// </summary>
        /// <param name="Id">Active</param>
        public EquipmentMfgByIdInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Active
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}