// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: EquipmentTypeAttributeList
//     Last Modified On: 5/29/2024 2:47:21 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the EquipmentTypeAttributeList service.
    /// </summary>
    public partial class EquipmentTypeAttributeListInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for EquipmentTypeAttributeListInput.
        /// </summary>
        public EquipmentTypeAttributeListInput() { }

        /// <summary>
        /// Parameterized constructor for EquipmentTypeAttributeListInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="AttributeId">Maps to parameter @AttributeId.</param>
        /// <param name="EquipmentTypeId">Maps to parameter @EquipmentTypeId.</param>
        public EquipmentTypeAttributeListInput(int? Id, int? AttributeId, int? EquipmentTypeId)
        {
            this.Id = Id;
            this.AttributeId = AttributeId;
            this.EquipmentTypeId = EquipmentTypeId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _AttributeId;
        /// <summary>
        /// Maps to parameter @AttributeId.
        /// </summary>
        public int? AttributeId
        {
            get => _AttributeId;
            set => _AttributeId = value;
        }

        private int? _EquipmentTypeId;
        /// <summary>
        /// Maps to parameter @EquipmentTypeId.
        /// </summary>
        public int? EquipmentTypeId
        {
            get => _EquipmentTypeId;
            set => _EquipmentTypeId = value;
        }

        #endregion

    }
}