// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: EquipmentList
//     Last Modified On: 4/29/2025 1:12:23 AM
//     Written By: Kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for EquipmentList service.
    /// </summary>
    public partial class EquipmentListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of EquipmentListResult.
        /// </summary>
        public List<EquipmentListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for EquipmentList service.
    /// </summary>


    public partial class EquipmentListResult
	{
        /// <summary>
        /// Result set object for EquipmentList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="TemporaryId">Maps to table value column TemporaryId.</param>
        /// <param name="CustomerLocationId">Maps to table value column CustomerLocationId.</param>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="Customer">Maps to table value column Customer.</param>
        /// <param name="LocName">Maps to table value column LocName.</param>
        /// <param name="LocInActive">Maps to table value column LocInActive.</param>
        /// <param name="EquipmentTypeId">Maps to table value column EquipmentTypeId.</param>
        /// <param name="EquipmentType">Maps to table value column EquipmentType.</param>
        /// <param name="EqType">Maps to table value column EqType.</param>
        /// <param name="UnitTag">Maps to table value column UnitTag.</param>
        /// <param name="EquipLocArea">Maps to table value column EquipLocArea.</param>
        /// <param name="EquipmentMfg">Maps to table value column EquipmentMfg.</param>
        /// <param name="Make">Maps to table value column Make.</param>
        /// <param name="Model">Maps to table value column Model.</param>
        /// <param name="Serial">Maps to table value column Serial.</param>
        /// <param name="IsRetired">Maps to table value column IsRetired.</param>
        /// <param name="EquipmentGroup">Maps to table value column EquipmentGroup.</param>
        /// <param name="MfgDate">Maps to table value column MfgDate.</param>
        /// <param name="MfgDateDaysAgo">Maps to table value column MfgDateDaysAgo.</param>
        /// <param name="InstallationDate">Maps to table value column InstallationDate.</param>
        /// <param name="InstallationDaysAgo">Maps to table value column InstallationDaysAgo.</param>
        /// <param name="WarrantyEndDate">Maps to table value column WarrantyEndDate.</param>
        /// <param name="WarrantyEndDaysAgo">Maps to table value column WarrantyEndDaysAgo.</param>
        /// <param name="Invoice">Maps to table value column Invoice.</param>
        /// <param name="AreaServed">Maps to table value column AreaServed.</param>
        /// <param name="Refrigerant">Maps to table value column Refrigerant.</param>
        /// <param name="VoltagePhase">Maps to table value column VoltagePhase.</param>
        /// <param name="Tonnage">Maps to table value column Tonnage.</param>
        /// <param name="HeatSize">Maps to table value column HeatSize.</param>
        /// <param name="FilterQty">Maps to table value column FilterQty.</param>
        /// <param name="FilterSize">Maps to table value column FilterSize.</param>
        /// <param name="BeltSize">Maps to table value column BeltSize.</param>
        /// <param name="DataPlateFileName">Maps to table value column DataPlateFileName.</param>
        /// <param name="UnitImage1FileName">Maps to table value column UnitImage1FileName.</param>
        /// <param name="UnitImage2FileName">Maps to table value column UnitImage2FileName.</param>
        /// <param name="ExternalKey">Maps to table value column ExternalKey.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        /// <param name="Tags">Maps to table value column Tags.</param>
        /// <param name="EntityId">Maps to table value column EntityId.</param>
        /// <param name="CreatedBy">Maps to table value column CreatedBy.</param>
        /// <param name="CreatedDate">Maps to table value column CreatedDate.</param>
        /// <param name="ModifiedBy">Maps to table value column ModifiedBy.</param>
        /// <param name="ModifiedDate">Maps to table value column ModifiedDate.</param>
        /// <param name="Hash">Maps to table value column Hash.</param>
        public EquipmentListResult(int Id, Guid? TemporaryId, int CustomerLocationId, int CustomerId, string Customer, string LocName, short LocInActive, int EquipmentTypeId, string EquipmentType, string EqType, string UnitTag, string EquipLocArea, string EquipmentMfg, string Make, string Model, string Serial, bool IsRetired, string? EquipmentGroup, DateTime? MfgDate, int MfgDateDaysAgo, DateTimeOffset? InstallationDate, int InstallationDaysAgo, DateTimeOffset? WarrantyEndDate, int WarrantyEndDaysAgo, string? Invoice, string? AreaServed, string? Refrigerant, string? VoltagePhase, string? Tonnage, string? HeatSize, string? FilterQty, string? FilterSize, string? BeltSize, string? DataPlateFileName, string? UnitImage1FileName, string? UnitImage2FileName, string? ExternalKey, string? Notes, string? Tags, string EntityId, int CreatedBy, DateTime CreatedDate, int ModifiedBy, DateTime ModifiedDate, int Hash)
        {
             this.Id = Id;
             this.TemporaryId = TemporaryId;
             this.CustomerLocationId = CustomerLocationId;
             this.CustomerId = CustomerId;
             this.Customer = Customer;
             this.LocName = LocName;
             this.LocInActive = LocInActive;
             this.EquipmentTypeId = EquipmentTypeId;
             this.EquipmentType = EquipmentType;
             this.EqType = EqType;
             this.UnitTag = UnitTag;
             this.EquipLocArea = EquipLocArea;
             this.EquipmentMfg = EquipmentMfg;
             this.Make = Make;
             this.Model = Model;
             this.Serial = Serial;
             this.IsRetired = IsRetired;
             this.EquipmentGroup = EquipmentGroup;
             this.MfgDate = MfgDate;
             this.MfgDateDaysAgo = MfgDateDaysAgo;
             this.InstallationDate = InstallationDate;
             this.InstallationDaysAgo = InstallationDaysAgo;
             this.WarrantyEndDate = WarrantyEndDate;
             this.WarrantyEndDaysAgo = WarrantyEndDaysAgo;
             this.Invoice = Invoice;
             this.AreaServed = AreaServed;
             this.Refrigerant = Refrigerant;
             this.VoltagePhase = VoltagePhase;
             this.Tonnage = Tonnage;
             this.HeatSize = HeatSize;
             this.FilterQty = FilterQty;
             this.FilterSize = FilterSize;
             this.BeltSize = BeltSize;
             this.DataPlateFileName = DataPlateFileName;
             this.UnitImage1FileName = UnitImage1FileName;
             this.UnitImage2FileName = UnitImage2FileName;
             this.ExternalKey = ExternalKey;
             this.Notes = Notes;
             this.Tags = Tags;
             this.EntityId = EntityId;
             this.CreatedBy = CreatedBy;
             this.CreatedDate = CreatedDate;
             this.ModifiedBy = ModifiedBy;
             this.ModifiedDate = ModifiedDate;
             this.Hash = Hash;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column TemporaryId.
        /// </summary>
        public Guid? TemporaryId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerLocationId.
        /// </summary>
        public int CustomerLocationId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column Customer.
        /// </summary>
        public string Customer { set; get; }

        /// <summary>
        /// Maps to table value column LocName.
        /// </summary>
        public string LocName { set; get; }

        /// <summary>
        /// Maps to table value column LocInActive.
        /// </summary>
        public short LocInActive { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentTypeId.
        /// </summary>
        public int EquipmentTypeId { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentType.
        /// </summary>
        public string EquipmentType { set; get; }

        /// <summary>
        /// Maps to table value column EqType.
        /// </summary>
        public string EqType { set; get; }

        /// <summary>
        /// Maps to table value column UnitTag.
        /// </summary>
        public string UnitTag { set; get; }

        /// <summary>
        /// Maps to table value column EquipLocArea.
        /// </summary>
        public string EquipLocArea { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentMfg.
        /// </summary>
        public string EquipmentMfg { set; get; }

        /// <summary>
        /// Maps to table value column Make.
        /// </summary>
        public string Make { set; get; }

        /// <summary>
        /// Maps to table value column Model.
        /// </summary>
        public string Model { set; get; }

        /// <summary>
        /// Maps to table value column Serial.
        /// </summary>
        public string Serial { set; get; }

        /// <summary>
        /// Maps to table value column IsRetired.
        /// </summary>
        public bool IsRetired { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentGroup.
        /// </summary>
        public string? EquipmentGroup { set; get; }

        /// <summary>
        /// Maps to table value column MfgDate.
        /// </summary>
        public DateTime? MfgDate { set; get; }

        /// <summary>
        /// Maps to table value column MfgDateDaysAgo.
        /// </summary>
        public int MfgDateDaysAgo { set; get; }

        /// <summary>
        /// Maps to table value column InstallationDate.
        /// </summary>
        public DateTimeOffset? InstallationDate { set; get; }

        /// <summary>
        /// Maps to table value column InstallationDaysAgo.
        /// </summary>
        public int InstallationDaysAgo { set; get; }

        /// <summary>
        /// Maps to table value column WarrantyEndDate.
        /// </summary>
        public DateTimeOffset? WarrantyEndDate { set; get; }

        /// <summary>
        /// Maps to table value column WarrantyEndDaysAgo.
        /// </summary>
        public int WarrantyEndDaysAgo { set; get; }

        /// <summary>
        /// Maps to table value column Invoice.
        /// </summary>
        public string? Invoice { set; get; }

        /// <summary>
        /// Maps to table value column AreaServed.
        /// </summary>
        public string? AreaServed { set; get; }

        /// <summary>
        /// Maps to table value column Refrigerant.
        /// </summary>
        public string? Refrigerant { set; get; }

        /// <summary>
        /// Maps to table value column VoltagePhase.
        /// </summary>
        public string? VoltagePhase { set; get; }

        /// <summary>
        /// Maps to table value column Tonnage.
        /// </summary>
        public string? Tonnage { set; get; }

        /// <summary>
        /// Maps to table value column HeatSize.
        /// </summary>
        public string? HeatSize { set; get; }

        /// <summary>
        /// Maps to table value column FilterQty.
        /// </summary>
        public string? FilterQty { set; get; }

        /// <summary>
        /// Maps to table value column FilterSize.
        /// </summary>
        public string? FilterSize { set; get; }

        /// <summary>
        /// Maps to table value column BeltSize.
        /// </summary>
        public string? BeltSize { set; get; }

        /// <summary>
        /// Maps to table value column DataPlateFileName.
        /// </summary>
        public string? DataPlateFileName { set; get; }

        /// <summary>
        /// Maps to table value column UnitImage1FileName.
        /// </summary>
        public string? UnitImage1FileName { set; get; }

        /// <summary>
        /// Maps to table value column UnitImage2FileName.
        /// </summary>
        public string? UnitImage2FileName { set; get; }

        /// <summary>
        /// Maps to table value column ExternalKey.
        /// </summary>
        public string? ExternalKey { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }

        /// <summary>
        /// Maps to table value column Tags.
        /// </summary>
        public string? Tags { set; get; }

        /// <summary>
        /// Maps to table value column EntityId.
        /// </summary>
        public string EntityId { set; get; }

        /// <summary>
        /// Maps to table value column CreatedBy.
        /// </summary>
        public int CreatedBy { set; get; }

        /// <summary>
        /// Maps to table value column CreatedDate.
        /// </summary>
        public DateTime CreatedDate { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedBy.
        /// </summary>
        public int ModifiedBy { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedDate.
        /// </summary>
        public DateTime ModifiedDate { set; get; }

        /// <summary>
        /// Maps to table value column Hash.
        /// </summary>
        public int Hash { set; get; }
    }

    #endregion Result Set Objects

}
