// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_DispTechQuery
//     Last Modified On: 2/22/2024 3:01:14 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the h_DispTechQuery service.
    /// </summary>
    public partial class h_DispTechQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for h_DispTechQueryInput.
        /// </summary>
        public h_DispTechQueryInput() { }

        /// <summary>
        /// Parameterized constructor for h_DispTechQueryInput.
        /// </summary>
        /// <param name="Dispatch">Dispatch</param>
        /// <param name="TechId">TechId</param>
        /// <param name="TechLine">TechLine</param>
        /// <param name="TechStatus">TechStatus</param>
        /// <param name="TechDispDate">TechDispDate</param>
        /// <param name="TechFullName">TechFullName</param>
        /// <param name="TechTravelHrs">TechTravelHrs</param>
        /// <param name="TechWorkHrs">TechWorkHrs</param>
        /// <param name="TechTotalHrs">TechTotalHrs</param>
        public h_DispTechQueryInput(string? Dispatch, string? TechId, string? TechLine, string? TechStatus, string? TechDispDate, string? TechFullName, double? TechTravelHrs, double? TechWorkHrs, double? TechTotalHrs)
        {
            this.Dispatch = Dispatch;
            this.TechId = TechId;
            this.TechLine = TechLine;
            this.TechStatus = TechStatus;
            this.TechDispDate = TechDispDate;
            this.TechFullName = TechFullName;
            this.TechTravelHrs = TechTravelHrs;
            this.TechWorkHrs = TechWorkHrs;
            this.TechTotalHrs = TechTotalHrs;
        }

        #endregion Constructors

        #region Fields

        private string? _Dispatch;
        /// <summary>
        /// Dispatch
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        private string? _TechId;
        /// <summary>
        /// TechId
        /// </summary>
        public string? TechId
        {
            get => _TechId;
            set => _TechId = value;
        }

        private string? _TechLine;
        /// <summary>
        /// TechLine
        /// </summary>
        public string? TechLine
        {
            get => _TechLine;
            set => _TechLine = value;
        }

        private string? _TechStatus;
        /// <summary>
        /// TechStatus
        /// </summary>
        public string? TechStatus
        {
            get => _TechStatus;
            set => _TechStatus = value;
        }

        private string? _TechDispDate;
        /// <summary>
        /// TechDispDate
        /// </summary>
        public string? TechDispDate
        {
            get => _TechDispDate;
            set => _TechDispDate = value;
        }

        private string? _TechFullName;
        /// <summary>
        /// TechFullName
        /// </summary>
        public string? TechFullName
        {
            get => _TechFullName;
            set => _TechFullName = value;
        }

        private double? _TechTravelHrs;
        /// <summary>
        /// TechTravelHrs
        /// </summary>
        public double? TechTravelHrs
        {
            get => _TechTravelHrs;
            set => _TechTravelHrs = value;
        }

        private double? _TechWorkHrs;
        /// <summary>
        /// TechWorkHrs
        /// </summary>
        public double? TechWorkHrs
        {
            get => _TechWorkHrs;
            set => _TechWorkHrs = value;
        }

        private double? _TechTotalHrs;
        /// <summary>
        /// TechTotalHrs
        /// </summary>
        public double? TechTotalHrs
        {
            get => _TechTotalHrs;
            set => _TechTotalHrs = value;
        }

        #endregion

    }
}