// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_InvoicesQuery
//     Last Modified On: 2/22/2024 5:09:02 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for h_InvoicesQuery service.
    /// </summary>
    public partial class h_InvoicesQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of h_InvoicesQueryResult.
        /// </summary>
        public List<h_InvoicesQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for h_InvoicesQuery service.
    /// </summary>


    public partial class h_InvoicesQueryResult
	{
        /// <summary>
        /// Result set object for h_InvoicesQuery.
        /// </summary>
        /// <param name="Dispatch">Maps to table value column Dispatch.</param>
        /// <param name="InvDate">Maps to table value column InvDate.</param>
        /// <param name="InvInvoice">Maps to table value column InvInvoice.</param>
        /// <param name="InvoiceAmt">Maps to table value column InvoiceAmt.</param>
        /// <param name="InvoiceTotal">Maps to table value column InvoiceTotal.</param>
        /// <param name="InvTaxCode">Maps to table value column InvTaxCode.</param>
        /// <param name="InvTerms">Maps to table value column InvTerms.</param>
        /// <param name="InvTax">Maps to table value column InvTax.</param>
        /// <param name="InvTaxable">Maps to table value column InvTaxable.</param>
        /// <param name="InvClerk">Maps to table value column InvClerk.</param>
        public h_InvoicesQueryResult(string Dispatch, string? InvDate, string? InvInvoice, decimal? InvoiceAmt, decimal? InvoiceTotal, string InvTaxCode, string InvTerms, decimal? InvTax, string InvTaxable, string InvClerk)
        {
             this.Dispatch = Dispatch;
             this.InvDate = InvDate;
             this.InvInvoice = InvInvoice;
             this.InvoiceAmt = InvoiceAmt;
             this.InvoiceTotal = InvoiceTotal;
             this.InvTaxCode = InvTaxCode;
             this.InvTerms = InvTerms;
             this.InvTax = InvTax;
             this.InvTaxable = InvTaxable;
             this.InvClerk = InvClerk;
        }


        /// <summary>
        /// Maps to table value column Dispatch.
        /// </summary>
        public string Dispatch { set; get; }

        /// <summary>
        /// Maps to table value column InvDate.
        /// </summary>
        public string? InvDate { set; get; }

        /// <summary>
        /// Maps to table value column InvInvoice.
        /// </summary>
        public string? InvInvoice { set; get; }

        /// <summary>
        /// Maps to table value column InvoiceAmt.
        /// </summary>
        public decimal? InvoiceAmt { set; get; }

        /// <summary>
        /// Maps to table value column InvoiceTotal.
        /// </summary>
        public decimal? InvoiceTotal { set; get; }

        /// <summary>
        /// Maps to table value column InvTaxCode.
        /// </summary>
        public string InvTaxCode { set; get; }

        /// <summary>
        /// Maps to table value column InvTerms.
        /// </summary>
        public string InvTerms { set; get; }

        /// <summary>
        /// Maps to table value column InvTax.
        /// </summary>
        public decimal? InvTax { set; get; }

        /// <summary>
        /// Maps to table value column InvTaxable.
        /// </summary>
        public string InvTaxable { set; get; }

        /// <summary>
        /// Maps to table value column InvClerk.
        /// </summary>
        public string InvClerk { set; get; }
    }

    #endregion Result Set Objects

}
