// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_POPartsQuery
//     Last Modified On: 2/22/2024 5:09:39 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the h_POPartsQuery service.
    /// </summary>
    public partial class h_POPartsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for h_POPartsQueryInput.
        /// </summary>
        public h_POPartsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for h_POPartsQueryInput.
        /// </summary>
        /// <param name="Dispatch">Dispatch</param>
        /// <param name="PONum">PONum</param>
        public h_POPartsQueryInput(string? Dispatch, string? PONum)
        {
            this.Dispatch = Dispatch;
            this.PONum = PONum;
        }

        #endregion Constructors

        #region Fields

        private string? _Dispatch;
        /// <summary>
        /// Dispatch
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        private string? _PONum;
        /// <summary>
        /// PONum
        /// </summary>
        public string? PONum
        {
            get => _PONum;
            set => _PONum = value;
        }

        #endregion

    }
}