// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_QBCustomersQuery
//     Last Modified On: 2/22/2024 3:04:27 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for h_QBCustomersQuery service.
    /// </summary>
    public partial class h_QBCustomersQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of h_QBCustomersQueryResult.
        /// </summary>
        public List<h_QBCustomersQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for h_QBCustomersQuery service.
    /// </summary>


    public partial class h_QBCustomersQueryResult
	{
        /// <summary>
        /// Result set object for h_QBCustomersQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="SyncToken">Maps to table value column SyncToken.</param>
        /// <param name="MetaData_CreateTime">Maps to table value column MetaData_CreateTime.</param>
        /// <param name="MetaData_LastUpdatedTime">Maps to table value column MetaData_LastUpdatedTime.</param>
        /// <param name="Title">Maps to table value column Title.</param>
        /// <param name="GivenName">Maps to table value column GivenName.</param>
        /// <param name="MiddleName">Maps to table value column MiddleName.</param>
        /// <param name="FamilyName">Maps to table value column FamilyName.</param>
        /// <param name="Suffix">Maps to table value column Suffix.</param>
        /// <param name="FullyQualifiedName">Maps to table value column FullyQualifiedName.</param>
        /// <param name="CompanyName">Maps to table value column CompanyName.</param>
        /// <param name="DisplayName">Maps to table value column DisplayName.</param>
        /// <param name="PrintOnCheckName">Maps to table value column PrintOnCheckName.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="IsProject">Maps to table value column IsProject.</param>
        /// <param name="PrimaryPhone_FreeFormNumber">Maps to table value column PrimaryPhone_FreeFormNumber.</param>
        /// <param name="AlternatePhone_FreeFormNumber">Maps to table value column AlternatePhone_FreeFormNumber.</param>
        /// <param name="Mobile_FreeFormNumber">Maps to table value column Mobile_FreeFormNumber.</param>
        /// <param name="Fax_FreeFormNumber">Maps to table value column Fax_FreeFormNumber.</param>
        /// <param name="PrimaryEmailAddr_Address">Maps to table value column PrimaryEmailAddr_Address.</param>
        /// <param name="WebAddr_URI">Maps to table value column WebAddr_URI.</param>
        /// <param name="DefaultTaxCodeRef">Maps to table value column DefaultTaxCodeRef.</param>
        /// <param name="Taxable">Maps to table value column Taxable.</param>
        /// <param name="CustomerTypeRef">Maps to table value column CustomerTypeRef.</param>
        /// <param name="BillAddr_Id">Maps to table value column BillAddr_Id.</param>
        /// <param name="BillAddr_Line1">Maps to table value column BillAddr_Line1.</param>
        /// <param name="BillAddr_Line2">Maps to table value column BillAddr_Line2.</param>
        /// <param name="BillAddr_Line3">Maps to table value column BillAddr_Line3.</param>
        /// <param name="BillAddr_Line4">Maps to table value column BillAddr_Line4.</param>
        /// <param name="BillAddr_Line5">Maps to table value column BillAddr_Line5.</param>
        /// <param name="BillAddr_City">Maps to table value column BillAddr_City.</param>
        /// <param name="BillAddr_Country">Maps to table value column BillAddr_Country.</param>
        /// <param name="BillAddr_CountrySubDivisionCode">Maps to table value column BillAddr_CountrySubDivisionCode.</param>
        /// <param name="BillAddr_PostalCode">Maps to table value column BillAddr_PostalCode.</param>
        /// <param name="BillAddr_Lat">Maps to table value column BillAddr_Lat.</param>
        /// <param name="BillAddr_Long">Maps to table value column BillAddr_Long.</param>
        /// <param name="ShipAddr_Id">Maps to table value column ShipAddr_Id.</param>
        /// <param name="ShipAddr_Line1">Maps to table value column ShipAddr_Line1.</param>
        /// <param name="ShipAddr_Line2">Maps to table value column ShipAddr_Line2.</param>
        /// <param name="ShipAddr_Line3">Maps to table value column ShipAddr_Line3.</param>
        /// <param name="ShipAddr_Line4">Maps to table value column ShipAddr_Line4.</param>
        /// <param name="ShipAddr_Line5">Maps to table value column ShipAddr_Line5.</param>
        /// <param name="ShipAddr_City">Maps to table value column ShipAddr_City.</param>
        /// <param name="ShipAddr_Country">Maps to table value column ShipAddr_Country.</param>
        /// <param name="ShipAddr_CountrySubDivisionCode">Maps to table value column ShipAddr_CountrySubDivisionCode.</param>
        /// <param name="ShipAddr_PostalCode">Maps to table value column ShipAddr_PostalCode.</param>
        /// <param name="ShipAddr_Note">Maps to table value column ShipAddr_Note.</param>
        /// <param name="ShipAddr_Lat">Maps to table value column ShipAddr_Lat.</param>
        /// <param name="ShipAddr_Long">Maps to table value column ShipAddr_Long.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        /// <param name="Job">Maps to table value column Job.</param>
        /// <param name="BillWithParent">Maps to table value column BillWithParent.</param>
        /// <param name="ParentRef">Maps to table value column ParentRef.</param>
        /// <param name="ParentRef_Name">Maps to table value column ParentRef_Name.</param>
        /// <param name="Level">Maps to table value column Level.</param>
        /// <param name="SalesTermRef">Maps to table value column SalesTermRef.</param>
        /// <param name="SalesTermRef_Name">Maps to table value column SalesTermRef_Name.</param>
        /// <param name="PaymentMethodRef">Maps to table value column PaymentMethodRef.</param>
        /// <param name="PaymentMethodRef_Name">Maps to table value column PaymentMethodRef_Name.</param>
        /// <param name="Balance">Maps to table value column Balance.</param>
        /// <param name="OpenBalanceDate">Maps to table value column OpenBalanceDate.</param>
        /// <param name="BalanceWithJobs">Maps to table value column BalanceWithJobs.</param>
        /// <param name="PreferredDeliveryMethod">Maps to table value column PreferredDeliveryMethod.</param>
        /// <param name="ResaleNum">Maps to table value column ResaleNum.</param>
        /// <param name="CurrencyRef">Maps to table value column CurrencyRef.</param>
        /// <param name="CurrencyRef_Name">Maps to table value column CurrencyRef_Name.</param>
        /// <param name="TaxExemptionReasonId">Maps to table value column TaxExemptionReasonId.</param>
        public h_QBCustomersQueryResult(long Id, string? SyncToken, DateTime? MetaData_CreateTime, DateTime? MetaData_LastUpdatedTime, string? Title, string? GivenName, string? MiddleName, string? FamilyName, string? Suffix, string? FullyQualifiedName, string? CompanyName, string? DisplayName, string? PrintOnCheckName, bool? Active, bool? IsProject, string? PrimaryPhone_FreeFormNumber, string? AlternatePhone_FreeFormNumber, string? Mobile_FreeFormNumber, string? Fax_FreeFormNumber, string? PrimaryEmailAddr_Address, string? WebAddr_URI, string? DefaultTaxCodeRef, bool? Taxable, string? CustomerTypeRef, string? BillAddr_Id, string? BillAddr_Line1, string? BillAddr_Line2, string? BillAddr_Line3, string? BillAddr_Line4, string? BillAddr_Line5, string? BillAddr_City, string? BillAddr_Country, string? BillAddr_CountrySubDivisionCode, string? BillAddr_PostalCode, string? BillAddr_Lat, string? BillAddr_Long, string? ShipAddr_Id, string? ShipAddr_Line1, string? ShipAddr_Line2, string? ShipAddr_Line3, string? ShipAddr_Line4, string? ShipAddr_Line5, string? ShipAddr_City, string? ShipAddr_Country, string? ShipAddr_CountrySubDivisionCode, string? ShipAddr_PostalCode, string? ShipAddr_Note, string? ShipAddr_Lat, string? ShipAddr_Long, string? Notes, bool? Job, bool? BillWithParent, string? ParentRef, string? ParentRef_Name, int? Level, string? SalesTermRef, string? SalesTermRef_Name, string? PaymentMethodRef, string? PaymentMethodRef_Name, decimal? Balance, DateTime? OpenBalanceDate, decimal? BalanceWithJobs, string? PreferredDeliveryMethod, string? ResaleNum, string? CurrencyRef, string? CurrencyRef_Name, int? TaxExemptionReasonId)
        {
             this.Id = Id;
             this.SyncToken = SyncToken;
             this.MetaData_CreateTime = MetaData_CreateTime;
             this.MetaData_LastUpdatedTime = MetaData_LastUpdatedTime;
             this.Title = Title;
             this.GivenName = GivenName;
             this.MiddleName = MiddleName;
             this.FamilyName = FamilyName;
             this.Suffix = Suffix;
             this.FullyQualifiedName = FullyQualifiedName;
             this.CompanyName = CompanyName;
             this.DisplayName = DisplayName;
             this.PrintOnCheckName = PrintOnCheckName;
             this.Active = Active;
             this.IsProject = IsProject;
             this.PrimaryPhone_FreeFormNumber = PrimaryPhone_FreeFormNumber;
             this.AlternatePhone_FreeFormNumber = AlternatePhone_FreeFormNumber;
             this.Mobile_FreeFormNumber = Mobile_FreeFormNumber;
             this.Fax_FreeFormNumber = Fax_FreeFormNumber;
             this.PrimaryEmailAddr_Address = PrimaryEmailAddr_Address;
             this.WebAddr_URI = WebAddr_URI;
             this.DefaultTaxCodeRef = DefaultTaxCodeRef;
             this.Taxable = Taxable;
             this.CustomerTypeRef = CustomerTypeRef;
             this.BillAddr_Id = BillAddr_Id;
             this.BillAddr_Line1 = BillAddr_Line1;
             this.BillAddr_Line2 = BillAddr_Line2;
             this.BillAddr_Line3 = BillAddr_Line3;
             this.BillAddr_Line4 = BillAddr_Line4;
             this.BillAddr_Line5 = BillAddr_Line5;
             this.BillAddr_City = BillAddr_City;
             this.BillAddr_Country = BillAddr_Country;
             this.BillAddr_CountrySubDivisionCode = BillAddr_CountrySubDivisionCode;
             this.BillAddr_PostalCode = BillAddr_PostalCode;
             this.BillAddr_Lat = BillAddr_Lat;
             this.BillAddr_Long = BillAddr_Long;
             this.ShipAddr_Id = ShipAddr_Id;
             this.ShipAddr_Line1 = ShipAddr_Line1;
             this.ShipAddr_Line2 = ShipAddr_Line2;
             this.ShipAddr_Line3 = ShipAddr_Line3;
             this.ShipAddr_Line4 = ShipAddr_Line4;
             this.ShipAddr_Line5 = ShipAddr_Line5;
             this.ShipAddr_City = ShipAddr_City;
             this.ShipAddr_Country = ShipAddr_Country;
             this.ShipAddr_CountrySubDivisionCode = ShipAddr_CountrySubDivisionCode;
             this.ShipAddr_PostalCode = ShipAddr_PostalCode;
             this.ShipAddr_Note = ShipAddr_Note;
             this.ShipAddr_Lat = ShipAddr_Lat;
             this.ShipAddr_Long = ShipAddr_Long;
             this.Notes = Notes;
             this.Job = Job;
             this.BillWithParent = BillWithParent;
             this.ParentRef = ParentRef;
             this.ParentRef_Name = ParentRef_Name;
             this.Level = Level;
             this.SalesTermRef = SalesTermRef;
             this.SalesTermRef_Name = SalesTermRef_Name;
             this.PaymentMethodRef = PaymentMethodRef;
             this.PaymentMethodRef_Name = PaymentMethodRef_Name;
             this.Balance = Balance;
             this.OpenBalanceDate = OpenBalanceDate;
             this.BalanceWithJobs = BalanceWithJobs;
             this.PreferredDeliveryMethod = PreferredDeliveryMethod;
             this.ResaleNum = ResaleNum;
             this.CurrencyRef = CurrencyRef;
             this.CurrencyRef_Name = CurrencyRef_Name;
             this.TaxExemptionReasonId = TaxExemptionReasonId;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public long Id { set; get; }

        /// <summary>
        /// Maps to table value column SyncToken.
        /// </summary>
        public string? SyncToken { set; get; }

        /// <summary>
        /// Maps to table value column MetaData_CreateTime.
        /// </summary>
        public DateTime? MetaData_CreateTime { set; get; }

        /// <summary>
        /// Maps to table value column MetaData_LastUpdatedTime.
        /// </summary>
        public DateTime? MetaData_LastUpdatedTime { set; get; }

        /// <summary>
        /// Maps to table value column Title.
        /// </summary>
        public string? Title { set; get; }

        /// <summary>
        /// Maps to table value column GivenName.
        /// </summary>
        public string? GivenName { set; get; }

        /// <summary>
        /// Maps to table value column MiddleName.
        /// </summary>
        public string? MiddleName { set; get; }

        /// <summary>
        /// Maps to table value column FamilyName.
        /// </summary>
        public string? FamilyName { set; get; }

        /// <summary>
        /// Maps to table value column Suffix.
        /// </summary>
        public string? Suffix { set; get; }

        /// <summary>
        /// Maps to table value column FullyQualifiedName.
        /// </summary>
        public string? FullyQualifiedName { set; get; }

        /// <summary>
        /// Maps to table value column CompanyName.
        /// </summary>
        public string? CompanyName { set; get; }

        /// <summary>
        /// Maps to table value column DisplayName.
        /// </summary>
        public string? DisplayName { set; get; }

        /// <summary>
        /// Maps to table value column PrintOnCheckName.
        /// </summary>
        public string? PrintOnCheckName { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool? Active { set; get; }

        /// <summary>
        /// Maps to table value column IsProject.
        /// </summary>
        public bool? IsProject { set; get; }

        /// <summary>
        /// Maps to table value column PrimaryPhone_FreeFormNumber.
        /// </summary>
        public string? PrimaryPhone_FreeFormNumber { set; get; }

        /// <summary>
        /// Maps to table value column AlternatePhone_FreeFormNumber.
        /// </summary>
        public string? AlternatePhone_FreeFormNumber { set; get; }

        /// <summary>
        /// Maps to table value column Mobile_FreeFormNumber.
        /// </summary>
        public string? Mobile_FreeFormNumber { set; get; }

        /// <summary>
        /// Maps to table value column Fax_FreeFormNumber.
        /// </summary>
        public string? Fax_FreeFormNumber { set; get; }

        /// <summary>
        /// Maps to table value column PrimaryEmailAddr_Address.
        /// </summary>
        public string? PrimaryEmailAddr_Address { set; get; }

        /// <summary>
        /// Maps to table value column WebAddr_URI.
        /// </summary>
        public string? WebAddr_URI { set; get; }

        /// <summary>
        /// Maps to table value column DefaultTaxCodeRef.
        /// </summary>
        public string? DefaultTaxCodeRef { set; get; }

        /// <summary>
        /// Maps to table value column Taxable.
        /// </summary>
        public bool? Taxable { set; get; }

        /// <summary>
        /// Maps to table value column CustomerTypeRef.
        /// </summary>
        public string? CustomerTypeRef { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Id.
        /// </summary>
        public string? BillAddr_Id { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line1.
        /// </summary>
        public string? BillAddr_Line1 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line2.
        /// </summary>
        public string? BillAddr_Line2 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line3.
        /// </summary>
        public string? BillAddr_Line3 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line4.
        /// </summary>
        public string? BillAddr_Line4 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line5.
        /// </summary>
        public string? BillAddr_Line5 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_City.
        /// </summary>
        public string? BillAddr_City { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Country.
        /// </summary>
        public string? BillAddr_Country { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_CountrySubDivisionCode.
        /// </summary>
        public string? BillAddr_CountrySubDivisionCode { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_PostalCode.
        /// </summary>
        public string? BillAddr_PostalCode { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Lat.
        /// </summary>
        public string? BillAddr_Lat { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Long.
        /// </summary>
        public string? BillAddr_Long { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Id.
        /// </summary>
        public string? ShipAddr_Id { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line1.
        /// </summary>
        public string? ShipAddr_Line1 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line2.
        /// </summary>
        public string? ShipAddr_Line2 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line3.
        /// </summary>
        public string? ShipAddr_Line3 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line4.
        /// </summary>
        public string? ShipAddr_Line4 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line5.
        /// </summary>
        public string? ShipAddr_Line5 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_City.
        /// </summary>
        public string? ShipAddr_City { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Country.
        /// </summary>
        public string? ShipAddr_Country { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_CountrySubDivisionCode.
        /// </summary>
        public string? ShipAddr_CountrySubDivisionCode { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_PostalCode.
        /// </summary>
        public string? ShipAddr_PostalCode { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Note.
        /// </summary>
        public string? ShipAddr_Note { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Lat.
        /// </summary>
        public string? ShipAddr_Lat { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Long.
        /// </summary>
        public string? ShipAddr_Long { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }

        /// <summary>
        /// Maps to table value column Job.
        /// </summary>
        public bool? Job { set; get; }

        /// <summary>
        /// Maps to table value column BillWithParent.
        /// </summary>
        public bool? BillWithParent { set; get; }

        /// <summary>
        /// Maps to table value column ParentRef.
        /// </summary>
        public string? ParentRef { set; get; }

        /// <summary>
        /// Maps to table value column ParentRef_Name.
        /// </summary>
        public string? ParentRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column Level.
        /// </summary>
        public int? Level { set; get; }

        /// <summary>
        /// Maps to table value column SalesTermRef.
        /// </summary>
        public string? SalesTermRef { set; get; }

        /// <summary>
        /// Maps to table value column SalesTermRef_Name.
        /// </summary>
        public string? SalesTermRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column PaymentMethodRef.
        /// </summary>
        public string? PaymentMethodRef { set; get; }

        /// <summary>
        /// Maps to table value column PaymentMethodRef_Name.
        /// </summary>
        public string? PaymentMethodRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column Balance.
        /// </summary>
        public decimal? Balance { set; get; }

        /// <summary>
        /// Maps to table value column OpenBalanceDate.
        /// </summary>
        public DateTime? OpenBalanceDate { set; get; }

        /// <summary>
        /// Maps to table value column BalanceWithJobs.
        /// </summary>
        public decimal? BalanceWithJobs { set; get; }

        /// <summary>
        /// Maps to table value column PreferredDeliveryMethod.
        /// </summary>
        public string? PreferredDeliveryMethod { set; get; }

        /// <summary>
        /// Maps to table value column ResaleNum.
        /// </summary>
        public string? ResaleNum { set; get; }

        /// <summary>
        /// Maps to table value column CurrencyRef.
        /// </summary>
        public string? CurrencyRef { set; get; }

        /// <summary>
        /// Maps to table value column CurrencyRef_Name.
        /// </summary>
        public string? CurrencyRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column TaxExemptionReasonId.
        /// </summary>
        public int? TaxExemptionReasonId { set; get; }
    }

    #endregion Result Set Objects

}
