// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_QBBillsQuery
//     Last Modified On: 2/26/2024 5:13:38 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the h_QBBillsQuery service.
    /// </summary>
    public partial class h_QBBillsQueryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for h_QBBillsQueryInput.
        /// </summary>
        public h_QBBillsQueryInput() { }

        /// <summary>
        /// Parameterized constructor for h_QBBillsQueryInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="SyncToken">SyncToken</param>
        /// <param name="MetaData_CreateTime">MetaData_CreateTime</param>
        /// <param name="MetaData_LastUpdatedTime">MetaData_LastUpdatedTime</param>
        /// <param name="DocNumber">DocNumber</param>
        /// <param name="TxnDate">TxnDate</param>
        /// <param name="PrivateNote">PrivateNote</param>
        /// <param name="LinkedTxnAggregate">LinkedTxnAggregate</param>
        /// <param name="LineAggregate">LineAggregate</param>
        /// <param name="VendorRef">VendorRef</param>
        /// <param name="VendorRef_Name">VendorRef_Name</param>
        /// <param name="APAccountRef">APAccountRef</param>
        /// <param name="APAccountRef_Name">APAccountRef_Name</param>
        /// <param name="TotalAmt">TotalAmt</param>
        /// <param name="SalesTermRef">SalesTermRef</param>
        /// <param name="SalesTermRef_Name">SalesTermRef_Name</param>
        /// <param name="DueDate">DueDate</param>
        /// <param name="Balance">Balance</param>
        /// <param name="DepartmentRef">DepartmentRef</param>
        /// <param name="DepartmentRef_Name">DepartmentRef_Name</param>
        /// <param name="TxnTaxDetail_TxnTaxCodeRef">TxnTaxDetail_TxnTaxCodeRef</param>
        /// <param name="TxnTaxDetail_TotalTax">TxnTaxDetail_TotalTax</param>
        /// <param name="TxnTaxDetail_TaxLineAggregate">TxnTaxDetail_TaxLineAggregate</param>
        /// <param name="CurrencyRef">CurrencyRef</param>
        /// <param name="CurrencyRef_Name">CurrencyRef_Name</param>
        /// <param name="ExchangeRate">ExchangeRate</param>
        /// <param name="GlobalTaxCalculation">GlobalTaxCalculation</param>
        /// <param name="TransactionLocationType">TransactionLocationType</param>
        public h_QBBillsQueryInput(long? Id, string? SyncToken, DateTime? MetaData_CreateTime, DateTime? MetaData_LastUpdatedTime, string? DocNumber, DateTime? TxnDate, string? PrivateNote, string? LinkedTxnAggregate, string? LineAggregate, long? VendorRef, string? VendorRef_Name, string? APAccountRef, string? APAccountRef_Name, decimal? TotalAmt, string? SalesTermRef, string? SalesTermRef_Name, DateTime? DueDate, decimal? Balance, string? DepartmentRef, string? DepartmentRef_Name, string? TxnTaxDetail_TxnTaxCodeRef, string? TxnTaxDetail_TotalTax, string? TxnTaxDetail_TaxLineAggregate, string? CurrencyRef, string? CurrencyRef_Name, decimal? ExchangeRate, string? GlobalTaxCalculation, string? TransactionLocationType)
        {
            this.Id = Id;
            this.SyncToken = SyncToken;
            this.MetaData_CreateTime = MetaData_CreateTime;
            this.MetaData_LastUpdatedTime = MetaData_LastUpdatedTime;
            this.DocNumber = DocNumber;
            this.TxnDate = TxnDate;
            this.PrivateNote = PrivateNote;
            this.LinkedTxnAggregate = LinkedTxnAggregate;
            this.LineAggregate = LineAggregate;
            this.VendorRef = VendorRef;
            this.VendorRef_Name = VendorRef_Name;
            this.APAccountRef = APAccountRef;
            this.APAccountRef_Name = APAccountRef_Name;
            this.TotalAmt = TotalAmt;
            this.SalesTermRef = SalesTermRef;
            this.SalesTermRef_Name = SalesTermRef_Name;
            this.DueDate = DueDate;
            this.Balance = Balance;
            this.DepartmentRef = DepartmentRef;
            this.DepartmentRef_Name = DepartmentRef_Name;
            this.TxnTaxDetail_TxnTaxCodeRef = TxnTaxDetail_TxnTaxCodeRef;
            this.TxnTaxDetail_TotalTax = TxnTaxDetail_TotalTax;
            this.TxnTaxDetail_TaxLineAggregate = TxnTaxDetail_TaxLineAggregate;
            this.CurrencyRef = CurrencyRef;
            this.CurrencyRef_Name = CurrencyRef_Name;
            this.ExchangeRate = ExchangeRate;
            this.GlobalTaxCalculation = GlobalTaxCalculation;
            this.TransactionLocationType = TransactionLocationType;
        }

        #endregion Constructors

        #region Fields

        private long? _Id;
        /// <summary>
        /// Id
        /// </summary>
        public long? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private string? _SyncToken;
        /// <summary>
        /// SyncToken
        /// </summary>
        public string? SyncToken
        {
            get => _SyncToken;
            set => _SyncToken = value;
        }

        private DateTime? _MetaData_CreateTime;
        /// <summary>
        /// MetaData_CreateTime
        /// </summary>
        public DateTime? MetaData_CreateTime
        {
            get => _MetaData_CreateTime;
            set => _MetaData_CreateTime = value;
        }

        private DateTime? _MetaData_LastUpdatedTime;
        /// <summary>
        /// MetaData_LastUpdatedTime
        /// </summary>
        public DateTime? MetaData_LastUpdatedTime
        {
            get => _MetaData_LastUpdatedTime;
            set => _MetaData_LastUpdatedTime = value;
        }

        private string? _DocNumber;
        /// <summary>
        /// DocNumber
        /// </summary>
        public string? DocNumber
        {
            get => _DocNumber;
            set => _DocNumber = value;
        }

        private DateTime? _TxnDate;
        /// <summary>
        /// TxnDate
        /// </summary>
        public DateTime? TxnDate
        {
            get => _TxnDate;
            set => _TxnDate = value;
        }

        private string? _PrivateNote;
        /// <summary>
        /// PrivateNote
        /// </summary>
        public string? PrivateNote
        {
            get => _PrivateNote;
            set => _PrivateNote = value;
        }

        private string? _LinkedTxnAggregate;
        /// <summary>
        /// LinkedTxnAggregate
        /// </summary>
        public string? LinkedTxnAggregate
        {
            get => _LinkedTxnAggregate;
            set => _LinkedTxnAggregate = value;
        }

        private string? _LineAggregate;
        /// <summary>
        /// LineAggregate
        /// </summary>
        public string? LineAggregate
        {
            get => _LineAggregate;
            set => _LineAggregate = value;
        }

        private long? _VendorRef;
        /// <summary>
        /// VendorRef
        /// </summary>
        public long? VendorRef
        {
            get => _VendorRef;
            set => _VendorRef = value;
        }

        private string? _VendorRef_Name;
        /// <summary>
        /// VendorRef_Name
        /// </summary>
        public string? VendorRef_Name
        {
            get => _VendorRef_Name;
            set => _VendorRef_Name = value;
        }

        private string? _APAccountRef;
        /// <summary>
        /// APAccountRef
        /// </summary>
        public string? APAccountRef
        {
            get => _APAccountRef;
            set => _APAccountRef = value;
        }

        private string? _APAccountRef_Name;
        /// <summary>
        /// APAccountRef_Name
        /// </summary>
        public string? APAccountRef_Name
        {
            get => _APAccountRef_Name;
            set => _APAccountRef_Name = value;
        }

        private decimal? _TotalAmt;
        /// <summary>
        /// TotalAmt
        /// </summary>
        public decimal? TotalAmt
        {
            get => _TotalAmt;
            set => _TotalAmt = value;
        }

        private string? _SalesTermRef;
        /// <summary>
        /// SalesTermRef
        /// </summary>
        public string? SalesTermRef
        {
            get => _SalesTermRef;
            set => _SalesTermRef = value;
        }

        private string? _SalesTermRef_Name;
        /// <summary>
        /// SalesTermRef_Name
        /// </summary>
        public string? SalesTermRef_Name
        {
            get => _SalesTermRef_Name;
            set => _SalesTermRef_Name = value;
        }

        private DateTime? _DueDate;
        /// <summary>
        /// DueDate
        /// </summary>
        public DateTime? DueDate
        {
            get => _DueDate;
            set => _DueDate = value;
        }

        private decimal? _Balance;
        /// <summary>
        /// Balance
        /// </summary>
        public decimal? Balance
        {
            get => _Balance;
            set => _Balance = value;
        }

        private string? _DepartmentRef;
        /// <summary>
        /// DepartmentRef
        /// </summary>
        public string? DepartmentRef
        {
            get => _DepartmentRef;
            set => _DepartmentRef = value;
        }

        private string? _DepartmentRef_Name;
        /// <summary>
        /// DepartmentRef_Name
        /// </summary>
        public string? DepartmentRef_Name
        {
            get => _DepartmentRef_Name;
            set => _DepartmentRef_Name = value;
        }

        private string? _TxnTaxDetail_TxnTaxCodeRef;
        /// <summary>
        /// TxnTaxDetail_TxnTaxCodeRef
        /// </summary>
        public string? TxnTaxDetail_TxnTaxCodeRef
        {
            get => _TxnTaxDetail_TxnTaxCodeRef;
            set => _TxnTaxDetail_TxnTaxCodeRef = value;
        }

        private string? _TxnTaxDetail_TotalTax;
        /// <summary>
        /// TxnTaxDetail_TotalTax
        /// </summary>
        public string? TxnTaxDetail_TotalTax
        {
            get => _TxnTaxDetail_TotalTax;
            set => _TxnTaxDetail_TotalTax = value;
        }

        private string? _TxnTaxDetail_TaxLineAggregate;
        /// <summary>
        /// TxnTaxDetail_TaxLineAggregate
        /// </summary>
        public string? TxnTaxDetail_TaxLineAggregate
        {
            get => _TxnTaxDetail_TaxLineAggregate;
            set => _TxnTaxDetail_TaxLineAggregate = value;
        }

        private string? _CurrencyRef;
        /// <summary>
        /// CurrencyRef
        /// </summary>
        public string? CurrencyRef
        {
            get => _CurrencyRef;
            set => _CurrencyRef = value;
        }

        private string? _CurrencyRef_Name;
        /// <summary>
        /// CurrencyRef_Name
        /// </summary>
        public string? CurrencyRef_Name
        {
            get => _CurrencyRef_Name;
            set => _CurrencyRef_Name = value;
        }

        private decimal? _ExchangeRate;
        /// <summary>
        /// ExchangeRate
        /// </summary>
        public decimal? ExchangeRate
        {
            get => _ExchangeRate;
            set => _ExchangeRate = value;
        }

        private string? _GlobalTaxCalculation;
        /// <summary>
        /// GlobalTaxCalculation
        /// </summary>
        public string? GlobalTaxCalculation
        {
            get => _GlobalTaxCalculation;
            set => _GlobalTaxCalculation = value;
        }

        private string? _TransactionLocationType;
        /// <summary>
        /// TransactionLocationType
        /// </summary>
        public string? TransactionLocationType
        {
            get => _TransactionLocationType;
            set => _TransactionLocationType = value;
        }

        #endregion

    }
}