// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_QBCreditMemosQuery
//     Last Modified On: 2/25/2024 10:44:30 PM
//     Written By: KirkB
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for h_QBCreditMemosQuery service.
    /// </summary>
    public partial class h_QBCreditMemosQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of h_QBCreditMemosQueryResult.
        /// </summary>
        public List<h_QBCreditMemosQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for h_QBCreditMemosQuery service.
    /// </summary>


    public partial class h_QBCreditMemosQueryResult
	{
        /// <summary>
        /// Result set object for h_QBCreditMemosQuery.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="SyncToken">Maps to table value column SyncToken.</param>
        /// <param name="MetaData_CreateTime">Maps to table value column MetaData_CreateTime.</param>
        /// <param name="MetaData_LastUpdatedTime">Maps to table value column MetaData_LastUpdatedTime.</param>
        /// <param name="CustomFieldAggregate">Maps to table value column CustomFieldAggregate.</param>
        /// <param name="DocNumber">Maps to table value column DocNumber.</param>
        /// <param name="TxnDate">Maps to table value column TxnDate.</param>
        /// <param name="PrivateNote">Maps to table value column PrivateNote.</param>
        /// <param name="LineAggregate">Maps to table value column LineAggregate.</param>
        /// <param name="TxnTaxDetail_TxnTaxCodeRef">Maps to table value column TxnTaxDetail_TxnTaxCodeRef.</param>
        /// <param name="TxnTaxDetail_TotalTax">Maps to table value column TxnTaxDetail_TotalTax.</param>
        /// <param name="TxnTaxDetail_TaxLineAggregate">Maps to table value column TxnTaxDetail_TaxLineAggregate.</param>
        /// <param name="CustomerRef">Maps to table value column CustomerRef.</param>
        /// <param name="CustomerRef_Name">Maps to table value column CustomerRef_Name.</param>
        /// <param name="CustomerMemo">Maps to table value column CustomerMemo.</param>
        /// <param name="BillAddr_Id">Maps to table value column BillAddr_Id.</param>
        /// <param name="BillAddr_Line1">Maps to table value column BillAddr_Line1.</param>
        /// <param name="BillAddr_Line2">Maps to table value column BillAddr_Line2.</param>
        /// <param name="BillAddr_Line3">Maps to table value column BillAddr_Line3.</param>
        /// <param name="BillAddr_Line4">Maps to table value column BillAddr_Line4.</param>
        /// <param name="BillAddr_Line5">Maps to table value column BillAddr_Line5.</param>
        /// <param name="BillAddr_City">Maps to table value column BillAddr_City.</param>
        /// <param name="BillAddr_Country">Maps to table value column BillAddr_Country.</param>
        /// <param name="BillAddr_CountrySubDivisionCode">Maps to table value column BillAddr_CountrySubDivisionCode.</param>
        /// <param name="BillAddr_PostalCode">Maps to table value column BillAddr_PostalCode.</param>
        /// <param name="BillAddr_Note">Maps to table value column BillAddr_Note.</param>
        /// <param name="BillAddr_Lat">Maps to table value column BillAddr_Lat.</param>
        /// <param name="BillAddr_Long">Maps to table value column BillAddr_Long.</param>
        /// <param name="ShipAddr_Id">Maps to table value column ShipAddr_Id.</param>
        /// <param name="ShipAddr_Line1">Maps to table value column ShipAddr_Line1.</param>
        /// <param name="ShipAddr_Line2">Maps to table value column ShipAddr_Line2.</param>
        /// <param name="ShipAddr_Line3">Maps to table value column ShipAddr_Line3.</param>
        /// <param name="ShipAddr_Line4">Maps to table value column ShipAddr_Line4.</param>
        /// <param name="ShipAddr_Line5">Maps to table value column ShipAddr_Line5.</param>
        /// <param name="ShipAddr_City">Maps to table value column ShipAddr_City.</param>
        /// <param name="ShipAddr_Country">Maps to table value column ShipAddr_Country.</param>
        /// <param name="ShipAddr_CountrySubDivisionCode">Maps to table value column ShipAddr_CountrySubDivisionCode.</param>
        /// <param name="ShipAddr_PostalCode">Maps to table value column ShipAddr_PostalCode.</param>
        /// <param name="ShipAddr_Lat">Maps to table value column ShipAddr_Lat.</param>
        /// <param name="ShipAddr_Long">Maps to table value column ShipAddr_Long.</param>
        /// <param name="ClassRef">Maps to table value column ClassRef.</param>
        /// <param name="ClassRef_Name">Maps to table value column ClassRef_Name.</param>
        /// <param name="SalesTermRef">Maps to table value column SalesTermRef.</param>
        /// <param name="SalesTermRef_Name">Maps to table value column SalesTermRef_Name.</param>
        /// <param name="TotalAmt">Maps to table value column TotalAmt.</param>
        /// <param name="PrintStatus">Maps to table value column PrintStatus.</param>
        /// <param name="EmailStatus">Maps to table value column EmailStatus.</param>
        /// <param name="DepositToAccountRef">Maps to table value column DepositToAccountRef.</param>
        /// <param name="DepositToAccountRef_Name">Maps to table value column DepositToAccountRef_Name.</param>
        /// <param name="RemainingCredit">Maps to table value column RemainingCredit.</param>
        /// <param name="DepartmentRef">Maps to table value column DepartmentRef.</param>
        /// <param name="DepartmentRef_Name">Maps to table value column DepartmentRef_Name.</param>
        /// <param name="BillEmail_Address">Maps to table value column BillEmail_Address.</param>
        /// <param name="ApplyTaxAfterDiscount">Maps to table value column ApplyTaxAfterDiscount.</param>
        /// <param name="CurrencyRef">Maps to table value column CurrencyRef.</param>
        /// <param name="CurrencyRef_Name">Maps to table value column CurrencyRef_Name.</param>
        /// <param name="ExchangeRate">Maps to table value column ExchangeRate.</param>
        /// <param name="GlobalTaxCalculation">Maps to table value column GlobalTaxCalculation.</param>
        /// <param name="HomeTotalAmt">Maps to table value column HomeTotalAmt.</param>
        /// <param name="TransactionLocationType">Maps to table value column TransactionLocationType.</param>
        public h_QBCreditMemosQueryResult(int Id, string? SyncToken, DateTime? MetaData_CreateTime, DateTime? MetaData_LastUpdatedTime, string? CustomFieldAggregate, string? DocNumber, DateTime? TxnDate, string? PrivateNote, string? LineAggregate, string? TxnTaxDetail_TxnTaxCodeRef, string? TxnTaxDetail_TotalTax, string? TxnTaxDetail_TaxLineAggregate, long? CustomerRef, string? CustomerRef_Name, string? CustomerMemo, string? BillAddr_Id, string? BillAddr_Line1, string? BillAddr_Line2, string? BillAddr_Line3, string? BillAddr_Line4, string? BillAddr_Line5, string? BillAddr_City, string? BillAddr_Country, string? BillAddr_CountrySubDivisionCode, string? BillAddr_PostalCode, string? BillAddr_Note, string? BillAddr_Lat, string? BillAddr_Long, string? ShipAddr_Id, string? ShipAddr_Line1, string? ShipAddr_Line2, string? ShipAddr_Line3, string? ShipAddr_Line4, string? ShipAddr_Line5, string? ShipAddr_City, string? ShipAddr_Country, string? ShipAddr_CountrySubDivisionCode, string? ShipAddr_PostalCode, string? ShipAddr_Lat, string? ShipAddr_Long, string? ClassRef, string? ClassRef_Name, string? SalesTermRef, string? SalesTermRef_Name, decimal? TotalAmt, string? PrintStatus, string? EmailStatus, string? DepositToAccountRef, string? DepositToAccountRef_Name, decimal? RemainingCredit, string? DepartmentRef, string? DepartmentRef_Name, string? BillEmail_Address, bool? ApplyTaxAfterDiscount, string? CurrencyRef, string? CurrencyRef_Name, decimal? ExchangeRate, string? GlobalTaxCalculation, decimal? HomeTotalAmt, string? TransactionLocationType)
        {
             this.Id = Id;
             this.SyncToken = SyncToken;
             this.MetaData_CreateTime = MetaData_CreateTime;
             this.MetaData_LastUpdatedTime = MetaData_LastUpdatedTime;
             this.CustomFieldAggregate = CustomFieldAggregate;
             this.DocNumber = DocNumber;
             this.TxnDate = TxnDate;
             this.PrivateNote = PrivateNote;
             this.LineAggregate = LineAggregate;
             this.TxnTaxDetail_TxnTaxCodeRef = TxnTaxDetail_TxnTaxCodeRef;
             this.TxnTaxDetail_TotalTax = TxnTaxDetail_TotalTax;
             this.TxnTaxDetail_TaxLineAggregate = TxnTaxDetail_TaxLineAggregate;
             this.CustomerRef = CustomerRef;
             this.CustomerRef_Name = CustomerRef_Name;
             this.CustomerMemo = CustomerMemo;
             this.BillAddr_Id = BillAddr_Id;
             this.BillAddr_Line1 = BillAddr_Line1;
             this.BillAddr_Line2 = BillAddr_Line2;
             this.BillAddr_Line3 = BillAddr_Line3;
             this.BillAddr_Line4 = BillAddr_Line4;
             this.BillAddr_Line5 = BillAddr_Line5;
             this.BillAddr_City = BillAddr_City;
             this.BillAddr_Country = BillAddr_Country;
             this.BillAddr_CountrySubDivisionCode = BillAddr_CountrySubDivisionCode;
             this.BillAddr_PostalCode = BillAddr_PostalCode;
             this.BillAddr_Note = BillAddr_Note;
             this.BillAddr_Lat = BillAddr_Lat;
             this.BillAddr_Long = BillAddr_Long;
             this.ShipAddr_Id = ShipAddr_Id;
             this.ShipAddr_Line1 = ShipAddr_Line1;
             this.ShipAddr_Line2 = ShipAddr_Line2;
             this.ShipAddr_Line3 = ShipAddr_Line3;
             this.ShipAddr_Line4 = ShipAddr_Line4;
             this.ShipAddr_Line5 = ShipAddr_Line5;
             this.ShipAddr_City = ShipAddr_City;
             this.ShipAddr_Country = ShipAddr_Country;
             this.ShipAddr_CountrySubDivisionCode = ShipAddr_CountrySubDivisionCode;
             this.ShipAddr_PostalCode = ShipAddr_PostalCode;
             this.ShipAddr_Lat = ShipAddr_Lat;
             this.ShipAddr_Long = ShipAddr_Long;
             this.ClassRef = ClassRef;
             this.ClassRef_Name = ClassRef_Name;
             this.SalesTermRef = SalesTermRef;
             this.SalesTermRef_Name = SalesTermRef_Name;
             this.TotalAmt = TotalAmt;
             this.PrintStatus = PrintStatus;
             this.EmailStatus = EmailStatus;
             this.DepositToAccountRef = DepositToAccountRef;
             this.DepositToAccountRef_Name = DepositToAccountRef_Name;
             this.RemainingCredit = RemainingCredit;
             this.DepartmentRef = DepartmentRef;
             this.DepartmentRef_Name = DepartmentRef_Name;
             this.BillEmail_Address = BillEmail_Address;
             this.ApplyTaxAfterDiscount = ApplyTaxAfterDiscount;
             this.CurrencyRef = CurrencyRef;
             this.CurrencyRef_Name = CurrencyRef_Name;
             this.ExchangeRate = ExchangeRate;
             this.GlobalTaxCalculation = GlobalTaxCalculation;
             this.HomeTotalAmt = HomeTotalAmt;
             this.TransactionLocationType = TransactionLocationType;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column SyncToken.
        /// </summary>
        public string? SyncToken { set; get; }

        /// <summary>
        /// Maps to table value column MetaData_CreateTime.
        /// </summary>
        public DateTime? MetaData_CreateTime { set; get; }

        /// <summary>
        /// Maps to table value column MetaData_LastUpdatedTime.
        /// </summary>
        public DateTime? MetaData_LastUpdatedTime { set; get; }

        /// <summary>
        /// Maps to table value column CustomFieldAggregate.
        /// </summary>
        public string? CustomFieldAggregate { set; get; }

        /// <summary>
        /// Maps to table value column DocNumber.
        /// </summary>
        public string? DocNumber { set; get; }

        /// <summary>
        /// Maps to table value column TxnDate.
        /// </summary>
        public DateTime? TxnDate { set; get; }

        /// <summary>
        /// Maps to table value column PrivateNote.
        /// </summary>
        public string? PrivateNote { set; get; }

        /// <summary>
        /// Maps to table value column LineAggregate.
        /// </summary>
        public string? LineAggregate { set; get; }

        /// <summary>
        /// Maps to table value column TxnTaxDetail_TxnTaxCodeRef.
        /// </summary>
        public string? TxnTaxDetail_TxnTaxCodeRef { set; get; }

        /// <summary>
        /// Maps to table value column TxnTaxDetail_TotalTax.
        /// </summary>
        public string? TxnTaxDetail_TotalTax { set; get; }

        /// <summary>
        /// Maps to table value column TxnTaxDetail_TaxLineAggregate.
        /// </summary>
        public string? TxnTaxDetail_TaxLineAggregate { set; get; }

        /// <summary>
        /// Maps to table value column CustomerRef.
        /// </summary>
        public long? CustomerRef { set; get; }

        /// <summary>
        /// Maps to table value column CustomerRef_Name.
        /// </summary>
        public string? CustomerRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column CustomerMemo.
        /// </summary>
        public string? CustomerMemo { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Id.
        /// </summary>
        public string? BillAddr_Id { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line1.
        /// </summary>
        public string? BillAddr_Line1 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line2.
        /// </summary>
        public string? BillAddr_Line2 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line3.
        /// </summary>
        public string? BillAddr_Line3 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line4.
        /// </summary>
        public string? BillAddr_Line4 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Line5.
        /// </summary>
        public string? BillAddr_Line5 { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_City.
        /// </summary>
        public string? BillAddr_City { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Country.
        /// </summary>
        public string? BillAddr_Country { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_CountrySubDivisionCode.
        /// </summary>
        public string? BillAddr_CountrySubDivisionCode { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_PostalCode.
        /// </summary>
        public string? BillAddr_PostalCode { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Note.
        /// </summary>
        public string? BillAddr_Note { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Lat.
        /// </summary>
        public string? BillAddr_Lat { set; get; }

        /// <summary>
        /// Maps to table value column BillAddr_Long.
        /// </summary>
        public string? BillAddr_Long { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Id.
        /// </summary>
        public string? ShipAddr_Id { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line1.
        /// </summary>
        public string? ShipAddr_Line1 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line2.
        /// </summary>
        public string? ShipAddr_Line2 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line3.
        /// </summary>
        public string? ShipAddr_Line3 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line4.
        /// </summary>
        public string? ShipAddr_Line4 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Line5.
        /// </summary>
        public string? ShipAddr_Line5 { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_City.
        /// </summary>
        public string? ShipAddr_City { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Country.
        /// </summary>
        public string? ShipAddr_Country { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_CountrySubDivisionCode.
        /// </summary>
        public string? ShipAddr_CountrySubDivisionCode { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_PostalCode.
        /// </summary>
        public string? ShipAddr_PostalCode { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Lat.
        /// </summary>
        public string? ShipAddr_Lat { set; get; }

        /// <summary>
        /// Maps to table value column ShipAddr_Long.
        /// </summary>
        public string? ShipAddr_Long { set; get; }

        /// <summary>
        /// Maps to table value column ClassRef.
        /// </summary>
        public string? ClassRef { set; get; }

        /// <summary>
        /// Maps to table value column ClassRef_Name.
        /// </summary>
        public string? ClassRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column SalesTermRef.
        /// </summary>
        public string? SalesTermRef { set; get; }

        /// <summary>
        /// Maps to table value column SalesTermRef_Name.
        /// </summary>
        public string? SalesTermRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column TotalAmt.
        /// </summary>
        public decimal? TotalAmt { set; get; }

        /// <summary>
        /// Maps to table value column PrintStatus.
        /// </summary>
        public string? PrintStatus { set; get; }

        /// <summary>
        /// Maps to table value column EmailStatus.
        /// </summary>
        public string? EmailStatus { set; get; }

        /// <summary>
        /// Maps to table value column DepositToAccountRef.
        /// </summary>
        public string? DepositToAccountRef { set; get; }

        /// <summary>
        /// Maps to table value column DepositToAccountRef_Name.
        /// </summary>
        public string? DepositToAccountRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column RemainingCredit.
        /// </summary>
        public decimal? RemainingCredit { set; get; }

        /// <summary>
        /// Maps to table value column DepartmentRef.
        /// </summary>
        public string? DepartmentRef { set; get; }

        /// <summary>
        /// Maps to table value column DepartmentRef_Name.
        /// </summary>
        public string? DepartmentRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column BillEmail_Address.
        /// </summary>
        public string? BillEmail_Address { set; get; }

        /// <summary>
        /// Maps to table value column ApplyTaxAfterDiscount.
        /// </summary>
        public bool? ApplyTaxAfterDiscount { set; get; }

        /// <summary>
        /// Maps to table value column CurrencyRef.
        /// </summary>
        public string? CurrencyRef { set; get; }

        /// <summary>
        /// Maps to table value column CurrencyRef_Name.
        /// </summary>
        public string? CurrencyRef_Name { set; get; }

        /// <summary>
        /// Maps to table value column ExchangeRate.
        /// </summary>
        public decimal? ExchangeRate { set; get; }

        /// <summary>
        /// Maps to table value column GlobalTaxCalculation.
        /// </summary>
        public string? GlobalTaxCalculation { set; get; }

        /// <summary>
        /// Maps to table value column HomeTotalAmt.
        /// </summary>
        public decimal? HomeTotalAmt { set; get; }

        /// <summary>
        /// Maps to table value column TransactionLocationType.
        /// </summary>
        public string? TransactionLocationType { set; get; }
    }

    #endregion Result Set Objects

}
