// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ICSInventoryGroupList
//     Last Modified On: 9/18/2024 1:13:38 AM
//     Written By: kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for ICSInventoryGroupList service.
    /// </summary>
    public partial class ICSInventoryGroupListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of ICSInventoryGroupListResult.
        /// </summary>
        public List<ICSInventoryGroupListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for ICSInventoryGroupList service.
    /// </summary>


    public partial class ICSInventoryGroupListResult
	{
        /// <summary>
        /// Result set object for ICSInventoryGroupList.
        /// </summary>
        /// <param name="GroupName">Maps to table value column GroupName.</param>
        /// <param name="MapToAttribute">Maps to table value column MapToAttribute.</param>
        /// <param name="Enabled">Maps to table value column Enabled.</param>
        public ICSInventoryGroupListResult(string GroupName, int MapToAttribute, bool Enabled)
        {
             this.GroupName = GroupName;
             this.MapToAttribute = MapToAttribute;
             this.Enabled = Enabled;
        }


        /// <summary>
        /// Maps to table value column GroupName.
        /// </summary>
        public string GroupName { set; get; }

        /// <summary>
        /// Maps to table value column MapToAttribute.
        /// </summary>
        public int MapToAttribute { set; get; }

        /// <summary>
        /// Maps to table value column Enabled.
        /// </summary>
        public bool Enabled { set; get; }
    }

    #endregion Result Set Objects

}
