// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: JobCodesById
//     Last Modified On: 8/20/2025 5:46:46 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the JobCodesById service.
    /// </summary>
    public partial class JobCodesByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for JobCodesByIdInput.
        /// </summary>
        public JobCodesByIdInput() { }

        /// <summary>
        /// Parameterized constructor for JobCodesByIdInput.
        /// </summary>
        /// <param name="JobCodeId">JobCodeId</param>
        public JobCodesByIdInput(int? JobCodeId)
        {
            this.JobCodeId = JobCodeId;
        }

        #endregion Constructors

        #region Fields

        private int? _JobCodeId;
        /// <summary>
        /// JobCodeId
        /// </summary>
        [Required]
        public int? JobCodeId
        {
            get => _JobCodeId;
            set => _JobCodeId = value;
        }

        #endregion

    }
}