// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: LocationLookup
//     Last Modified On: 9/29/2023 12:02:31 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for LocationLookup service.
    /// </summary>
    public partial class LocationLookupOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of LocationLookupResult.
        /// </summary>
        public List<LocationLookupResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for LocationLookup service.
    /// </summary>


    public partial class LocationLookupResult
	{
        /// <summary>
        /// Result set object for LocationLookup.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="CustomerId">Maps to table value column CustomerId.</param>
        /// <param name="DivisionId">Maps to table value column DivisionId.</param>
        /// <param name="LocName">Maps to table value column LocName.</param>
        /// <param name="ContactName">Maps to table value column ContactName.</param>
        /// <param name="ContactInfo">Maps to table value column ContactInfo.</param>
        /// <param name="AddressLine">Maps to table value column AddressLine.</param>
        /// <param name="Locality">Maps to table value column Locality.</param>
        /// <param name="AdminDistrict">Maps to table value column AdminDistrict.</param>
        /// <param name="AdminDistrict2">Maps to table value column AdminDistrict2.</param>
        /// <param name="CountryRegion">Maps to table value column CountryRegion.</param>
        /// <param name="FormattedAddress">Maps to table value column FormattedAddress.</param>
        /// <param name="Landmark">Maps to table value column Landmark.</param>
        /// <param name="Latitude">Maps to table value column Latitude.</param>
        /// <param name="Longitude">Maps to table value column Longitude.</param>
        /// <param name="Neighborhood">Maps to table value column Neighborhood.</param>
        /// <param name="PostalCode">Maps to table value column PostalCode.</param>
        /// <param name="PostalCodeFour">Maps to table value column PostalCodeFour.</param>
        /// <param name="FIPS">Maps to table value column FIPS.</param>
        /// <param name="TaxCode">Maps to table value column TaxCode.</param>
        /// <param name="LaborRate">Maps to table value column LaborRate.</param>
        /// <param name="HelperRate">Maps to table value column HelperRate.</param>
        /// <param name="Zone">Maps to table value column Zone.</param>
        /// <param name="TripCharge">Maps to table value column TripCharge.</param>
        /// <param name="TaxFRP">Maps to table value column TaxFRP.</param>
        /// <param name="SalesRef">Maps to table value column SalesRef.</param>
        /// <param name="LocationInactive">Maps to table value column LocationInactive.</param>
        /// <param name="SalespersonId">Maps to table value column SalespersonId.</param>
        /// <param name="TimezoneId">Maps to table value column TimezoneId.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        public LocationLookupResult(int Id, int CustomerId, int DivisionId, string LocName, string? ContactName, string? ContactInfo, string AddressLine, string Locality, string AdminDistrict, string AdminDistrict2, string CountryRegion, string FormattedAddress, string? Landmark, decimal Latitude, decimal Longitude, string Neighborhood, string PostalCode, string? PostalCodeFour, string FIPS, string TaxCode, double LaborRate, double HelperRate, string Zone, double TripCharge, int TaxFRP, string SalesRef, short LocationInactive, int SalespersonId, string TimezoneId, string? Notes)
        {
             this.Id = Id;
             this.CustomerId = CustomerId;
             this.DivisionId = DivisionId;
             this.LocName = LocName;
             this.ContactName = ContactName;
             this.ContactInfo = ContactInfo;
             this.AddressLine = AddressLine;
             this.Locality = Locality;
             this.AdminDistrict = AdminDistrict;
             this.AdminDistrict2 = AdminDistrict2;
             this.CountryRegion = CountryRegion;
             this.FormattedAddress = FormattedAddress;
             this.Landmark = Landmark;
             this.Latitude = Latitude;
             this.Longitude = Longitude;
             this.Neighborhood = Neighborhood;
             this.PostalCode = PostalCode;
             this.PostalCodeFour = PostalCodeFour;
             this.FIPS = FIPS;
             this.TaxCode = TaxCode;
             this.LaborRate = LaborRate;
             this.HelperRate = HelperRate;
             this.Zone = Zone;
             this.TripCharge = TripCharge;
             this.TaxFRP = TaxFRP;
             this.SalesRef = SalesRef;
             this.LocationInactive = LocationInactive;
             this.SalespersonId = SalespersonId;
             this.TimezoneId = TimezoneId;
             this.Notes = Notes;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column CustomerId.
        /// </summary>
        public int CustomerId { set; get; }

        /// <summary>
        /// Maps to table value column DivisionId.
        /// </summary>
        public int DivisionId { set; get; }

        /// <summary>
        /// Maps to table value column LocName.
        /// </summary>
        public string LocName { set; get; }

        /// <summary>
        /// Maps to table value column ContactName.
        /// </summary>
        public string? ContactName { set; get; }

        /// <summary>
        /// Maps to table value column ContactInfo.
        /// </summary>
        public string? ContactInfo { set; get; }

        /// <summary>
        /// Maps to table value column AddressLine.
        /// </summary>
        public string AddressLine { set; get; }

        /// <summary>
        /// Maps to table value column Locality.
        /// </summary>
        public string Locality { set; get; }

        /// <summary>
        /// Maps to table value column AdminDistrict.
        /// </summary>
        public string AdminDistrict { set; get; }

        /// <summary>
        /// Maps to table value column AdminDistrict2.
        /// </summary>
        public string AdminDistrict2 { set; get; }

        /// <summary>
        /// Maps to table value column CountryRegion.
        /// </summary>
        public string CountryRegion { set; get; }

        /// <summary>
        /// Maps to table value column FormattedAddress.
        /// </summary>
        public string FormattedAddress { set; get; }

        /// <summary>
        /// Maps to table value column Landmark.
        /// </summary>
        public string? Landmark { set; get; }

        /// <summary>
        /// Maps to table value column Latitude.
        /// </summary>
        public decimal Latitude { set; get; }

        /// <summary>
        /// Maps to table value column Longitude.
        /// </summary>
        public decimal Longitude { set; get; }

        /// <summary>
        /// Maps to table value column Neighborhood.
        /// </summary>
        public string Neighborhood { set; get; }

        /// <summary>
        /// Maps to table value column PostalCode.
        /// </summary>
        public string PostalCode { set; get; }

        /// <summary>
        /// Maps to table value column PostalCodeFour.
        /// </summary>
        public string? PostalCodeFour { set; get; }

        /// <summary>
        /// Maps to table value column FIPS.
        /// </summary>
        public string FIPS { set; get; }

        /// <summary>
        /// Maps to table value column TaxCode.
        /// </summary>
        public string TaxCode { set; get; }

        /// <summary>
        /// Maps to table value column LaborRate.
        /// </summary>
        public double LaborRate { set; get; }

        /// <summary>
        /// Maps to table value column HelperRate.
        /// </summary>
        public double HelperRate { set; get; }

        /// <summary>
        /// Maps to table value column Zone.
        /// </summary>
        public string Zone { set; get; }

        /// <summary>
        /// Maps to table value column TripCharge.
        /// </summary>
        public double TripCharge { set; get; }

        /// <summary>
        /// Maps to table value column TaxFRP.
        /// </summary>
        public int TaxFRP { set; get; }

        /// <summary>
        /// Maps to table value column SalesRef.
        /// </summary>
        public string SalesRef { set; get; }

        /// <summary>
        /// Maps to table value column LocationInactive.
        /// </summary>
        public short LocationInactive { set; get; }

        /// <summary>
        /// Maps to table value column SalespersonId.
        /// </summary>
        public int SalespersonId { set; get; }

        /// <summary>
        /// Maps to table value column TimezoneId.
        /// </summary>
        public string TimezoneId { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }
    }

    #endregion Result Set Objects

}
