// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: OnCallTypeQuery
//     Last Modified On: 3/27/2025 6:09:09 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for OnCallTypeQuery service.
    /// </summary>
    public partial class OnCallTypeQueryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of OnCallTypeQueryResult.
        /// </summary>
        public List<OnCallTypeQueryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for OnCallTypeQuery service.
    /// </summary>


    public partial class OnCallTypeQueryResult
	{
        /// <summary>
        /// Result set object for OnCallTypeQuery.
        /// </summary>
        /// <param name="OnCallTypeId">Maps to table value column OnCallTypeId.</param>
        /// <param name="OnCall">Maps to table value column OnCall.</param>
        /// <param name="Enabled">Maps to table value column Enabled.</param>
        public OnCallTypeQueryResult(int OnCallTypeId, string OnCall, bool Enabled)
        {
             this.OnCallTypeId = OnCallTypeId;
             this.OnCall = OnCall;
             this.Enabled = Enabled;
        }


        /// <summary>
        /// Maps to table value column OnCallTypeId.
        /// </summary>
        public int OnCallTypeId { set; get; }

        /// <summary>
        /// Maps to table value column OnCall.
        /// </summary>
        public string OnCall { set; get; }

        /// <summary>
        /// Maps to table value column Enabled.
        /// </summary>
        public bool Enabled { set; get; }
    }

    #endregion Result Set Objects

}
