// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TechNewsList
//     Last Modified On: 12/4/2024 5:27:41 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the TechNewsList service.
    /// </summary>
    public partial class TechNewsListInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for TechNewsListInput.
        /// </summary>
        public TechNewsListInput() { }

        /// <summary>
        /// Parameterized constructor for TechNewsListInput.
        /// </summary>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        /// <param name="Archived">Maps to parameter @Archived.</param>
        public TechNewsListInput(int? EmployeeId, bool? Archived)
        {
            this.EmployeeId = EmployeeId;
            this.Archived = Archived;
        }

        #endregion Constructors

        #region Fields

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private bool? _Archived;
        /// <summary>
        /// Maps to parameter @Archived.
        /// </summary>
        public bool? Archived
        {
            get => _Archived;
            set => _Archived = value;
        }

        #endregion

    }
}