// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: Timeclock
//     Last Modified On: 11/14/2025 4:51:41 PM
//     Written By: Kirk
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for Timeclock service.
    /// </summary>
    public partial class TimeclockOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of TimeclockResult.
        /// </summary>
        public List<TimeclockResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for Timeclock service.
    /// </summary>


    public partial class TimeclockResult
	{
        /// <summary>
        /// Result set object for Timeclock.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="EventDate">Maps to table value column EventDate.</param>
        /// <param name="WeekNum">Maps to table value column WeekNum.</param>
        /// <param name="EmployeeId">Maps to table value column EmployeeId.</param>
        /// <param name="EmpNo">Maps to table value column EmpNo.</param>
        /// <param name="EmpName">Maps to table value column EmpName.</param>
        /// <param name="EmployeeName">Maps to table value column EmployeeName.</param>
        /// <param name="Zone">Maps to table value column Zone.</param>
        /// <param name="AzugaFirst">Maps to table value column AzugaFirst.</param>
        /// <param name="AzugaLast">Maps to table value column AzugaLast.</param>
        /// <param name="AzugaFirstAddress">Maps to table value column AzugaFirstAddress.</param>
        /// <param name="AzugaLastAddress">Maps to table value column AzugaLastAddress.</param>
        /// <param name="AzugaFirstSpeed">Maps to table value column AzugaFirstSpeed.</param>
        /// <param name="AzugaLastSpeed">Maps to table value column AzugaLastSpeed.</param>
        /// <param name="AzugaFirstLatLng">Maps to table value column AzugaFirstLatLng.</param>
        /// <param name="AzugaLastLatLng">Maps to table value column AzugaLastLatLng.</param>
        /// <param name="AzugaFirstEventNameKeyValue">Maps to table value column AzugaFirstEventNameKeyValue.</param>
        /// <param name="AzugaLastEventNameKeyValue">Maps to table value column AzugaLastEventNameKeyValue.</param>
        /// <param name="StartOfDay">Maps to table value column StartOfDay.</param>
        /// <param name="EndOfDay">Maps to table value column EndOfDay.</param>
        /// <param name="StartOfDayLatLng">Maps to table value column StartOfDayLatLng.</param>
        /// <param name="EndOfDayLatLng">Maps to table value column EndOfDayLatLng.</param>
        /// <param name="Take5">Maps to table value column Take5.</param>
        /// <param name="Take5DayLatLng">Maps to table value column Take5DayLatLng.</param>
        /// <param name="Resume5">Maps to table value column Resume5.</param>
        /// <param name="Resume5DayLatLng">Maps to table value column Resume5DayLatLng.</param>
        /// <param name="ESCFirstDisp">Maps to table value column ESCFirstDisp.</param>
        /// <param name="ESCFirstWork">Maps to table value column ESCFirstWork.</param>
        /// <param name="ESCLastTimeOff">Maps to table value column ESCLastTimeOff.</param>
        /// <param name="ESCTravelMins">Maps to table value column ESCTravelMins.</param>
        /// <param name="ESCWorkMins">Maps to table value column ESCWorkMins.</param>
        /// <param name="ESCTotalMins">Maps to table value column ESCTotalMins.</param>
        /// <param name="CompileDate">Maps to table value column CompileDate.</param>
        /// <param name="Hash">Maps to table value column Hash.</param>
        /// <param name="IsExpanded">Maps to table value column IsExpanded.</param>
        public TimeclockResult(int Id, DateTime EventDate, int WeekNum, int EmployeeId, string? EmpNo, string? EmpName, string? EmployeeName, string? Zone, DateTime? AzugaFirst, DateTime? AzugaLast, string? AzugaFirstAddress, string? AzugaLastAddress, int AzugaFirstSpeed, int AzugaLastSpeed, string? AzugaFirstLatLng, string? AzugaLastLatLng, string? AzugaFirstEventNameKeyValue, string? AzugaLastEventNameKeyValue, DateTime? StartOfDay, DateTime? EndOfDay, string? StartOfDayLatLng, string? EndOfDayLatLng, DateTime? Take5, string? Take5DayLatLng, DateTime? Resume5, string? Resume5DayLatLng, DateTime? ESCFirstDisp, DateTime? ESCFirstWork, DateTime? ESCLastTimeOff, decimal? ESCTravelMins, decimal? ESCWorkMins, decimal? ESCTotalMins, DateTime CompileDate, int Hash, bool? IsExpanded)
        {
             this.Id = Id;
             this.EventDate = EventDate;
             this.WeekNum = WeekNum;
             this.EmployeeId = EmployeeId;
             this.EmpNo = EmpNo;
             this.EmpName = EmpName;
             this.EmployeeName = EmployeeName;
             this.Zone = Zone;
             this.AzugaFirst = AzugaFirst;
             this.AzugaLast = AzugaLast;
             this.AzugaFirstAddress = AzugaFirstAddress;
             this.AzugaLastAddress = AzugaLastAddress;
             this.AzugaFirstSpeed = AzugaFirstSpeed;
             this.AzugaLastSpeed = AzugaLastSpeed;
             this.AzugaFirstLatLng = AzugaFirstLatLng;
             this.AzugaLastLatLng = AzugaLastLatLng;
             this.AzugaFirstEventNameKeyValue = AzugaFirstEventNameKeyValue;
             this.AzugaLastEventNameKeyValue = AzugaLastEventNameKeyValue;
             this.StartOfDay = StartOfDay;
             this.EndOfDay = EndOfDay;
             this.StartOfDayLatLng = StartOfDayLatLng;
             this.EndOfDayLatLng = EndOfDayLatLng;
             this.Take5 = Take5;
             this.Take5DayLatLng = Take5DayLatLng;
             this.Resume5 = Resume5;
             this.Resume5DayLatLng = Resume5DayLatLng;
             this.ESCFirstDisp = ESCFirstDisp;
             this.ESCFirstWork = ESCFirstWork;
             this.ESCLastTimeOff = ESCLastTimeOff;
             this.ESCTravelMins = ESCTravelMins;
             this.ESCWorkMins = ESCWorkMins;
             this.ESCTotalMins = ESCTotalMins;
             this.CompileDate = CompileDate;
             this.Hash = Hash;
             this.IsExpanded = IsExpanded;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column EventDate.
        /// </summary>
        public DateTime EventDate { set; get; }

        /// <summary>
        /// Maps to table value column WeekNum.
        /// </summary>
        public int WeekNum { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeId.
        /// </summary>
        public int EmployeeId { set; get; }

        /// <summary>
        /// Maps to table value column EmpNo.
        /// </summary>
        public string? EmpNo { set; get; }

        /// <summary>
        /// Maps to table value column EmpName.
        /// </summary>
        public string? EmpName { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeName.
        /// </summary>
        public string? EmployeeName { set; get; }

        /// <summary>
        /// Maps to table value column Zone.
        /// </summary>
        public string? Zone { set; get; }

        /// <summary>
        /// Maps to table value column AzugaFirst.
        /// </summary>
        public DateTime? AzugaFirst { set; get; }

        /// <summary>
        /// Maps to table value column AzugaLast.
        /// </summary>
        public DateTime? AzugaLast { set; get; }

        /// <summary>
        /// Maps to table value column AzugaFirstAddress.
        /// </summary>
        public string? AzugaFirstAddress { set; get; }

        /// <summary>
        /// Maps to table value column AzugaLastAddress.
        /// </summary>
        public string? AzugaLastAddress { set; get; }

        /// <summary>
        /// Maps to table value column AzugaFirstSpeed.
        /// </summary>
        public int AzugaFirstSpeed { set; get; }

        /// <summary>
        /// Maps to table value column AzugaLastSpeed.
        /// </summary>
        public int AzugaLastSpeed { set; get; }

        /// <summary>
        /// Maps to table value column AzugaFirstLatLng.
        /// </summary>
        public string? AzugaFirstLatLng { set; get; }

        /// <summary>
        /// Maps to table value column AzugaLastLatLng.
        /// </summary>
        public string? AzugaLastLatLng { set; get; }

        /// <summary>
        /// Maps to table value column AzugaFirstEventNameKeyValue.
        /// </summary>
        public string? AzugaFirstEventNameKeyValue { set; get; }

        /// <summary>
        /// Maps to table value column AzugaLastEventNameKeyValue.
        /// </summary>
        public string? AzugaLastEventNameKeyValue { set; get; }

        /// <summary>
        /// Maps to table value column StartOfDay.
        /// </summary>
        public DateTime? StartOfDay { set; get; }

        /// <summary>
        /// Maps to table value column EndOfDay.
        /// </summary>
        public DateTime? EndOfDay { set; get; }

        /// <summary>
        /// Maps to table value column StartOfDayLatLng.
        /// </summary>
        public string? StartOfDayLatLng { set; get; }

        /// <summary>
        /// Maps to table value column EndOfDayLatLng.
        /// </summary>
        public string? EndOfDayLatLng { set; get; }

        /// <summary>
        /// Maps to table value column Take5.
        /// </summary>
        public DateTime? Take5 { set; get; }

        /// <summary>
        /// Maps to table value column Take5DayLatLng.
        /// </summary>
        public string? Take5DayLatLng { set; get; }

        /// <summary>
        /// Maps to table value column Resume5.
        /// </summary>
        public DateTime? Resume5 { set; get; }

        /// <summary>
        /// Maps to table value column Resume5DayLatLng.
        /// </summary>
        public string? Resume5DayLatLng { set; get; }

        /// <summary>
        /// Maps to table value column ESCFirstDisp.
        /// </summary>
        public DateTime? ESCFirstDisp { set; get; }

        /// <summary>
        /// Maps to table value column ESCFirstWork.
        /// </summary>
        public DateTime? ESCFirstWork { set; get; }

        /// <summary>
        /// Maps to table value column ESCLastTimeOff.
        /// </summary>
        public DateTime? ESCLastTimeOff { set; get; }

        /// <summary>
        /// Maps to table value column ESCTravelMins.
        /// </summary>
        public decimal? ESCTravelMins { set; get; }

        /// <summary>
        /// Maps to table value column ESCWorkMins.
        /// </summary>
        public decimal? ESCWorkMins { set; get; }

        /// <summary>
        /// Maps to table value column ESCTotalMins.
        /// </summary>
        public decimal? ESCTotalMins { set; get; }

        /// <summary>
        /// Maps to table value column CompileDate.
        /// </summary>
        public DateTime CompileDate { set; get; }

        /// <summary>
        /// Maps to table value column Hash.
        /// </summary>
        public int Hash { set; get; }

        /// <summary>
        /// Maps to table value column IsExpanded.
        /// </summary>
        public bool? IsExpanded { set; get; }
    }

    #endregion Result Set Objects

}
