// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TimeclockDetails
//     Last Modified On: 11/19/2024 9:27:07 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the TimeclockDetails service.
    /// </summary>
    public partial class TimeclockDetailsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for TimeclockDetailsInput.
        /// </summary>
        public TimeclockDetailsInput() { }

        /// <summary>
        /// Parameterized constructor for TimeclockDetailsInput.
        /// </summary>
        /// <param name="Hash">Maps to parameter @Hash.</param>
        /// <param name="WeekNum">Maps to parameter @WeekNum.</param>
        /// <param name="EventDate">Maps to parameter @EventDate.</param>
        /// <param name="Dispatch">Maps to parameter @Dispatch.</param>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        /// <param name="Zone">Maps to parameter @Zone.</param>
        public TimeclockDetailsInput(int? Hash, int? WeekNum, DateTime? EventDate, string? Dispatch, int? EmployeeId, string? Zone)
        {
            this.Hash = Hash;
            this.WeekNum = WeekNum;
            this.EventDate = EventDate;
            this.Dispatch = Dispatch;
            this.EmployeeId = EmployeeId;
            this.Zone = Zone;
        }

        #endregion Constructors

        #region Fields

        private int? _Hash;
        /// <summary>
        /// Maps to parameter @Hash.
        /// </summary>
        public int? Hash
        {
            get => _Hash;
            set => _Hash = value;
        }

        private int? _WeekNum;
        /// <summary>
        /// Maps to parameter @WeekNum.
        /// </summary>
        public int? WeekNum
        {
            get => _WeekNum;
            set => _WeekNum = value;
        }

        private DateTime? _EventDate;
        /// <summary>
        /// Maps to parameter @EventDate.
        /// </summary>
        public DateTime? EventDate
        {
            get => _EventDate;
            set => _EventDate = value;
        }

        private string? _Dispatch;
        /// <summary>
        /// Maps to parameter @Dispatch.
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private string? _Zone;
        /// <summary>
        /// Maps to parameter @Zone.
        /// </summary>
        public string? Zone
        {
            get => _Zone;
            set => _Zone = value;
        }

        #endregion

    }
}