// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TimeclockHistory
//     Last Modified On: 12/9/2024 9:47:06 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the TimeclockHistory service.
    /// </summary>
    public partial class TimeclockHistoryInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for TimeclockHistoryInput.
        /// </summary>
        public TimeclockHistoryInput() { }

        /// <summary>
        /// Parameterized constructor for TimeclockHistoryInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="Hash">Maps to parameter @Hash.</param>
        /// <param name="Dispatch">Maps to parameter @Dispatch.</param>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        public TimeclockHistoryInput(int? Id, int? Hash, string? Dispatch, int? EmployeeId)
        {
            this.Id = Id;
            this.Hash = Hash;
            this.Dispatch = Dispatch;
            this.EmployeeId = EmployeeId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _Hash;
        /// <summary>
        /// Maps to parameter @Hash.
        /// </summary>
        public int? Hash
        {
            get => _Hash;
            set => _Hash = value;
        }

        private string? _Dispatch;
        /// <summary>
        /// Maps to parameter @Dispatch.
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        #endregion

    }
}