// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TimeclockHistory
//     Last Modified On: 12/9/2024 9:47:06 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for TimeclockHistory service.
    /// </summary>
    public partial class TimeclockHistoryOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of TimeclockHistoryResult.
        /// </summary>
        public List<TimeclockHistoryResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for TimeclockHistory service.
    /// </summary>


    public partial class TimeclockHistoryResult
	{
        /// <summary>
        /// Result set object for TimeclockHistory.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="EventDate">Maps to table value column EventDate.</param>
        /// <param name="Hash">Maps to table value column Hash.</param>
        /// <param name="EmployeeId">Maps to table value column EmployeeId.</param>
        /// <param name="EmpName">Maps to table value column EmpName.</param>
        /// <param name="EmployeeName">Maps to table value column EmployeeName.</param>
        /// <param name="Dispatch">Maps to table value column Dispatch.</param>
        /// <param name="UpdatedOn">Maps to table value column UpdatedOn.</param>
        /// <param name="ReleaseNotes">Maps to table value column ReleaseNotes.</param>
        /// <param name="ReleaseBy">Maps to table value column ReleaseBy.</param>
        /// <param name="ReleaseStatus">Maps to table value column ReleaseStatus.</param>
        /// <param name="ApprovalNotes">Maps to table value column ApprovalNotes.</param>
        /// <param name="ApprovalBy">Maps to table value column ApprovalBy.</param>
        /// <param name="ApprovalStatus">Maps to table value column ApprovalStatus.</param>
        /// <param name="LockNotes">Maps to table value column LockNotes.</param>
        /// <param name="LockedBy">Maps to table value column LockedBy.</param>
        /// <param name="LockStatus">Maps to table value column LockStatus.</param>
        /// <param name="ContactInfo">Maps to table value column ContactInfo.</param>
        public TimeclockHistoryResult(int Id, DateTime? EventDate, int Hash, int EmployeeId, string EmpName, string EmployeeName, string? Dispatch, DateTime UpdatedOn, string? ReleaseNotes, int ReleaseBy, int ReleaseStatus, string? ApprovalNotes, int ApprovalBy, int ApprovalStatus, string? LockNotes, int LockedBy, int LockStatus, string? ContactInfo)
        {
             this.Id = Id;
             this.EventDate = EventDate;
             this.Hash = Hash;
             this.EmployeeId = EmployeeId;
             this.EmpName = EmpName;
             this.EmployeeName = EmployeeName;
             this.Dispatch = Dispatch;
             this.UpdatedOn = UpdatedOn;
             this.ReleaseNotes = ReleaseNotes;
             this.ReleaseBy = ReleaseBy;
             this.ReleaseStatus = ReleaseStatus;
             this.ApprovalNotes = ApprovalNotes;
             this.ApprovalBy = ApprovalBy;
             this.ApprovalStatus = ApprovalStatus;
             this.LockNotes = LockNotes;
             this.LockedBy = LockedBy;
             this.LockStatus = LockStatus;
             this.ContactInfo = ContactInfo;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column EventDate.
        /// </summary>
        public DateTime? EventDate { set; get; }

        /// <summary>
        /// Maps to table value column Hash.
        /// </summary>
        public int Hash { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeId.
        /// </summary>
        public int EmployeeId { set; get; }

        /// <summary>
        /// Maps to table value column EmpName.
        /// </summary>
        public string EmpName { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeName.
        /// </summary>
        public string EmployeeName { set; get; }

        /// <summary>
        /// Maps to table value column Dispatch.
        /// </summary>
        public string? Dispatch { set; get; }

        /// <summary>
        /// Maps to table value column UpdatedOn.
        /// </summary>
        public DateTime UpdatedOn { set; get; }

        /// <summary>
        /// Maps to table value column ReleaseNotes.
        /// </summary>
        public string? ReleaseNotes { set; get; }

        /// <summary>
        /// Maps to table value column ReleaseBy.
        /// </summary>
        public int ReleaseBy { set; get; }

        /// <summary>
        /// Maps to table value column ReleaseStatus.
        /// </summary>
        public int ReleaseStatus { set; get; }

        /// <summary>
        /// Maps to table value column ApprovalNotes.
        /// </summary>
        public string? ApprovalNotes { set; get; }

        /// <summary>
        /// Maps to table value column ApprovalBy.
        /// </summary>
        public int ApprovalBy { set; get; }

        /// <summary>
        /// Maps to table value column ApprovalStatus.
        /// </summary>
        public int ApprovalStatus { set; get; }

        /// <summary>
        /// Maps to table value column LockNotes.
        /// </summary>
        public string? LockNotes { set; get; }

        /// <summary>
        /// Maps to table value column LockedBy.
        /// </summary>
        public int LockedBy { set; get; }

        /// <summary>
        /// Maps to table value column LockStatus.
        /// </summary>
        public int LockStatus { set; get; }

        /// <summary>
        /// Maps to table value column ContactInfo.
        /// </summary>
        public string? ContactInfo { set; get; }
    }

    #endregion Result Set Objects

}
