// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: VersionTracker
//     Last Modified On: 10/25/2024 1:44:23 PM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable
    /// <summary>
    /// Output object for VersionTracker service.
    /// </summary>
    public partial class VersionTrackerOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of VersionTrackerResult.
        /// </summary>
        public VersionTrackerResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for VersionTracker service.
    /// </summary>


    public partial class VersionTrackerResult
	{
        /// <summary>
        /// Result set object for VersionTracker.
        /// </summary>
        /// <param name="MobileVersion">Maps to table value column MobileVersion.</param>
        public VersionTrackerResult(string MobileVersion)
        {
             this.MobileVersion = MobileVersion;
        }


        /// <summary>
        /// Maps to table value column MobileVersion.
        /// </summary>
        public string MobileVersion { set; get; }
    }

    #endregion Result Set Objects

}
