// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowById
//     Last Modified On: 8/11/2024 3:34:56 AM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable
    /// <summary>
    /// Output object for WorkflowById service.
    /// </summary>
    public partial class WorkflowByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of WorkflowByIdResult.
        /// </summary>
        public WorkflowByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowById service.
    /// </summary>


    public partial class WorkflowByIdResult
	{
        /// <summary>
        /// Result set object for WorkflowById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="ShareExternally">Maps to table value column ShareExternally.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Prompt">Maps to table value column Prompt.</param>
        /// <param name="WorkflowTagId">Maps to table value column WorkflowTagId.</param>
        /// <param name="NotificationGroupId">Maps to table value column NotificationGroupId.</param>
        /// <param name="HelpText">Maps to table value column HelpText.</param>
        /// <param name="AutoLoad">Maps to table value column AutoLoad.</param>
        /// <param name="AutoStart">Maps to table value column AutoStart.</param>
        /// <param name="TagPriority">Maps to table value column TagPriority.</param>
        /// <param name="RequireDispatch">Maps to table value column RequireDispatch.</param>
        /// <param name="RunOnceId">Maps to table value column RunOnceId.</param>
        /// <param name="HideFromSelection">Maps to table value column HideFromSelection.</param>
        /// <param name="VariableHydrationMode">Maps to table value column VariableHydrationMode.</param>
        /// <param name="RecapBehavior">Maps to table value column RecapBehavior.</param>
        /// <param name="RowUserId">Maps to table value column RowUserId.</param>
        public WorkflowByIdResult(int Id, bool Active, bool ShareExternally, string Name, string? Description, string Prompt, int? WorkflowTagId, int? NotificationGroupId, string? HelpText, bool AutoLoad, bool AutoStart, bool TagPriority, bool RequireDispatch, int RunOnceId, bool HideFromSelection, int VariableHydrationMode, int RecapBehavior, int RowUserId)
        {
             this.Id = Id;
             this.Active = Active;
             this.ShareExternally = ShareExternally;
             this.Name = Name;
             this.Description = Description;
             this.Prompt = Prompt;
             this.WorkflowTagId = WorkflowTagId;
             this.NotificationGroupId = NotificationGroupId;
             this.HelpText = HelpText;
             this.AutoLoad = AutoLoad;
             this.AutoStart = AutoStart;
             this.TagPriority = TagPriority;
             this.RequireDispatch = RequireDispatch;
             this.RunOnceId = RunOnceId;
             this.HideFromSelection = HideFromSelection;
             this.VariableHydrationMode = VariableHydrationMode;
             this.RecapBehavior = RecapBehavior;
             this.RowUserId = RowUserId;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column ShareExternally.
        /// </summary>
        public bool ShareExternally { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string? Description { set; get; }

        /// <summary>
        /// Maps to table value column Prompt.
        /// </summary>
        public string Prompt { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowTagId.
        /// </summary>
        public int? WorkflowTagId { set; get; }

        /// <summary>
        /// Maps to table value column NotificationGroupId.
        /// </summary>
        public int? NotificationGroupId { set; get; }

        /// <summary>
        /// Maps to table value column HelpText.
        /// </summary>
        public string? HelpText { set; get; }

        /// <summary>
        /// Maps to table value column AutoLoad.
        /// </summary>
        public bool AutoLoad { set; get; }

        /// <summary>
        /// Maps to table value column AutoStart.
        /// </summary>
        public bool AutoStart { set; get; }

        /// <summary>
        /// Maps to table value column TagPriority.
        /// </summary>
        public bool TagPriority { set; get; }

        /// <summary>
        /// Maps to table value column RequireDispatch.
        /// </summary>
        public bool RequireDispatch { set; get; }

        /// <summary>
        /// Maps to table value column RunOnceId.
        /// </summary>
        public int RunOnceId { set; get; }

        /// <summary>
        /// Maps to table value column HideFromSelection.
        /// </summary>
        public bool HideFromSelection { set; get; }

        /// <summary>
        /// Maps to table value column VariableHydrationMode.
        /// </summary>
        public int VariableHydrationMode { set; get; }

        /// <summary>
        /// Maps to table value column RecapBehavior.
        /// </summary>
        public int RecapBehavior { set; get; }

        /// <summary>
        /// Maps to table value column RowUserId.
        /// </summary>
        public int RowUserId { set; get; }
    }

    #endregion Result Set Objects

}
