// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowJobLogById
//     Last Modified On: 7/12/2024 4:58:11 PM
//     Written By: ICS
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowJobLogById service.
    /// </summary>
    public partial class WorkflowJobLogByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowJobLogByIdInput.
        /// </summary>
        public WorkflowJobLogByIdInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowJobLogByIdInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public WorkflowJobLogByIdInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}