// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderTaskCodeList
//     Last Modified On: 4/16/2025 5:09:32 PM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkOrderTaskCodeList service.
    /// </summary>
    public partial class WorkOrderTaskCodeListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkOrderTaskCodeListResult.
        /// </summary>
        public List<WorkOrderTaskCodeListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkOrderTaskCodeList service.
    /// </summary>


    public partial class WorkOrderTaskCodeListResult
	{
        /// <summary>
        /// Result set object for WorkOrderTaskCodeList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="TaskCode">Maps to table value column TaskCode.</param>
        /// <param name="Task">Maps to table value column Task.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="ExternalKey">Maps to table value column ExternalKey.</param>
        public WorkOrderTaskCodeListResult(int Id, string? TaskCode, string? Task, string? Description, string? ExternalKey)
        {
             this.Id = Id;
             this.TaskCode = TaskCode;
             this.Task = Task;
             this.Description = Description;
             this.ExternalKey = ExternalKey;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column TaskCode.
        /// </summary>
        public string? TaskCode { set; get; }

        /// <summary>
        /// Maps to table value column Task.
        /// </summary>
        public string? Task { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string? Description { set; get; }

        /// <summary>
        /// Maps to table value column ExternalKey.
        /// </summary>
        public string? ExternalKey { set; get; }
    }

    #endregion Result Set Objects

}
