// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowJobSheetList
//     Last Modified On: 7/27/2024 5:56:21 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkflowJobSheetList service.
    /// </summary>
    public partial class WorkflowJobSheetListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkflowJobSheetListResult.
        /// </summary>
        public List<WorkflowJobSheetListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowJobSheetList service.
    /// </summary>


    public partial class WorkflowJobSheetListResult
	{
        /// <summary>
        /// Result set object for WorkflowJobSheetList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="WorkflowId">Maps to table value column WorkflowId.</param>
        /// <param name="WorkFlowName">Maps to table value column WorkFlowName.</param>
        /// <param name="WorkFlowPrompt">Maps to table value column WorkFlowPrompt.</param>
        /// <param name="WorkFlowSharePrompt">Maps to table value column WorkFlowSharePrompt.</param>
        /// <param name="SheetType">Maps to table value column SheetType.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Overwrite">Maps to table value column Overwrite.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="ScheduleId">Maps to table value column ScheduleId.</param>
        /// <param name="SheetId">Maps to table value column SheetId.</param>
        /// <param name="Tab">Maps to table value column Tab.</param>
        /// <param name="Range">Maps to table value column Range.</param>
        /// <param name="ColumnList">Maps to table value column ColumnList.</param>
        /// <param name="CustomerIds">Maps to table value column CustomerIds.</param>
        /// <param name="LocationIds">Maps to table value column LocationIds.</param>
        /// <param name="TaskCodeIds">Maps to table value column TaskCodeIds.</param>
        /// <param name="EmployeeIds">Maps to table value column EmployeeIds.</param>
        /// <param name="RowUserId">Maps to table value column RowUserId.</param>
        public WorkflowJobSheetListResult(int Id, int WorkflowId, string? WorkFlowName, string? WorkFlowPrompt, string? WorkFlowSharePrompt, int SheetType, string Name, string? Description, bool Overwrite, bool Active, int ScheduleId, string? SheetId, string? Tab, string? Range, string? ColumnList, string? CustomerIds, string? LocationIds, string? TaskCodeIds, string? EmployeeIds, int RowUserId)
        {
             this.Id = Id;
             this.WorkflowId = WorkflowId;
             this.WorkFlowName = WorkFlowName;
             this.WorkFlowPrompt = WorkFlowPrompt;
             this.WorkFlowSharePrompt = WorkFlowSharePrompt;
             this.SheetType = SheetType;
             this.Name = Name;
             this.Description = Description;
             this.Overwrite = Overwrite;
             this.Active = Active;
             this.ScheduleId = ScheduleId;
             this.SheetId = SheetId;
             this.Tab = Tab;
             this.Range = Range;
             this.ColumnList = ColumnList;
             this.CustomerIds = CustomerIds;
             this.LocationIds = LocationIds;
             this.TaskCodeIds = TaskCodeIds;
             this.EmployeeIds = EmployeeIds;
             this.RowUserId = RowUserId;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowId.
        /// </summary>
        public int WorkflowId { set; get; }

        /// <summary>
        /// Maps to table value column WorkFlowName.
        /// </summary>
        public string? WorkFlowName { set; get; }

        /// <summary>
        /// Maps to table value column WorkFlowPrompt.
        /// </summary>
        public string? WorkFlowPrompt { set; get; }

        /// <summary>
        /// Maps to table value column WorkFlowSharePrompt.
        /// </summary>
        public string? WorkFlowSharePrompt { set; get; }

        /// <summary>
        /// Maps to table value column SheetType.
        /// </summary>
        public int SheetType { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string? Description { set; get; }

        /// <summary>
        /// Maps to table value column Overwrite.
        /// </summary>
        public bool Overwrite { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column ScheduleId.
        /// </summary>
        public int ScheduleId { set; get; }

        /// <summary>
        /// Maps to table value column SheetId.
        /// </summary>
        public string? SheetId { set; get; }

        /// <summary>
        /// Maps to table value column Tab.
        /// </summary>
        public string? Tab { set; get; }

        /// <summary>
        /// Maps to table value column Range.
        /// </summary>
        public string? Range { set; get; }

        /// <summary>
        /// Maps to table value column ColumnList.
        /// </summary>
        public string? ColumnList { set; get; }

        /// <summary>
        /// Maps to table value column CustomerIds.
        /// </summary>
        public string? CustomerIds { set; get; }

        /// <summary>
        /// Maps to table value column LocationIds.
        /// </summary>
        public string? LocationIds { set; get; }

        /// <summary>
        /// Maps to table value column TaskCodeIds.
        /// </summary>
        public string? TaskCodeIds { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeIds.
        /// </summary>
        public string? EmployeeIds { set; get; }

        /// <summary>
        /// Maps to table value column RowUserId.
        /// </summary>
        public int RowUserId { set; get; }
    }

    #endregion Result Set Objects

}
