// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowJobSheetList
//     Last Modified On: 7/27/2024 5:56:21 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowJobSheetList service.
    /// </summary>
    public partial class WorkflowJobSheetListInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowJobSheetListInput.
        /// </summary>
        public WorkflowJobSheetListInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowJobSheetListInput.
        /// </summary>
        /// <param name="WorkflowId">WorkflowId</param>
        /// <param name="SheetType">SheetType</param>
        /// <param name="Name">Name</param>
        /// <param name="Description">Description</param>
        /// <param name="Overwrite">Overwrite</param>
        /// <param name="Active">Active</param>
        /// <param name="ScheduleId">ScheduleId</param>
        /// <param name="SheetId">SheetId</param>
        /// <param name="Tab">Tab</param>
        /// <param name="CustomerId">CustomerId</param>
        /// <param name="CustomerLocationId">LocationId</param>
        /// <param name="TaskCodeId">TaskCodeId</param>
        /// <param name="EmployeeId">EmployeeId</param>
        /// <param name="RowUserId">RowUserId</param>
        public WorkflowJobSheetListInput(int? WorkflowId, int? SheetType, string? Name, string? Description, bool? Overwrite, bool? Active, int? ScheduleId, string? SheetId, string? Tab, int? CustomerId, int? CustomerLocationId, string? TaskCodeId, int? EmployeeId, int? RowUserId)
        {
            this.WorkflowId = WorkflowId;
            this.SheetType = SheetType;
            this.Name = Name;
            this.Description = Description;
            this.Overwrite = Overwrite;
            this.Active = Active;
            this.ScheduleId = ScheduleId;
            this.SheetId = SheetId;
            this.Tab = Tab;
            this.CustomerId = CustomerId;
            this.CustomerLocationId = CustomerLocationId;
            this.TaskCodeId = TaskCodeId;
            this.EmployeeId = EmployeeId;
            this.RowUserId = RowUserId;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowId;
        /// <summary>
        /// WorkflowId
        /// </summary>
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        private int? _SheetType;
        /// <summary>
        /// SheetType
        /// </summary>
        public int? SheetType
        {
            get => _SheetType;
            set => _SheetType = value;
        }

        private string? _Name;
        /// <summary>
        /// Name
        /// </summary>
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private string? _Description;
        /// <summary>
        /// Description
        /// </summary>
        public string? Description
        {
            get => _Description;
            set => _Description = value;
        }

        private bool? _Overwrite;
        /// <summary>
        /// Overwrite
        /// </summary>
        public bool? Overwrite
        {
            get => _Overwrite;
            set => _Overwrite = value;
        }

        private bool? _Active;
        /// <summary>
        /// Active
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        private int? _ScheduleId;
        /// <summary>
        /// ScheduleId
        /// </summary>
        public int? ScheduleId
        {
            get => _ScheduleId;
            set => _ScheduleId = value;
        }

        private string? _SheetId;
        /// <summary>
        /// SheetId
        /// </summary>
        public string? SheetId
        {
            get => _SheetId;
            set => _SheetId = value;
        }

        private string? _Tab;
        /// <summary>
        /// Tab
        /// </summary>
        public string? Tab
        {
            get => _Tab;
            set => _Tab = value;
        }

        private int? _CustomerId;
        /// <summary>
        /// CustomerId
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private int? _CustomerLocationId;
        /// <summary>
        /// LocationId
        /// </summary>
        public int? CustomerLocationId
        {
            get => _CustomerLocationId;
            set => _CustomerLocationId = value;
        }

        private string? _TaskCodeId;
        /// <summary>
        /// TaskCodeId
        /// </summary>
        public string? TaskCodeId
        {
            get => _TaskCodeId;
            set => _TaskCodeId = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// EmployeeId
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _RowUserId;
        /// <summary>
        /// RowUserId
        /// </summary>
        public int? RowUserId
        {
            get => _RowUserId;
            set => _RowUserId = value;
        }

        #endregion

    }
}