// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowNotificationGroupAssignmentsById
//     Last Modified On: 11/10/2023 8:32:12 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowNotificationGroupAssignmentsById service.
    /// </summary>
    public partial class WorkflowNotificationGroupAssignmentsByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowNotificationGroupAssignmentsByIdInput.
        /// </summary>
        public WorkflowNotificationGroupAssignmentsByIdInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowNotificationGroupAssignmentsByIdInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public WorkflowNotificationGroupAssignmentsByIdInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}