// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowResultList_OG
//     Last Modified On: 11/27/2025 12:30:04 AM
//     Written By: alan & kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowResultList_OG service.
    /// </summary>
    public partial class WorkflowResultList_OGInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowResultList_OGInput.
        /// </summary>
        public WorkflowResultList_OGInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowResultList_OGInput.
        /// </summary>
        /// <param name="Active">Maps to parameter @Active.</param>
        /// <param name="Complete">Maps to parameter @Complete.</param>
        /// <param name="Status">Maps to parameter @Status.</param>
        /// <param name="CompletedBefore">Maps to parameter @CompletedBefore.</param>
        /// <param name="CompletedAfter">Maps to parameter @CompletedAfter.</param>
        /// <param name="CreatedBefore">Maps to parameter @CreatedBefore.</param>
        /// <param name="CreatedAfter">Maps to parameter @CreatedAfter.</param>
        /// <param name="RunOnceId">Maps to parameter @RunOnceId.</param>
        /// <param name="WorkflowResultId">Maps to parameter @WorkflowResultId.</param>
        /// <param name="WorkflowId">Maps to parameter @WorkflowId.</param>
        /// <param name="BinderId">Maps to parameter @BinderId.</param>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        /// <param name="CustomerLocationId">Maps to parameter @CustomerLocationId.</param>
        /// <param name="WorkOrderDispatchId">Maps to parameter @WorkOrderDispatchId.</param>
        /// <param name="WorkOrderDispatchTechId">Maps to parameter @WorkOrderDispatchTechId.</param>
        /// <param name="StatusList">Maps to parameter @StatusList.</param>
        /// <param name="WorkflowResultIdList">Maps to parameter @WorkflowResultIdList.</param>
        /// <param name="WorkflowIdList">Maps to parameter @WorkflowIdList.</param>
        /// <param name="BinderIdList">Maps to parameter @BinderIdList.</param>
        /// <param name="EmployeeIdList">Maps to parameter @EmployeeIdList.</param>
        /// <param name="CustomerIdList">Maps to parameter @CustomerIdList.</param>
        /// <param name="CustomerLocationIdList">Maps to parameter @CustomerLocationIdList.</param>
        /// <param name="WorkOrderDispatchIdList">Maps to parameter @WorkOrderDispatchIdList.</param>
        /// <param name="WorkOrderDispatchTechIdList">Maps to parameter @WorkOrderDispatchTechIdList.</param>
        /// <param name="AttributeId">Maps to parameter @AttributeId.</param>
        public WorkflowResultList_OGInput(bool? Active, bool? Complete, int? Status, DateTime? CompletedBefore, DateTime? CompletedAfter, DateTime? CreatedBefore, DateTime? CreatedAfter, int? RunOnceId, int? WorkflowResultId, int? WorkflowId, int? BinderId, int? EmployeeId, int? CustomerId, int? CustomerLocationId, int? WorkOrderDispatchId, int? WorkOrderDispatchTechId, string? StatusList, string? WorkflowResultIdList, string? WorkflowIdList, string? BinderIdList, string? EmployeeIdList, string? CustomerIdList, string? CustomerLocationIdList, string? WorkOrderDispatchIdList, string? WorkOrderDispatchTechIdList, int? AttributeId)
        {
            this.Active = Active;
            this.Complete = Complete;
            this.Status = Status;
            this.CompletedBefore = CompletedBefore;
            this.CompletedAfter = CompletedAfter;
            this.CreatedBefore = CreatedBefore;
            this.CreatedAfter = CreatedAfter;
            this.RunOnceId = RunOnceId;
            this.WorkflowResultId = WorkflowResultId;
            this.WorkflowId = WorkflowId;
            this.BinderId = BinderId;
            this.EmployeeId = EmployeeId;
            this.CustomerId = CustomerId;
            this.CustomerLocationId = CustomerLocationId;
            this.WorkOrderDispatchId = WorkOrderDispatchId;
            this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
            this.StatusList = StatusList;
            this.WorkflowResultIdList = WorkflowResultIdList;
            this.WorkflowIdList = WorkflowIdList;
            this.BinderIdList = BinderIdList;
            this.EmployeeIdList = EmployeeIdList;
            this.CustomerIdList = CustomerIdList;
            this.CustomerLocationIdList = CustomerLocationIdList;
            this.WorkOrderDispatchIdList = WorkOrderDispatchIdList;
            this.WorkOrderDispatchTechIdList = WorkOrderDispatchTechIdList;
            this.AttributeId = AttributeId;
        }

        #endregion Constructors

        #region Fields

        private bool? _Active;
        /// <summary>
        /// Maps to parameter @Active.
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        private bool? _Complete;
        /// <summary>
        /// Maps to parameter @Complete.
        /// </summary>
        public bool? Complete
        {
            get => _Complete;
            set => _Complete = value;
        }

        private int? _Status;
        /// <summary>
        /// Maps to parameter @Status.
        /// </summary>
        public int? Status
        {
            get => _Status;
            set => _Status = value;
        }

        private DateTime? _CompletedBefore;
        /// <summary>
        /// Maps to parameter @CompletedBefore.
        /// </summary>
        public DateTime? CompletedBefore
        {
            get => _CompletedBefore;
            set => _CompletedBefore = value;
        }

        private DateTime? _CompletedAfter;
        /// <summary>
        /// Maps to parameter @CompletedAfter.
        /// </summary>
        public DateTime? CompletedAfter
        {
            get => _CompletedAfter;
            set => _CompletedAfter = value;
        }

        private DateTime? _CreatedBefore;
        /// <summary>
        /// Maps to parameter @CreatedBefore.
        /// </summary>
        public DateTime? CreatedBefore
        {
            get => _CreatedBefore;
            set => _CreatedBefore = value;
        }

        private DateTime? _CreatedAfter;
        /// <summary>
        /// Maps to parameter @CreatedAfter.
        /// </summary>
        public DateTime? CreatedAfter
        {
            get => _CreatedAfter;
            set => _CreatedAfter = value;
        }

        private int? _RunOnceId;
        /// <summary>
        /// Maps to parameter @RunOnceId.
        /// </summary>
        public int? RunOnceId
        {
            get => _RunOnceId;
            set => _RunOnceId = value;
        }

        private int? _WorkflowResultId;
        /// <summary>
        /// Maps to parameter @WorkflowResultId.
        /// </summary>
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private int? _WorkflowId;
        /// <summary>
        /// Maps to parameter @WorkflowId.
        /// </summary>
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        private int? _BinderId;
        /// <summary>
        /// Maps to parameter @BinderId.
        /// </summary>
        public int? BinderId
        {
            get => _BinderId;
            set => _BinderId = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _CustomerId;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private int? _CustomerLocationId;
        /// <summary>
        /// Maps to parameter @CustomerLocationId.
        /// </summary>
        public int? CustomerLocationId
        {
            get => _CustomerLocationId;
            set => _CustomerLocationId = value;
        }

        private int? _WorkOrderDispatchId;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchId.
        /// </summary>
        public int? WorkOrderDispatchId
        {
            get => _WorkOrderDispatchId;
            set => _WorkOrderDispatchId = value;
        }

        private int? _WorkOrderDispatchTechId;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchTechId.
        /// </summary>
        public int? WorkOrderDispatchTechId
        {
            get => _WorkOrderDispatchTechId;
            set => _WorkOrderDispatchTechId = value;
        }

        private string? _StatusList;
        /// <summary>
        /// Maps to parameter @StatusList.
        /// </summary>
        public string? StatusList
        {
            get => _StatusList;
            set => _StatusList = value;
        }

        private string? _WorkflowResultIdList;
        /// <summary>
        /// Maps to parameter @WorkflowResultIdList.
        /// </summary>
        public string? WorkflowResultIdList
        {
            get => _WorkflowResultIdList;
            set => _WorkflowResultIdList = value;
        }

        private string? _WorkflowIdList;
        /// <summary>
        /// Maps to parameter @WorkflowIdList.
        /// </summary>
        public string? WorkflowIdList
        {
            get => _WorkflowIdList;
            set => _WorkflowIdList = value;
        }

        private string? _BinderIdList;
        /// <summary>
        /// Maps to parameter @BinderIdList.
        /// </summary>
        public string? BinderIdList
        {
            get => _BinderIdList;
            set => _BinderIdList = value;
        }

        private string? _EmployeeIdList;
        /// <summary>
        /// Maps to parameter @EmployeeIdList.
        /// </summary>
        public string? EmployeeIdList
        {
            get => _EmployeeIdList;
            set => _EmployeeIdList = value;
        }

        private string? _CustomerIdList;
        /// <summary>
        /// Maps to parameter @CustomerIdList.
        /// </summary>
        public string? CustomerIdList
        {
            get => _CustomerIdList;
            set => _CustomerIdList = value;
        }

        private string? _CustomerLocationIdList;
        /// <summary>
        /// Maps to parameter @CustomerLocationIdList.
        /// </summary>
        public string? CustomerLocationIdList
        {
            get => _CustomerLocationIdList;
            set => _CustomerLocationIdList = value;
        }

        private string? _WorkOrderDispatchIdList;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchIdList.
        /// </summary>
        public string? WorkOrderDispatchIdList
        {
            get => _WorkOrderDispatchIdList;
            set => _WorkOrderDispatchIdList = value;
        }

        private string? _WorkOrderDispatchTechIdList;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchTechIdList.
        /// </summary>
        public string? WorkOrderDispatchTechIdList
        {
            get => _WorkOrderDispatchTechIdList;
            set => _WorkOrderDispatchTechIdList = value;
        }

        private int? _AttributeId;
        /// <summary>
        /// Maps to parameter @AttributeId.
        /// </summary>
        public int? AttributeId
        {
            get => _AttributeId;
            set => _AttributeId = value;
        }

        #endregion

    }
}