// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStepResultShareExtMismatches
//     Last Modified On: 2/4/2025 3:41:43 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkflowStepResultShareExtMismatches service.
    /// </summary>
    public partial class WorkflowStepResultShareExtMismatchesOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 1,
            /// <summary>
            /// Enumerated value for MisMatchesFound
            /// </summary>
             MisMatchesFound = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkflowStepResultShareExtMismatchesResult.
        /// </summary>
        public List<WorkflowStepResultShareExtMismatchesResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowStepResultShareExtMismatches service.
    /// </summary>


    public partial class WorkflowStepResultShareExtMismatchesResult
	{
        /// <summary>
        /// Result set object for WorkflowStepResultShareExtMismatches.
        /// </summary>
        /// <param name="WorkflowStepResultId">Maps to table value column WorkflowStepResultId.</param>
        /// <param name="WorkflowResultId">Maps to table value column WorkflowResultId.</param>
        /// <param name="WorkflowStepId">Maps to table value column WorkflowStepId.</param>
        /// <param name="WorkflowId">Maps to table value column WorkflowId.</param>
        /// <param name="Position">Maps to table value column Position.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Prompt">Maps to table value column Prompt.</param>
        /// <param name="WFShare">Maps to table value column WFShare.</param>
        /// <param name="ShareExternally">Maps to table value column ShareExternally.</param>
        public WorkflowStepResultShareExtMismatchesResult(int WorkflowStepResultId, int WorkflowResultId, int WorkflowStepId, int WorkflowId, int Position, string Name, string Prompt, bool WFShare, bool ShareExternally)
        {
             this.WorkflowStepResultId = WorkflowStepResultId;
             this.WorkflowResultId = WorkflowResultId;
             this.WorkflowStepId = WorkflowStepId;
             this.WorkflowId = WorkflowId;
             this.Position = Position;
             this.Name = Name;
             this.Prompt = Prompt;
             this.WFShare = WFShare;
             this.ShareExternally = ShareExternally;
        }


        /// <summary>
        /// Maps to table value column WorkflowStepResultId.
        /// </summary>
        public int WorkflowStepResultId { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowResultId.
        /// </summary>
        public int WorkflowResultId { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowStepId.
        /// </summary>
        public int WorkflowStepId { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowId.
        /// </summary>
        public int WorkflowId { set; get; }

        /// <summary>
        /// Maps to table value column Position.
        /// </summary>
        public int Position { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Prompt.
        /// </summary>
        public string Prompt { set; get; }

        /// <summary>
        /// Maps to table value column WFShare.
        /// </summary>
        public bool WFShare { set; get; }

        /// <summary>
        /// Maps to table value column ShareExternally.
        /// </summary>
        public bool ShareExternally { set; get; }
    }

    #endregion Result Set Objects

}
