// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStageDetail
//     Last Modified On: 5/20/2025 10:19:11 PM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowStageDetail service.
    /// </summary>
    public partial class WorkflowStageDetailInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowStageDetailInput.
        /// </summary>
        public WorkflowStageDetailInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowStageDetailInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public WorkflowStageDetailInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}