// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowTagById
//     Last Modified On: 2/1/2025 2:01:03 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowTagById service.
    /// </summary>
    public partial class WorkflowTagByIdInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowTagByIdInput.
        /// </summary>
        public WorkflowTagByIdInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowTagByIdInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        public WorkflowTagByIdInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}