// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowTagById
//     Last Modified On: 2/1/2025 2:01:03 AM
//     Written By: Kirk Barrett
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable
    /// <summary>
    /// Output object for WorkflowTagById service.
    /// </summary>
    public partial class WorkflowTagByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of WorkflowTagByIdResult.
        /// </summary>
        public WorkflowTagByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowTagById service.
    /// </summary>


    public partial class WorkflowTagByIdResult
	{
        /// <summary>
        /// Result set object for WorkflowTagById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="ProcessingActive">Maps to table value column ProcessingActive.</param>
        /// <param name="RowUserId">Maps to table value column RowUserId.</param>
        public WorkflowTagByIdResult(int Id, string Name, string Description, bool Active, bool ProcessingActive, int RowUserId)
        {
             this.Id = Id;
             this.Name = Name;
             this.Description = Description;
             this.Active = Active;
             this.ProcessingActive = ProcessingActive;
             this.RowUserId = RowUserId;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column ProcessingActive.
        /// </summary>
        public bool ProcessingActive { set; get; }

        /// <summary>
        /// Maps to table value column RowUserId.
        /// </summary>
        public int RowUserId { set; get; }
    }

    #endregion Result Set Objects

}
