// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderDispatchNotes
//     Last Modified On: 3/1/2024 5:52:27 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkOrderDispatchNotes service.
    /// </summary>
    public partial class WorkOrderDispatchNotesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkOrderDispatchNotesInput.
        /// </summary>
        public WorkOrderDispatchNotesInput() { }

        /// <summary>
        /// Parameterized constructor for WorkOrderDispatchNotesInput.
        /// </summary>
        /// <param name="DispatchId">DispatchId</param>
        /// <param name="Dispatch">DispatchString</param>
        public WorkOrderDispatchNotesInput(int? DispatchId, string? Dispatch)
        {
            this.DispatchId = DispatchId;
            this.Dispatch = Dispatch;
        }

        #endregion Constructors

        #region Fields

        private int? _DispatchId;
        /// <summary>
        /// DispatchId
        /// </summary>
        public int? DispatchId
        {
            get => _DispatchId;
            set => _DispatchId = value;
        }

        private string? _Dispatch;
        /// <summary>
        /// DispatchString
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        #endregion

    }
}