// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowNotificationGroupList
//     Last Modified On: 12/31/2025 3:57:36 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkflowNotificationGroupList service.
    /// </summary>
    public partial class WorkflowNotificationGroupListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkflowNotificationGroupListResult.
        /// </summary>
        public List<WorkflowNotificationGroupListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowNotificationGroupList service.
    /// </summary>


    public partial class WorkflowNotificationGroupListResult
	{
        /// <summary>
        /// Result set object for WorkflowNotificationGroupList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Recipients">Maps to table value column Recipients.</param>
        /// <param name="Subject">Maps to table value column Subject.</param>
        /// <param name="Body">Maps to table value column Body.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        /// <param name="UsageCount">Maps to table value column UsageCount.</param>
        /// <param name="RowUserId">Maps to table value column RowUserId.</param>
        public WorkflowNotificationGroupListResult(int Id, string Name, string Description, string? Recipients, string? Subject, string? Body, bool Active, int? UsageCount, int RowUserId)
        {
             this.Id = Id;
             this.Name = Name;
             this.Description = Description;
             this.Recipients = Recipients;
             this.Subject = Subject;
             this.Body = Body;
             this.Active = Active;
             this.UsageCount = UsageCount;
             this.RowUserId = RowUserId;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column Recipients.
        /// </summary>
        public string? Recipients { set; get; }

        /// <summary>
        /// Maps to table value column Subject.
        /// </summary>
        public string? Subject { set; get; }

        /// <summary>
        /// Maps to table value column Body.
        /// </summary>
        public string? Body { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }

        /// <summary>
        /// Maps to table value column UsageCount.
        /// </summary>
        public int? UsageCount { set; get; }

        /// <summary>
        /// Maps to table value column RowUserId.
        /// </summary>
        public int RowUserId { set; get; }
    }

    #endregion Result Set Objects

}
