// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowDataQueryList
//     Last Modified On: 10/27/2023 10:48:21 AM
//     Written By: alan
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkflowDataQueryList service.
    /// </summary>
    public partial class WorkflowDataQueryListOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkflowDataQueryListResult.
        /// </summary>
        public List<WorkflowDataQueryListResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowDataQueryList service.
    /// </summary>


    public partial class WorkflowDataQueryListResult
	{
        /// <summary>
        /// Result set object for WorkflowDataQueryList.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="IsParameterized">Maps to table value column IsParameterized.</param>
        /// <param name="ParameterName">Maps to table value column ParameterName.</param>
        public WorkflowDataQueryListResult(int Id, string Name, bool IsParameterized, string? ParameterName)
        {
             this.Id = Id;
             this.Name = Name;
             this.IsParameterized = IsParameterized;
             this.ParameterName = ParameterName;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column IsParameterized.
        /// </summary>
        public bool IsParameterized { set; get; }

        /// <summary>
        /// Maps to table value column ParameterName.
        /// </summary>
        public string? ParameterName { set; get; }
    }

    #endregion Result Set Objects

}
