// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowSequenceQueryValue
//     Last Modified On: 1/6/2024 9:48:20 PM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowSequenceQueryValue service.
    /// </summary>
    public partial class WorkflowSequenceQueryValueInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowSequenceQueryValueInput.
        /// </summary>
        public WorkflowSequenceQueryValueInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowSequenceQueryValueInput.
        /// </summary>
        /// <param name="QueryId">Maps to parameter @QueryId.</param>
        /// <param name="WorkflowId">Maps to parameter @WorkflowId.</param>
        /// <param name="BinderId">Maps to parameter @BinderId.</param>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        /// <param name="CustomerId">Maps to parameter @CustomerId.</param>
        /// <param name="CustomerLocationId">Maps to parameter @CustomerLocationId.</param>
        /// <param name="WorkOrderDispatchId">Maps to parameter @WorkOrderDispatchId.</param>
        /// <param name="WorkOrderDispatchTechId">Maps to parameter @WorkOrderDispatchTechId.</param>
        public WorkflowSequenceQueryValueInput(int? QueryId, int? WorkflowId, int? BinderId, int? EmployeeId, int? CustomerId, int? CustomerLocationId, int? WorkOrderDispatchId, int? WorkOrderDispatchTechId)
        {
            this.QueryId = QueryId;
            this.WorkflowId = WorkflowId;
            this.BinderId = BinderId;
            this.EmployeeId = EmployeeId;
            this.CustomerId = CustomerId;
            this.CustomerLocationId = CustomerLocationId;
            this.WorkOrderDispatchId = WorkOrderDispatchId;
            this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
        }

        #endregion Constructors

        #region Fields

        private int? _QueryId;
        /// <summary>
        /// Maps to parameter @QueryId.
        /// </summary>
        public int? QueryId
        {
            get => _QueryId;
            set => _QueryId = value;
        }

        private int? _WorkflowId;
        /// <summary>
        /// Maps to parameter @WorkflowId.
        /// </summary>
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        private int? _BinderId;
        /// <summary>
        /// Maps to parameter @BinderId.
        /// </summary>
        public int? BinderId
        {
            get => _BinderId;
            set => _BinderId = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _CustomerId;
        /// <summary>
        /// Maps to parameter @CustomerId.
        /// </summary>
        public int? CustomerId
        {
            get => _CustomerId;
            set => _CustomerId = value;
        }

        private int? _CustomerLocationId;
        /// <summary>
        /// Maps to parameter @CustomerLocationId.
        /// </summary>
        public int? CustomerLocationId
        {
            get => _CustomerLocationId;
            set => _CustomerLocationId = value;
        }

        private int? _WorkOrderDispatchId;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchId.
        /// </summary>
        public int? WorkOrderDispatchId
        {
            get => _WorkOrderDispatchId;
            set => _WorkOrderDispatchId = value;
        }

        private int? _WorkOrderDispatchTechId;
        /// <summary>
        /// Maps to parameter @WorkOrderDispatchTechId.
        /// </summary>
        public int? WorkOrderDispatchTechId
        {
            get => _WorkOrderDispatchTechId;
            set => _WorkOrderDispatchTechId = value;
        }

        #endregion

    }
}