// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderDispatchTechActivityById
//     Last Modified On: 8/1/2024 2:43:05 AM
//     Written By: Kirk
//     Select Type: SingleRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for WorkOrderDispatchTechActivityById service.
    /// </summary>
    public partial class WorkOrderDispatchTechActivityByIdOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of WorkOrderDispatchTechActivityByIdResult.
        /// </summary>
        public WorkOrderDispatchTechActivityByIdResult? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkOrderDispatchTechActivityById service.
    /// </summary>


    public partial class WorkOrderDispatchTechActivityByIdResult
	{
        /// <summary>
        /// Result set object for WorkOrderDispatchTechActivityById.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="EmployeeId">Maps to table value column EmployeeId.</param>
        /// <param name="CustomerLocationId">Maps to table value column CustomerLocationId.</param>
        /// <param name="WorkOrderDispatchTechId">Maps to table value column WorkOrderDispatchTechId.</param>
        /// <param name="WorkOrderDispatchId">Maps to table value column WorkOrderDispatchId.</param>
        /// <param name="WorkflowResultId">Maps to table value column WorkflowResultId.</param>
        /// <param name="WorkflowStepResultId">Maps to table value column WorkflowStepResultId.</param>
        /// <param name="Status">Maps to table value column Status.</param>
        /// <param name="Activity">Maps to table value column Activity.</param>
        /// <param name="ActivityDate">Maps to table value column ActivityDate.</param>
        /// <param name="Latitude">Maps to table value column Latitude.</param>
        /// <param name="Longitude">Maps to table value column Longitude.</param>
        /// <param name="Equipment">Maps to table value column Equipment.</param>
        /// <param name="EquipmentId">Maps to table value column EquipmentId.</param>
        /// <param name="NewEquipmentId">Maps to table value column NewEquipmentId.</param>
        /// <param name="EquipmentPayload">Maps to table value column EquipmentPayload.</param>
        /// <param name="ItemsUsed">Maps to table value column ItemsUsed.</param>
        /// <param name="ItemsUsedPayload">Maps to table value column ItemsUsedPayload.</param>
        /// <param name="GeoSignatureHash">Maps to table value column GeoSignatureHash.</param>
        /// <param name="ExternalKey">Maps to table value column ExternalKey.</param>
        /// <param name="Notes">Maps to table value column Notes.</param>
        /// <param name="Tags">Maps to table value column Tags.</param>
        /// <param name="EntityId">Maps to table value column EntityId.</param>
        /// <param name="CreatedBy">Maps to table value column CreatedBy.</param>
        /// <param name="CreatedDate">Maps to table value column CreatedDate.</param>
        /// <param name="ModifiedBy">Maps to table value column ModifiedBy.</param>
        /// <param name="Hash">Maps to table value column Hash.</param>
        public WorkOrderDispatchTechActivityByIdResult(int Id, int EmployeeId, int CustomerLocationId, int WorkOrderDispatchTechId, int WorkOrderDispatchId, int WorkflowResultId, int WorkflowStepResultId, string Status, string? Activity, DateTimeOffset ActivityDate, decimal Latitude, decimal Longitude, string? Equipment, int EquipmentId, Guid? NewEquipmentId, string? EquipmentPayload, string? ItemsUsed, string? ItemsUsedPayload, int GeoSignatureHash, string? ExternalKey, string? Notes, string? Tags, string EntityId, int? CreatedBy, DateTime CreatedDate, int ModifiedBy, int Hash)
        {
             this.Id = Id;
             this.EmployeeId = EmployeeId;
             this.CustomerLocationId = CustomerLocationId;
             this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
             this.WorkOrderDispatchId = WorkOrderDispatchId;
             this.WorkflowResultId = WorkflowResultId;
             this.WorkflowStepResultId = WorkflowStepResultId;
             this.Status = Status;
             this.Activity = Activity;
             this.ActivityDate = ActivityDate;
             this.Latitude = Latitude;
             this.Longitude = Longitude;
             this.Equipment = Equipment;
             this.EquipmentId = EquipmentId;
             this.NewEquipmentId = NewEquipmentId;
             this.EquipmentPayload = EquipmentPayload;
             this.ItemsUsed = ItemsUsed;
             this.ItemsUsedPayload = ItemsUsedPayload;
             this.GeoSignatureHash = GeoSignatureHash;
             this.ExternalKey = ExternalKey;
             this.Notes = Notes;
             this.Tags = Tags;
             this.EntityId = EntityId;
             this.CreatedBy = CreatedBy;
             this.CreatedDate = CreatedDate;
             this.ModifiedBy = ModifiedBy;
             this.Hash = Hash;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column EmployeeId.
        /// </summary>
        public int EmployeeId { set; get; }

        /// <summary>
        /// Maps to table value column CustomerLocationId.
        /// </summary>
        public int CustomerLocationId { set; get; }

        /// <summary>
        /// Maps to table value column WorkOrderDispatchTechId.
        /// </summary>
        public int WorkOrderDispatchTechId { set; get; }

        /// <summary>
        /// Maps to table value column WorkOrderDispatchId.
        /// </summary>
        public int WorkOrderDispatchId { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowResultId.
        /// </summary>
        public int WorkflowResultId { set; get; }

        /// <summary>
        /// Maps to table value column WorkflowStepResultId.
        /// </summary>
        public int WorkflowStepResultId { set; get; }

        /// <summary>
        /// Maps to table value column Status.
        /// </summary>
        public string Status { set; get; }

        /// <summary>
        /// Maps to table value column Activity.
        /// </summary>
        public string? Activity { set; get; }

        /// <summary>
        /// Maps to table value column ActivityDate.
        /// </summary>
        public DateTimeOffset ActivityDate { set; get; }

        /// <summary>
        /// Maps to table value column Latitude.
        /// </summary>
        public decimal Latitude { set; get; }

        /// <summary>
        /// Maps to table value column Longitude.
        /// </summary>
        public decimal Longitude { set; get; }

        /// <summary>
        /// Maps to table value column Equipment.
        /// </summary>
        public string? Equipment { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentId.
        /// </summary>
        public int EquipmentId { set; get; }

        /// <summary>
        /// Maps to table value column NewEquipmentId.
        /// </summary>
        public Guid? NewEquipmentId { set; get; }

        /// <summary>
        /// Maps to table value column EquipmentPayload.
        /// </summary>
        public string? EquipmentPayload { set; get; }

        /// <summary>
        /// Maps to table value column ItemsUsed.
        /// </summary>
        public string? ItemsUsed { set; get; }

        /// <summary>
        /// Maps to table value column ItemsUsedPayload.
        /// </summary>
        public string? ItemsUsedPayload { set; get; }

        /// <summary>
        /// Maps to table value column GeoSignatureHash.
        /// </summary>
        public int GeoSignatureHash { set; get; }

        /// <summary>
        /// Maps to table value column ExternalKey.
        /// </summary>
        public string? ExternalKey { set; get; }

        /// <summary>
        /// Maps to table value column Notes.
        /// </summary>
        public string? Notes { set; get; }

        /// <summary>
        /// Maps to table value column Tags.
        /// </summary>
        public string? Tags { set; get; }

        /// <summary>
        /// Maps to table value column EntityId.
        /// </summary>
        public string EntityId { set; get; }

        /// <summary>
        /// Maps to table value column CreatedBy.
        /// </summary>
        public int? CreatedBy { set; get; }

        /// <summary>
        /// Maps to table value column CreatedDate.
        /// </summary>
        public DateTime CreatedDate { set; get; }

        /// <summary>
        /// Maps to table value column ModifiedBy.
        /// </summary>
        public int ModifiedBy { set; get; }

        /// <summary>
        /// Maps to table value column Hash.
        /// </summary>
        public int Hash { set; get; }
    }

    #endregion Result Set Objects

}
