// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStageStepAutoSwitchIds
//     Last Modified On: 4/10/2025 12:40:12 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowStageStepAutoSwitchIds service.
    /// </summary>
    public partial class WorkflowStageStepAutoSwitchIdsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowStageStepAutoSwitchIdsInput.
        /// </summary>
        public WorkflowStageStepAutoSwitchIdsInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowStageStepAutoSwitchIdsInput.
        /// </summary>
        /// <param name="WorkflowId">WorkflowId, Any workflow to scan for autoswitches</param>
        /// <param name="OnlyDynamicGroups">OnlyDynamicGroups,false to return all option values</param>
        public WorkflowStageStepAutoSwitchIdsInput(int? WorkflowId, bool? OnlyDynamicGroups)
        {
            this.WorkflowId = WorkflowId;
            this.OnlyDynamicGroups = OnlyDynamicGroups;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowId = 0;
        /// <summary>
        /// WorkflowId, Any workflow to scan for autoswitches
        /// </summary>
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        private bool? _OnlyDynamicGroups = true;
        /// <summary>
        /// OnlyDynamicGroups,false to return all option values
        /// </summary>
        public bool? OnlyDynamicGroups
        {
            get => _OnlyDynamicGroups;
            set => _OnlyDynamicGroups = value;
        }

        #endregion

    }
}