// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowPermissionType
//     Last Modified On: 1/3/2024 12:00:09 AM
//     Written By: Kirk Barrett
//     Select Type: MultiRow
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for WorkflowPermissionType service.
    /// </summary>
    public partial class WorkflowPermissionTypeOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of WorkflowPermissionTypeResult.
        /// </summary>
        public List<WorkflowPermissionTypeResult>? ResultData { set; get; }

        #endregion Result Data

    }

    #region Result Set Objects

    /// <summary>
    /// Result object for WorkflowPermissionType service.
    /// </summary>


    public partial class WorkflowPermissionTypeResult
	{
        /// <summary>
        /// Result set object for WorkflowPermissionType.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="Enum">Maps to table value column Enum.</param>
        /// <param name="Name">Maps to table value column Name.</param>
        /// <param name="Description">Maps to table value column Description.</param>
        /// <param name="Active">Maps to table value column Active.</param>
        public WorkflowPermissionTypeResult(int Id, string Enum, string Name, string Description, bool Active)
        {
             this.Id = Id;
             this.Enum = Enum;
             this.Name = Name;
             this.Description = Description;
             this.Active = Active;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column Enum.
        /// </summary>
        public string Enum { set; get; }

        /// <summary>
        /// Maps to table value column Name.
        /// </summary>
        public string Name { set; get; }

        /// <summary>
        /// Maps to table value column Description.
        /// </summary>
        public string Description { set; get; }

        /// <summary>
        /// Maps to table value column Active.
        /// </summary>
        public bool Active { set; get; }
    }

    #endregion Result Set Objects

}
