// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowAssocEntity
//     Last Modified On: 4/14/2025 8:57:31 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Queries.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowAssocEntity service.
    /// </summary>
    public partial class WorkflowAssocEntityInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowAssocEntityInput.
        /// </summary>
        public WorkflowAssocEntityInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowAssocEntityInput.
        /// </summary>
        /// <param name="EntityTypeId">Maps to parameter @EntityTypeId.</param>
        /// <param name="OmitDefault">Maps to parameter @OmitDefault.</param>
        /// <param name="OmitFilterDataService">Maps to parameter @OmitFilterDataService.</param>
        public WorkflowAssocEntityInput(int? EntityTypeId, bool? OmitDefault, bool? OmitFilterDataService)
        {
            this.EntityTypeId = EntityTypeId;
            this.OmitDefault = OmitDefault;
            this.OmitFilterDataService = OmitFilterDataService;
        }

        #endregion Constructors

        #region Fields

        private int? _EntityTypeId;
        /// <summary>
        /// Maps to parameter @EntityTypeId.
        /// </summary>
        public int? EntityTypeId
        {
            get => _EntityTypeId;
            set => _EntityTypeId = value;
        }

        private bool? _OmitDefault;
        /// <summary>
        /// Maps to parameter @OmitDefault.
        /// </summary>
        public bool? OmitDefault
        {
            get => _OmitDefault;
            set => _OmitDefault = value;
        }

        private bool? _OmitFilterDataService;
        /// <summary>
        /// Maps to parameter @OmitFilterDataService.
        /// </summary>
        public bool? OmitFilterDataService
        {
            get => _OmitFilterDataService;
            set => _OmitFilterDataService = value;
        }

        #endregion

    }
}