// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AliasSave
//     Last Modified On: 8/24/2024 4:51:21 AM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the AliasSave service.
    /// </summary>
    public partial class AliasSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AliasSaveInput.
        /// </summary>
        public AliasSaveInput() { }

        /// <summary>
        /// Parameterized constructor for AliasSaveInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="Active">Maps to parameter @Active.</param>
        /// <param name="Pattern">Maps to parameter @Pattern.</param>
        /// <param name="FieldType">Maps to parameter @FieldType.</param>
        /// <param name="FieldSize">Maps to parameter @FieldSize.</param>
        /// <param name="DefaultValue">Maps to parameter @DefaultValue.</param>
        /// <param name="KeyFields">Maps to parameter @KeyFields.</param>
        /// <param name="Resolved">Maps to parameter @Resolved.</param>
        /// <param name="SQLDef">Maps to parameter @SQLDef.</param>
        public AliasSaveInput(int? Id, bool? Active, string? Pattern, string? FieldType, int? FieldSize, string? DefaultValue, string? KeyFields, string? Resolved, string? SQLDef)
        {
            this.Id = Id;
            this.Active = Active;
            this.Pattern = Pattern;
            this.FieldType = FieldType;
            this.FieldSize = FieldSize;
            this.DefaultValue = DefaultValue;
            this.KeyFields = KeyFields;
            this.Resolved = Resolved;
            this.SQLDef = SQLDef;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private bool? _Active = true;
        /// <summary>
        /// Maps to parameter @Active.
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        private string? _Pattern = "";
        /// <summary>
        /// Maps to parameter @Pattern.
        /// </summary>
        [MaxLength(254)]
        public string? Pattern
        {
            get => _Pattern;
            set => _Pattern = value;
        }

        private string? _FieldType;
        /// <summary>
        /// Maps to parameter @FieldType.
        /// </summary>
        [MaxLength(50)]
        public string? FieldType
        {
            get => _FieldType;
            set => _FieldType = value;
        }

        private int? _FieldSize = 0;
        /// <summary>
        /// Maps to parameter @FieldSize.
        /// </summary>
        public int? FieldSize
        {
            get => _FieldSize;
            set => _FieldSize = value;
        }

        private string? _DefaultValue;
        /// <summary>
        /// Maps to parameter @DefaultValue.
        /// </summary>
        public string? DefaultValue
        {
            get => _DefaultValue;
            set => _DefaultValue = value;
        }

        private string? _KeyFields;
        /// <summary>
        /// Maps to parameter @KeyFields.
        /// </summary>
        [MaxLength(128)]
        public string? KeyFields
        {
            get => _KeyFields;
            set => _KeyFields = value;
        }

        private string? _Resolved;
        /// <summary>
        /// Maps to parameter @Resolved.
        /// </summary>
        [MaxLength(128)]
        public string? Resolved
        {
            get => _Resolved;
            set => _Resolved = value;
        }

        private string? _SQLDef;
        /// <summary>
        /// Maps to parameter @SQLDef.
        /// </summary>
        public string? SQLDef
        {
            get => _SQLDef;
            set => _SQLDef = value;
        }

        #endregion

    }
}