// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AuthorizedUserRoleSave
//     Last Modified On: 10/9/2024 5:08:06 PM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the AuthorizedUserRoleSave service.
    /// </summary>
    public partial class AuthorizedUserRoleSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AuthorizedUserRoleSaveInput.
        /// </summary>
        public AuthorizedUserRoleSaveInput() { }

        /// <summary>
        /// Parameterized constructor for AuthorizedUserRoleSaveInput.
        /// </summary>
        /// <param name="EntityId">Maps to parameter @EntityId.</param>
        /// <param name="RoleFlag">Maps to parameter @RoleFlag.</param>
        public AuthorizedUserRoleSaveInput(int? EntityId, long? RoleFlag)
        {
            this.EntityId = EntityId;
            this.RoleFlag = RoleFlag;
        }

        #endregion Constructors

        #region Fields

        private int? _EntityId;
        /// <summary>
        /// Maps to parameter @EntityId.
        /// </summary>
        [Required]
        public int? EntityId
        {
            get => _EntityId;
            set => _EntityId = value;
        }

        private long? _RoleFlag;
        /// <summary>
        /// Maps to parameter @RoleFlag.
        /// </summary>
        [Required]
        public long? RoleFlag
        {
            get => _RoleFlag;
            set => _RoleFlag = value;
        }

        #endregion

    }
}