// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AuthorizedUserSubscriptionSave
//     Last Modified On: 1/14/2025 3:11:50 PM
//     Written By: Alan@interiorcs.com
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the AuthorizedUserSubscriptionSave service.
    /// </summary>
    public partial class AuthorizedUserSubscriptionSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for AuthorizedUserSubscriptionSaveInput.
        /// </summary>
        public AuthorizedUserSubscriptionSaveInput() { }

        /// <summary>
        /// Parameterized constructor for AuthorizedUserSubscriptionSaveInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="RowOwnerId">Maps to parameter @RowOwnerId.</param>
        /// <param name="SubscriptionJson">Maps to parameter @SubscriptionJson.</param>
        public AuthorizedUserSubscriptionSaveInput(int? Id, int? RowOwnerId, string? SubscriptionJson)
        {
            this.Id = Id;
            this.RowOwnerId = RowOwnerId;
            this.SubscriptionJson = SubscriptionJson;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _RowOwnerId;
        /// <summary>
        /// Maps to parameter @RowOwnerId.
        /// </summary>
        [Required]
        public int? RowOwnerId
        {
            get => _RowOwnerId;
            set => _RowOwnerId = value;
        }

        private string? _SubscriptionJson;
        /// <summary>
        /// Maps to parameter @SubscriptionJson.
        /// </summary>
        [Required]
        public string? SubscriptionJson
        {
            get => _SubscriptionJson;
            set => _SubscriptionJson = value;
        }

        #endregion

    }
}