// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: BinderUpdateNotes
//     Last Modified On: 9/10/2024 5:02:19 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the BinderUpdateNotes service.
    /// </summary>
    public partial class BinderUpdateNotesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for BinderUpdateNotesInput.
        /// </summary>
        public BinderUpdateNotesInput() { }

        /// <summary>
        /// Parameterized constructor for BinderUpdateNotesInput.
        /// </summary>
        /// <param name="BinderId">Maps to parameter @BinderId.</param>
        /// <param name="Notes">Maps to parameter @Notes.</param>
        public BinderUpdateNotesInput(int? BinderId, string? Notes)
        {
            this.BinderId = BinderId;
            this.Notes = Notes;
        }

        #endregion Constructors

        #region Fields

        private int? _BinderId;
        /// <summary>
        /// Maps to parameter @BinderId.
        /// </summary>
        public int? BinderId
        {
            get => _BinderId;
            set => _BinderId = value;
        }

        private string? _Notes;
        /// <summary>
        /// Maps to parameter @Notes.
        /// </summary>
        public string? Notes
        {
            get => _Notes;
            set => _Notes = value;
        }

        #endregion

    }
}