// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: BluonCacheSave
//     Last Modified On: 7/26/2025 1:11:02 AM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the BluonCacheSave service.
    /// </summary>
    public partial class BluonCacheSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for BluonCacheSaveInput.
        /// </summary>
        public BluonCacheSaveInput() { }

        /// <summary>
        /// Parameterized constructor for BluonCacheSaveInput.
        /// </summary>
        /// <param name="URLHash">Maps to parameter @URLHash.</param>
        /// <param name="URL">URL</param>
        /// <param name="JsonData">JsonData</param>
        /// <param name="CreatedAt">CreatedAt</param>
        /// <param name="ExpiresAt">ExpiresAt</param>
        public BluonCacheSaveInput(int? URLHash, string? URL, string? JsonData, DateTime? CreatedAt, DateTime? ExpiresAt)
        {
            this.URLHash = URLHash;
            this.URL = URL;
            this.JsonData = JsonData;
            this.CreatedAt = CreatedAt;
            this.ExpiresAt = ExpiresAt;
        }

        #endregion Constructors

        #region Fields

        private int? _URLHash = 0;
        /// <summary>
        /// Maps to parameter @URLHash.
        /// </summary>
        [Required]
        public int? URLHash
        {
            get => _URLHash;
            set => _URLHash = value;
        }

        private string? _URL = null;
        /// <summary>
        /// URL
        /// </summary>
        [MaxLength(254)]
        public string? URL
        {
            get => _URL;
            set => _URL = value;
        }

        private string? _JsonData = null;
        /// <summary>
        /// JsonData
        /// </summary>
        [Required]
        public string? JsonData
        {
            get => _JsonData;
            set => _JsonData = value;
        }

        private DateTime? _CreatedAt = null;
        /// <summary>
        /// CreatedAt
        /// </summary>
        public DateTime? CreatedAt
        {
            get => _CreatedAt;
            set => _CreatedAt = value;
        }

        private DateTime? _ExpiresAt = null;
        /// <summary>
        /// ExpiresAt
        /// </summary>
        public DateTime? ExpiresAt
        {
            get => _ExpiresAt;
            set => _ExpiresAt = value;
        }

        #endregion

    }
}