// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: CustomerLocationAttributeSave
//     Last Modified On: 5/29/2024 2:53:08 PM
//     Written By: Kirk
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for CustomerLocationAttributeSave service.
    /// </summary>
    public partial class CustomerLocationAttributeSaveOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// A new CustomerLocationAttribute was created.
            /// </summary>
             Inserted = 1,
            /// <summary>
            /// No CustomerLocationAttribute was found with provided id.
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// The existing CustomerLocationAttribute was modified.
            /// </summary>
             Modified = 2,
            /// <summary>
            /// A CustomerLocationAttribute with that name already exists.
            /// </summary>
             Conflict = 3
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        public int? Id { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
