// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DeleteWorkflowSteps
//     Last Modified On: 8/9/2024 4:51:02 PM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using ICS.Portal.Data.UserDefinedTypes;
    using SqlPlusBase;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Input object for the DeleteWorkflowSteps service.
    /// </summary>
    public partial class DeleteWorkflowStepsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for DeleteWorkflowStepsInput.
        /// </summary>
        public DeleteWorkflowStepsInput() { }

        /// <summary>
        /// Parameterized constructor for DeleteWorkflowStepsInput.
        /// </summary>
        /// <param name="Source">Maps to parameter @Source.</param>
        public DeleteWorkflowStepsInput(List<IntList>? Source)
        {
            this.Source = Source;
        }

        #endregion Constructors

        #region Fields

        private List<IntList>? _Source;
        /// <summary>
        /// Maps to parameter @Source.
        /// </summary>
        public List<IntList>? Source
        {
            get => _Source;
            set => _Source = value;
        }

        #endregion

    }
}