// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: DynamicGroupsDelete
//     Last Modified On: 4/8/2025 6:34:59 PM
//     Written By: kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the DynamicGroupsDelete service.
    /// </summary>
    public partial class DynamicGroupsDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for DynamicGroupsDeleteInput.
        /// </summary>
        public DynamicGroupsDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for DynamicGroupsDeleteInput.
        /// </summary>
        /// <param name="Id">Id</param>
        public DynamicGroupsDeleteInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}