// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: EmployeeTimeToNextJob
//     Last Modified On: 1/3/2026 1:27:57 AM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for EmployeeTimeToNextJob service.
    /// </summary>
    public partial class EmployeeTimeToNextJobOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for NoOrigin
            /// </summary>
             NoOrigin = 2,
            /// <summary>
            /// Enumerated value for NoDestination
            /// </summary>
             NoDestination = 3,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1,
            /// <summary>
            /// Enumerated value for ErrorUpdating
            /// </summary>
             ErrorUpdating = 4
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// TimeToNextJob,JSON payload from map engine
        /// </summary>
        public string? TimeToNextJob { set; get; }
        /// <summary>
        /// TimeToNextJobMins, number of minutes until next job
        /// </summary>
        public int? TimeToNextJobMins { set; get; }
        /// <summary>
        /// OriginLatitude,Tech Current Lat
        /// </summary>
        public decimal? OriginLatitude { set; get; }
        /// <summary>
        /// OriginLongitude,Tech Current Long
        /// </summary>
        public decimal? OriginLongitude { set; get; }
        /// <summary>
        /// DestLatitude,Tech Next Job Address Lat
        /// </summary>
        public decimal? DestLatitude { set; get; }
        /// <summary>
        /// DestLongitude,Tech Next Job Address Long
        /// </summary>
        public decimal? DestLongitude { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
