// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: h_ForensicJobsInsert
//     Last Modified On: 2/28/2024 8:14:40 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the h_ForensicJobsInsert service.
    /// </summary>
    public partial class h_ForensicJobsInsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for h_ForensicJobsInsertInput.
        /// </summary>
        public h_ForensicJobsInsertInput() { }

        /// <summary>
        /// Parameterized constructor for h_ForensicJobsInsertInput.
        /// </summary>
        /// <param name="UserId">UserId</param>
        /// <param name="PayLoad">PayLoad</param>
        public h_ForensicJobsInsertInput(int? UserId, string? PayLoad)
        {
            this.UserId = UserId;
            this.PayLoad = PayLoad;
        }

        #endregion Constructors

        #region Fields

        private int? _UserId;
        /// <summary>
        /// UserId
        /// </summary>
        [Required]
        public int? UserId
        {
            get => _UserId;
            set => _UserId = value;
        }

        private string? _PayLoad;
        /// <summary>
        /// PayLoad
        /// </summary>
        public string? PayLoad
        {
            get => _PayLoad;
            set => _PayLoad = value;
        }

        #endregion

    }
}