// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ICSInventoryDelete
//     Last Modified On: 9/18/2024 3:50:32 AM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the ICSInventoryDelete service.
    /// </summary>
    public partial class ICSInventoryDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ICSInventoryDeleteInput.
        /// </summary>
        public ICSInventoryDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for ICSInventoryDeleteInput.
        /// </summary>
        /// <param name="item">Id</param>
        public ICSInventoryDeleteInput(string? item)
        {
            this.item = item;
        }

        #endregion Constructors

        #region Fields

        private string? _item;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public string? item
        {
            get => _item;
            set => _item = value;
        }

        #endregion

    }
}