// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: JobCodesSave
//     Last Modified On: 8/20/2025 7:01:51 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the JobCodesSave service.
    /// </summary>
    public partial class JobCodesSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for JobCodesSaveInput.
        /// </summary>
        public JobCodesSaveInput() { }

        /// <summary>
        /// Parameterized constructor for JobCodesSaveInput.
        /// </summary>
        /// <param name="JobCodeId">JobCodeId</param>
        /// <param name="BinderId">BinderId</param>
        /// <param name="WorkflowResultId">WorkflowResultId</param>
        /// <param name="WorkOrderDispatchTechId">WorkOrderDispatchTechId</param>
        /// <param name="EmployeeId">EmployeeId</param>
        /// <param name="EmployeeIdRequestor">EmployeeIdRequestor</param>
        /// <param name="JobCode">JobCode</param>
        /// <param name="JobValue">JobValue</param>
        public JobCodesSaveInput(int? JobCodeId, int? BinderId, int? WorkflowResultId, int? WorkOrderDispatchTechId, int? EmployeeId, int? EmployeeIdRequestor, string? JobCode, int? JobValue)
        {
            this.JobCodeId = JobCodeId;
            this.BinderId = BinderId;
            this.WorkflowResultId = WorkflowResultId;
            this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
            this.EmployeeId = EmployeeId;
            this.EmployeeIdRequestor = EmployeeIdRequestor;
            this.JobCode = JobCode;
            this.JobValue = JobValue;
        }

        #endregion Constructors

        #region Fields

        private int? _JobCodeId = 0;
        /// <summary>
        /// JobCodeId
        /// </summary>
        public int? JobCodeId
        {
            get => _JobCodeId;
            set => _JobCodeId = value;
        }

        private int? _BinderId = 0;
        /// <summary>
        /// BinderId
        /// </summary>
        public int? BinderId
        {
            get => _BinderId;
            set => _BinderId = value;
        }

        private int? _WorkflowResultId = 0;
        /// <summary>
        /// WorkflowResultId
        /// </summary>
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private int? _WorkOrderDispatchTechId = 0;
        /// <summary>
        /// WorkOrderDispatchTechId
        /// </summary>
        public int? WorkOrderDispatchTechId
        {
            get => _WorkOrderDispatchTechId;
            set => _WorkOrderDispatchTechId = value;
        }

        private int? _EmployeeId = 0;
        /// <summary>
        /// EmployeeId
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _EmployeeIdRequestor = 0;
        /// <summary>
        /// EmployeeIdRequestor
        /// </summary>
        public int? EmployeeIdRequestor
        {
            get => _EmployeeIdRequestor;
            set => _EmployeeIdRequestor = value;
        }

        private string? _JobCode = null;
        /// <summary>
        /// JobCode
        /// </summary>
        [MaxLength(7)]
        public string? JobCode
        {
            get => _JobCode;
            set => _JobCode = value;
        }

        private int? _JobValue = 0;
        /// <summary>
        /// JobValue
        /// </summary>
        public int? JobValue
        {
            get => _JobValue;
            set => _JobValue = value;
        }

        #endregion

    }
}