// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: MessageCenterPostMsg
//     Last Modified On: 9/26/2023 3:45:50 AM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for MessageCenterPostMsg service.
    /// </summary>
    public partial class MessageCenterPostMsgOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// A new workflow was created.
            /// </summary>
             Inserted = 1,
            /// <summary>
            /// No Message with that ID.
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// The existing Message was modified.
            /// </summary>
             Modified = 2,
            /// <summary>
            /// A message with that ID already exists.
            /// </summary>
             Conflict = 3
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Use 0 for an insert, otherwise use the existing message.
        /// </summary>
        public int? Id { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
