// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: OnCallDelete
//     Last Modified On: 3/28/2025 7:06:40 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the OnCallDelete service.
    /// </summary>
    public partial class OnCallDeleteInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for OnCallDeleteInput.
        /// </summary>
        public OnCallDeleteInput() { }

        /// <summary>
        /// Parameterized constructor for OnCallDeleteInput.
        /// </summary>
        /// <param name="OnCallId">OnCallId</param>
        public OnCallDeleteInput(int? OnCallId)
        {
            this.OnCallId = OnCallId;
        }

        #endregion Constructors

        #region Fields

        private int? _OnCallId = 0;
        /// <summary>
        /// OnCallId
        /// </summary>
        [Required]
        public int? OnCallId
        {
            get => _OnCallId;
            set => _OnCallId = value;
        }

        #endregion

    }
}