// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: OnCallSave
//     Last Modified On: 4/2/2025 5:00:15 PM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for OnCallSave service.
    /// </summary>
    public partial class OnCallSaveOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for InsertError
            /// </summary>
             InsertError = 3,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1,
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// OnCallId
        /// </summary>
        public int? OnCallId { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
