// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: PreviewWorkflowStepResultValueSave
//     Last Modified On: 9/18/2025 2:38:46 PM
//     Written By: alan & kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the PreviewWorkflowStepResultValueSave service.
    /// </summary>
    public partial class PreviewWorkflowStepResultValueSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for PreviewWorkflowStepResultValueSaveInput.
        /// </summary>
        public PreviewWorkflowStepResultValueSaveInput() { }

        /// <summary>
        /// Parameterized constructor for PreviewWorkflowStepResultValueSaveInput.
        /// </summary>
        /// <param name="WorkflowStepResultId">This is the id from workflow step result.</param>
        /// <param name="LoopIndex">Loop iteration.</param>
        /// <param name="LoopPath">Maps to parameter @LoopPath.</param>
        /// <param name="WorkflowDataTypeId">Maps to parameter @WorkflowDataTypeId.</param>
        /// <param name="WorkflowResultId">This is the id from the workflow result.</param>
        /// <param name="StartedTimestamp">Date time UTC.</param>
        /// <param name="StartedLocal">Date time local.</param>
        /// <param name="StartedLatitude">Latitude position when the step was entered.</param>
        /// <param name="StartedLongitude">Longitued when the step was entered.</param>
        /// <param name="CompletedTimestamp">Maps to parameter @CompletedTimestamp.</param>
        /// <param name="CompletedLocal">Maps to parameter @CompletedLocal.</param>
        /// <param name="CompletedLatitude">Latitude position when the step was exited.</param>
        /// <param name="CompletedLongitude">Maps to parameter @CompletedLongitude.</param>
        /// <param name="SourceWorkflowStepResultId">The preceding step that launched this step.</param>
        /// <param name="SourceLoopIndex">Maps to parameter @SourceLoopIndex.</param>
        /// <param name="SourceLoopPath">Maps to parameter @SourceLoopPath.</param>
        /// <param name="Value">This is the primary value of the step result.</param>
        /// <param name="Note">A note that is part of the result.</param>
        /// <param name="ImageFileName">Image associated with step result.</param>
        /// <param name="JsonPayload">Json data collected in association with this step.</param>
        /// <param name="RowUserId">User id of the person entering this information.</param>
        public PreviewWorkflowStepResultValueSaveInput(int? WorkflowStepResultId, int? LoopIndex, string? LoopPath, int? WorkflowDataTypeId, int? WorkflowResultId, DateTime? StartedTimestamp, DateTime? StartedLocal, decimal? StartedLatitude, decimal? StartedLongitude, DateTime? CompletedTimestamp, DateTime? CompletedLocal, decimal? CompletedLatitude, decimal? CompletedLongitude, int? SourceWorkflowStepResultId, int? SourceLoopIndex, string? SourceLoopPath, string? Value, string? Note, string? ImageFileName, string? JsonPayload, int? RowUserId)
        {
            this.WorkflowStepResultId = WorkflowStepResultId;
            this.LoopIndex = LoopIndex;
            this.LoopPath = LoopPath;
            this.WorkflowDataTypeId = WorkflowDataTypeId;
            this.WorkflowResultId = WorkflowResultId;
            this.StartedTimestamp = StartedTimestamp;
            this.StartedLocal = StartedLocal;
            this.StartedLatitude = StartedLatitude;
            this.StartedLongitude = StartedLongitude;
            this.CompletedTimestamp = CompletedTimestamp;
            this.CompletedLocal = CompletedLocal;
            this.CompletedLatitude = CompletedLatitude;
            this.CompletedLongitude = CompletedLongitude;
            this.SourceWorkflowStepResultId = SourceWorkflowStepResultId;
            this.SourceLoopIndex = SourceLoopIndex;
            this.SourceLoopPath = SourceLoopPath;
            this.Value = Value;
            this.Note = Note;
            this.ImageFileName = ImageFileName;
            this.JsonPayload = JsonPayload;
            this.RowUserId = RowUserId;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowStepResultId;
        /// <summary>
        /// This is the id from workflow step result.
        /// </summary>
        [Required]
        public int? WorkflowStepResultId
        {
            get => _WorkflowStepResultId;
            set => _WorkflowStepResultId = value;
        }

        private int? _LoopIndex;
        /// <summary>
        /// Loop iteration.
        /// </summary>
        [Required]
        public int? LoopIndex
        {
            get => _LoopIndex;
            set => _LoopIndex = value;
        }

        private string? _LoopPath;
        /// <summary>
        /// Maps to parameter @LoopPath.
        /// </summary>
        public string? LoopPath
        {
            get => _LoopPath;
            set => _LoopPath = value;
        }

        private int? _WorkflowDataTypeId;
        /// <summary>
        /// Maps to parameter @WorkflowDataTypeId.
        /// </summary>
        [Required]
        public int? WorkflowDataTypeId
        {
            get => _WorkflowDataTypeId;
            set => _WorkflowDataTypeId = value;
        }

        private int? _WorkflowResultId;
        /// <summary>
        /// This is the id from the workflow result.
        /// </summary>
        [Required]
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private DateTime? _StartedTimestamp;
        /// <summary>
        /// Date time UTC.
        /// </summary>
        [Required]
        public DateTime? StartedTimestamp
        {
            get => _StartedTimestamp;
            set => _StartedTimestamp = value;
        }

        private DateTime? _StartedLocal;
        /// <summary>
        /// Date time local.
        /// </summary>
        [Required]
        public DateTime? StartedLocal
        {
            get => _StartedLocal;
            set => _StartedLocal = value;
        }

        private decimal? _StartedLatitude;
        /// <summary>
        /// Latitude position when the step was entered.
        /// </summary>
        [Required]
        public decimal? StartedLatitude
        {
            get => _StartedLatitude;
            set => _StartedLatitude = value;
        }

        private decimal? _StartedLongitude;
        /// <summary>
        /// Longitued when the step was entered.
        /// </summary>
        [Required]
        public decimal? StartedLongitude
        {
            get => _StartedLongitude;
            set => _StartedLongitude = value;
        }

        private DateTime? _CompletedTimestamp;
        /// <summary>
        /// Maps to parameter @CompletedTimestamp.
        /// </summary>
        [Required]
        public DateTime? CompletedTimestamp
        {
            get => _CompletedTimestamp;
            set => _CompletedTimestamp = value;
        }

        private DateTime? _CompletedLocal;
        /// <summary>
        /// Maps to parameter @CompletedLocal.
        /// </summary>
        [Required]
        public DateTime? CompletedLocal
        {
            get => _CompletedLocal;
            set => _CompletedLocal = value;
        }

        private decimal? _CompletedLatitude;
        /// <summary>
        /// Latitude position when the step was exited.
        /// </summary>
        [Required]
        public decimal? CompletedLatitude
        {
            get => _CompletedLatitude;
            set => _CompletedLatitude = value;
        }

        private decimal? _CompletedLongitude;
        /// <summary>
        /// Maps to parameter @CompletedLongitude.
        /// </summary>
        [Required]
        public decimal? CompletedLongitude
        {
            get => _CompletedLongitude;
            set => _CompletedLongitude = value;
        }

        private int? _SourceWorkflowStepResultId;
        /// <summary>
        /// The preceding step that launched this step.
        /// </summary>
        public int? SourceWorkflowStepResultId
        {
            get => _SourceWorkflowStepResultId;
            set => _SourceWorkflowStepResultId = value;
        }

        private int? _SourceLoopIndex;
        /// <summary>
        /// Maps to parameter @SourceLoopIndex.
        /// </summary>
        public int? SourceLoopIndex
        {
            get => _SourceLoopIndex;
            set => _SourceLoopIndex = value;
        }

        private string? _SourceLoopPath;
        /// <summary>
        /// Maps to parameter @SourceLoopPath.
        /// </summary>
        public string? SourceLoopPath
        {
            get => _SourceLoopPath;
            set => _SourceLoopPath = value;
        }

        private string? _Value;
        /// <summary>
        /// This is the primary value of the step result.
        /// </summary>
        [MaxLength(4000)]
        public string? Value
        {
            get => _Value;
            set => _Value = value;
        }

        private string? _Note;
        /// <summary>
        /// A note that is part of the result.
        /// </summary>
        [MaxLength(2000)]
        public string? Note
        {
            get => _Note;
            set => _Note = value;
        }

        private string? _ImageFileName;
        /// <summary>
        /// Image associated with step result.
        /// </summary>
        public string? ImageFileName
        {
            get => _ImageFileName;
            set => _ImageFileName = value;
        }

        private string? _JsonPayload;
        /// <summary>
        /// Json data collected in association with this step.
        /// </summary>
        public string? JsonPayload
        {
            get => _JsonPayload;
            set => _JsonPayload = value;
        }

        private int? _RowUserId;
        /// <summary>
        /// User id of the person entering this information.
        /// </summary>
        [Required]
        public int? RowUserId
        {
            get => _RowUserId;
            set => _RowUserId = value;
        }

        #endregion

    }
}