// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ReorderSteps
//     Last Modified On: 10/3/2024 1:09:48 AM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using ICS.Portal.Data.UserDefinedTypes;
    using SqlPlusBase;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Input object for the ReorderSteps service.
    /// </summary>
    public partial class ReorderStepsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ReorderStepsInput.
        /// </summary>
        public ReorderStepsInput() { }

        /// <summary>
        /// Parameterized constructor for ReorderStepsInput.
        /// </summary>
        /// <param name="ReorderInsfos">Maps to parameter @ReorderInsfos.</param>
        public ReorderStepsInput(List<ReorderInfo>? ReorderInsfos)
        {
            this.ReorderInsfos = ReorderInsfos;
        }

        #endregion Constructors

        #region Fields

        private List<ReorderInfo>? _ReorderInsfos;
        /// <summary>
        /// Maps to parameter @ReorderInsfos.
        /// </summary>
        public List<ReorderInfo>? ReorderInsfos
        {
            get => _ReorderInsfos;
            set => _ReorderInsfos = value;
        }

        #endregion

    }
}