// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ReorderWorkflowSteps
//     Last Modified On: 8/9/2024 4:49:57 PM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using ICS.Portal.Data.UserDefinedTypes;
    using SqlPlusBase;
    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Input object for the ReorderWorkflowSteps service.
    /// </summary>
    public partial class ReorderWorkflowStepsInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ReorderWorkflowStepsInput.
        /// </summary>
        public ReorderWorkflowStepsInput() { }

        /// <summary>
        /// Parameterized constructor for ReorderWorkflowStepsInput.
        /// </summary>
        /// <param name="Source">Maps to parameter @Source.</param>
        public ReorderWorkflowStepsInput(List<IntPair>? Source)
        {
            this.Source = Source;
        }

        #endregion Constructors

        #region Fields

        private List<IntPair>? _Source;
        /// <summary>
        /// Maps to parameter @Source.
        /// </summary>
        public List<IntPair>? Source
        {
            get => _Source;
            set => _Source = value;
        }

        #endregion

    }
}