// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: ResolveTemplateVariables
//     Last Modified On: 1/3/2026 1:42:23 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the ResolveTemplateVariables service.
    /// </summary>
    public partial class ResolveTemplateVariablesInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for ResolveTemplateVariablesInput.
        /// </summary>
        public ResolveTemplateVariablesInput() { }

        /// <summary>
        /// Parameterized constructor for ResolveTemplateVariablesInput.
        /// </summary>
        /// <param name="WorkflowResultId">Maps to parameter @WorkflowResultId.</param>
        /// <param name="TextBlob">Maps to parameter @TextBlob.</param>
        public ResolveTemplateVariablesInput(int? WorkflowResultId, string? TextBlob)
        {
            this.WorkflowResultId = WorkflowResultId;
            this.TextBlob = TextBlob;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowResultId = 0;
        /// <summary>
        /// Maps to parameter @WorkflowResultId.
        /// </summary>
        [Required]
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private string? _TextBlob = "";
        /// <summary>
        /// Maps to parameter @TextBlob.
        /// </summary>
        [Required]
        public string? TextBlob
        {
            get => _TextBlob;
            set => _TextBlob = value;
        }

        #endregion

    }
}