// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TechKPISave
//     Last Modified On: 7/7/2024 1:32:43 AM
//     Written By: Kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the TechKPISave service.
    /// </summary>
    public partial class TechKPISaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for TechKPISaveInput.
        /// </summary>
        public TechKPISaveInput() { }

        /// <summary>
        /// Parameterized constructor for TechKPISaveInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="EmployeeId">Maps to parameter @EmployeeId.</param>
        /// <param name="TechKPITypeId">Maps to parameter @TechKPITypeId.</param>
        /// <param name="KPIValue">Maps to parameter @KPIValue.</param>
        /// <param name="Link">Maps to parameter @Link.</param>
        /// <param name="DisplayOn">Maps to parameter @DisplayOn.</param>
        /// <param name="DisplayUntil">Maps to parameter @DisplayUntil.</param>
        /// <param name="Archived">Maps to parameter @Archived.</param>
        /// <param name="RowUserId">Maps to parameter @RowUserId.</param>
        public TechKPISaveInput(int? Id, int? EmployeeId, int? TechKPITypeId, double? KPIValue, string? Link, DateTime? DisplayOn, DateTime? DisplayUntil, bool? Archived, int? RowUserId)
        {
            this.Id = Id;
            this.EmployeeId = EmployeeId;
            this.TechKPITypeId = TechKPITypeId;
            this.KPIValue = KPIValue;
            this.Link = Link;
            this.DisplayOn = DisplayOn;
            this.DisplayUntil = DisplayUntil;
            this.Archived = Archived;
            this.RowUserId = RowUserId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// Maps to parameter @EmployeeId.
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _TechKPITypeId;
        /// <summary>
        /// Maps to parameter @TechKPITypeId.
        /// </summary>
        public int? TechKPITypeId
        {
            get => _TechKPITypeId;
            set => _TechKPITypeId = value;
        }

        private double? _KPIValue;
        /// <summary>
        /// Maps to parameter @KPIValue.
        /// </summary>
        public double? KPIValue
        {
            get => _KPIValue;
            set => _KPIValue = value;
        }

        private string? _Link;
        /// <summary>
        /// Maps to parameter @Link.
        /// </summary>
        [MaxLength(255)]
        public string? Link
        {
            get => _Link;
            set => _Link = value;
        }

        private DateTime? _DisplayOn;
        /// <summary>
        /// Maps to parameter @DisplayOn.
        /// </summary>
        public DateTime? DisplayOn
        {
            get => _DisplayOn;
            set => _DisplayOn = value;
        }

        private DateTime? _DisplayUntil;
        /// <summary>
        /// Maps to parameter @DisplayUntil.
        /// </summary>
        public DateTime? DisplayUntil
        {
            get => _DisplayUntil;
            set => _DisplayUntil = value;
        }

        private bool? _Archived;
        /// <summary>
        /// Maps to parameter @Archived.
        /// </summary>
        public bool? Archived
        {
            get => _Archived;
            set => _Archived = value;
        }

        private int? _RowUserId;
        /// <summary>
        /// Maps to parameter @RowUserId.
        /// </summary>
        [Required]
        public int? RowUserId
        {
            get => _RowUserId;
            set => _RowUserId = value;
        }

        #endregion

    }
}