// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: TimeclockActivity
//     Last Modified On: 12/10/2024 5:07:54 AM
//     Written By: Kirk Barrett and Timber
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the TimeclockActivity service.
    /// </summary>
    public partial class TimeclockActivityInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for TimeclockActivityInput.
        /// </summary>
        public TimeclockActivityInput() { }

        /// <summary>
        /// Parameterized constructor for TimeclockActivityInput.
        /// </summary>
        /// <param name="Id">Id,may be used for updates returned on insert</param>
        /// <param name="Hash">Hash,Hashcode ID for identifying activity</param>
        /// <param name="Role">ActivityRole,1=release,2=approver,3=lock</param>
        /// <param name="By">By,userid doing this action.  EmployeeId/EntityId</param>
        /// <param name="Status">Status,1=approve,2=decline,3=hold</param>
        /// <param name="Notes">Notes,approvers comments</param>
        /// <param name="Payload">Payload,JSON capture of the timeentry</param>
        /// <param name="Dispatch">Dispatch,Optional Dispatch#</param>
        /// <param name="EventDate">EventDate,EventDate only needed if approving indivual dispatch</param>
        /// <param name="EmployeeId">EmployeeId,required only if approving individual dispatch</param>
        /// <param name="WeekNum">WeekNum,Optional WeekNum for later easy query</param>
        public TimeclockActivityInput(int? Id, int? Hash, int? Role, int? By, int? Status, string? Notes, string? Payload, string? Dispatch, DateTime? EventDate, int? EmployeeId, int? WeekNum)
        {
            this.Id = Id;
            this.Hash = Hash;
            this.Role = Role;
            this.By = By;
            this.Status = Status;
            this.Notes = Notes;
            this.Payload = Payload;
            this.Dispatch = Dispatch;
            this.EventDate = EventDate;
            this.EmployeeId = EmployeeId;
            this.WeekNum = WeekNum;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id,may be used for updates returned on insert
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _Hash;
        /// <summary>
        /// Hash,Hashcode ID for identifying activity
        /// </summary>
        public int? Hash
        {
            get => _Hash;
            set => _Hash = value;
        }

        private int? _Role;
        /// <summary>
        /// ActivityRole,1=release,2=approver,3=lock
        /// </summary>
        public int? Role
        {
            get => _Role;
            set => _Role = value;
        }

        private int? _By;
        /// <summary>
        /// By,userid doing this action.  EmployeeId/EntityId
        /// </summary>
        public int? By
        {
            get => _By;
            set => _By = value;
        }

        private int? _Status;
        /// <summary>
        /// Status,1=approve,2=decline,3=hold
        /// </summary>
        public int? Status
        {
            get => _Status;
            set => _Status = value;
        }

        private string? _Notes;
        /// <summary>
        /// Notes,approvers comments
        /// </summary>
        [MaxLength(2500)]
        public string? Notes
        {
            get => _Notes;
            set => _Notes = value;
        }

        private string? _Payload;
        /// <summary>
        /// Payload,JSON capture of the timeentry
        /// </summary>
        public string? Payload
        {
            get => _Payload;
            set => _Payload = value;
        }

        private string? _Dispatch;
        /// <summary>
        /// Dispatch,Optional Dispatch#
        /// </summary>
        public string? Dispatch
        {
            get => _Dispatch;
            set => _Dispatch = value;
        }

        private DateTime? _EventDate;
        /// <summary>
        /// EventDate,EventDate only needed if approving indivual dispatch
        /// </summary>
        public DateTime? EventDate
        {
            get => _EventDate;
            set => _EventDate = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// EmployeeId,required only if approving individual dispatch
        /// </summary>
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _WeekNum;
        /// <summary>
        /// WeekNum,Optional WeekNum for later easy query
        /// </summary>
        public int? WeekNum
        {
            get => _WeekNum;
            set => _WeekNum = value;
        }

        #endregion

    }
}