// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowSave
//     Last Modified On: 10/21/2024 4:18:16 PM
//     Written By: Alan
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for WorkflowSave service.
    /// </summary>
    public partial class WorkflowSaveOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// A new workflow was created.
            /// </summary>
             Inserted = 1,
            /// <summary>
            /// No workflow was found with provided id.
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// The existing workflow was modified.
            /// </summary>
             Modified = 2,
            /// <summary>
            /// A workflow with that name already exists.
            /// </summary>
             Conflict = 3
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Use 0 for an insert, otherwise use the existing workflow id.
        /// </summary>
        public int? Id { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
