// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowTagActionEvaluate
//     Last Modified On: 3/31/2025 8:30:56 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowTagActionEvaluate service.
    /// </summary>
    public partial class WorkflowTagActionEvaluateInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowTagActionEvaluateInput.
        /// </summary>
        public WorkflowTagActionEvaluateInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowTagActionEvaluateInput.
        /// </summary>
        /// <param name="WorkflowStepResultId">WorkflowStepResultId Input</param>
        /// <param name="LoopIndex">LoopIndex Input</param>
        /// <param name="WorkflowResultId">WorkflowResultId Input</param>
        /// <param name="TagActionId">Optional Input override - TagActionId specified to run this job.  ALWAYS reset to 0 or Last TagActionId MATCHED by system</param>
        /// <param name="WorkflowTagId">Optional Override - WorkflowTagId to FORCE to check against answer</param>
        /// <param name="WorkflowTag">Optional Override - Single or comma delimited list of Tags to check against answer</param>
        /// <param name="ActionsSchema">ActionsSchema to find our tag action proclets in</param>
        /// <param name="ThisPlatformId">PlatformId we are on now.  0=icenext bridge 1=esc or other, 2=sql server, 3=test</param>
        public WorkflowTagActionEvaluateInput(int? WorkflowStepResultId, int? LoopIndex, int? WorkflowResultId, int? TagActionId, int? WorkflowTagId, string? WorkflowTag, string? ActionsSchema, int? ThisPlatformId)
        {
            this.WorkflowStepResultId = WorkflowStepResultId;
            this.LoopIndex = LoopIndex;
            this.WorkflowResultId = WorkflowResultId;
            this.TagActionId = TagActionId;
            this.WorkflowTagId = WorkflowTagId;
            this.WorkflowTag = WorkflowTag;
            this.ActionsSchema = ActionsSchema;
            this.ThisPlatformId = ThisPlatformId;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowStepResultId = 0;
        /// <summary>
        /// WorkflowStepResultId Input
        /// </summary>
        [Required]
        public int? WorkflowStepResultId
        {
            get => _WorkflowStepResultId;
            set => _WorkflowStepResultId = value;
        }

        private int? _LoopIndex = 0;
        /// <summary>
        /// LoopIndex Input
        /// </summary>
        [Required]
        public int? LoopIndex
        {
            get => _LoopIndex;
            set => _LoopIndex = value;
        }

        private int? _WorkflowResultId = 0;
        /// <summary>
        /// WorkflowResultId Input
        /// </summary>
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private int? _TagActionId = 0;
        /// <summary>
        /// Optional Input override - TagActionId specified to run this job.  ALWAYS reset to 0 or Last TagActionId MATCHED by system
        /// </summary>
        public int? TagActionId
        {
            get => _TagActionId;
            set => _TagActionId = value;
        }

        private int? _WorkflowTagId = 0;
        /// <summary>
        /// Optional Override - WorkflowTagId to FORCE to check against answer
        /// </summary>
        public int? WorkflowTagId
        {
            get => _WorkflowTagId;
            set => _WorkflowTagId = value;
        }

        private string? _WorkflowTag;
        /// <summary>
        /// Optional Override - Single or comma delimited list of Tags to check against answer
        /// </summary>
        [MaxLength(3072)]
        public string? WorkflowTag
        {
            get => _WorkflowTag;
            set => _WorkflowTag = value;
        }

        private string? _ActionsSchema = "tagcmd";
        /// <summary>
        /// ActionsSchema to find our tag action proclets in
        /// </summary>
        public string? ActionsSchema
        {
            get => _ActionsSchema;
            set => _ActionsSchema = value;
        }

        private int? _ThisPlatformId = 3;
        /// <summary>
        /// PlatformId we are on now.  0=icenext bridge 1=esc or other, 2=sql server, 3=test
        /// </summary>
        public int? ThisPlatformId
        {
            get => _ThisPlatformId;
            set => _ThisPlatformId = value;
        }

        #endregion

    }
}