// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderDispatchTechStatusChange
//     Last Modified On: 12/10/2025 5:51:37 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkOrderDispatchTechStatusChange service.
    /// </summary>
    public partial class WorkOrderDispatchTechStatusChangeInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkOrderDispatchTechStatusChangeInput.
        /// </summary>
        public WorkOrderDispatchTechStatusChangeInput() { }

        /// <summary>
        /// Parameterized constructor for WorkOrderDispatchTechStatusChangeInput.
        /// </summary>
        /// <param name="WorkOrderDispatchTechId">WorkOrderDispatchTechId</param>
        /// <param name="ActionType">ActionType 1-6 is 1-Pending,2-Travel,3-Working,4-Complete,5-Off Job,6-Cancel, 25=arrival, 55= OnJob</param>
        /// <param name="Status">Status</param>
        /// <param name="ActivityDate">ActivityDate</param>
        public WorkOrderDispatchTechStatusChangeInput(int? WorkOrderDispatchTechId, int? ActionType, string? Status, DateTimeOffset? ActivityDate)
        {
            this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
            this.ActionType = ActionType;
            this.Status = Status;
            this.ActivityDate = ActivityDate;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkOrderDispatchTechId;
        /// <summary>
        /// WorkOrderDispatchTechId
        /// </summary>
        public int? WorkOrderDispatchTechId
        {
            get => _WorkOrderDispatchTechId;
            set => _WorkOrderDispatchTechId = value;
        }

        private int? _ActionType;
        /// <summary>
        /// ActionType 1-6 is 1-Pending,2-Travel,3-Working,4-Complete,5-Off Job,6-Cancel, 25=arrival, 55= OnJob
        /// </summary>
        public int? ActionType
        {
            get => _ActionType;
            set => _ActionType = value;
        }

        private string? _Status;
        /// <summary>
        /// Status
        /// </summary>
        public string? Status
        {
            get => _Status;
            set => _Status = value;
        }

        private DateTimeOffset? _ActivityDate;
        /// <summary>
        /// ActivityDate
        /// </summary>
        [Required]
        public DateTimeOffset? ActivityDate
        {
            get => _ActivityDate;
            set => _ActivityDate = value;
        }

        #endregion

    }
}