// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderDispatchTechActivitySave
//     Last Modified On: 12/10/2025 5:44:59 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkOrderDispatchTechActivitySave service.
    /// </summary>
    public partial class WorkOrderDispatchTechActivitySaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkOrderDispatchTechActivitySaveInput.
        /// </summary>
        public WorkOrderDispatchTechActivitySaveInput() { }

        /// <summary>
        /// Parameterized constructor for WorkOrderDispatchTechActivitySaveInput.
        /// </summary>
        /// <param name="Id">Output Id if adding a new activity record.  May not be super important to anyone</param>
        /// <param name="ActionType">ActionType 1-6 is 1-Pending,2-Travel,3-Working,4-Complete,5-Off Job,6-Cancel, 25=arrival, 55= OnJob, 70=StartDay, 75=EndDay. 0=justadd action not also dispatchtech</param>
        /// <param name="WorkOrderDispatchTechId">WorkOrderDispatchTechId</param>
        /// <param name="EmployeeId">EmployeeId</param>
        /// <param name="CustomerLocationId">CustomerId</param>
        /// <param name="WorkflowResultId">WorkflowResultId</param>
        /// <param name="WorkflowStepResultId">WorkflowResultStepId</param>
        /// <param name="WorkOrderDispatchId">WorkOrderDispatchId</param>
        /// <param name="Equipment">Maps to parameter @Equipment.</param>
        /// <param name="EquipmentId">EquipmentId</param>
        /// <param name="EquipmentPayload">EquipmentPayload with json of equipment</param>
        /// <param name="NewEquipmentId">GUID of new temp equipment</param>
        /// <param name="ItemsUsed">Maps to parameter @ItemsUsed.</param>
        /// <param name="ItemsUsedPayload">Maps to parameter @ItemsUsedPayload.</param>
        /// <param name="Status">Status</param>
        /// <param name="Activity">Activity Detail or JSON</param>
        /// <param name="ActivityDate">ActivityDate</param>
        /// <param name="Latitude">Latitude</param>
        /// <param name="Longitude">Longitude</param>
        /// <param name="ExternalKey">ExternalKey</param>
        /// <param name="Notes">Notes</param>
        /// <param name="Tags">Tags</param>
        /// <param name="CreatedBy">CreatedBy</param>
        /// <param name="ModifiedBy">ModifiedBy</param>
        /// <param name="Hash">Hash</param>
        public WorkOrderDispatchTechActivitySaveInput(int? Id, int? ActionType, int? WorkOrderDispatchTechId, int? EmployeeId, int? CustomerLocationId, int? WorkflowResultId, int? WorkflowStepResultId, int? WorkOrderDispatchId, string? Equipment, int? EquipmentId, string? EquipmentPayload, Guid? NewEquipmentId, string? ItemsUsed, string? ItemsUsedPayload, string? Status, string? Activity, DateTimeOffset? ActivityDate, decimal? Latitude, decimal? Longitude, string? ExternalKey, string? Notes, string? Tags, int? CreatedBy, int? ModifiedBy, int? Hash)
        {
            this.Id = Id;
            this.ActionType = ActionType;
            this.WorkOrderDispatchTechId = WorkOrderDispatchTechId;
            this.EmployeeId = EmployeeId;
            this.CustomerLocationId = CustomerLocationId;
            this.WorkflowResultId = WorkflowResultId;
            this.WorkflowStepResultId = WorkflowStepResultId;
            this.WorkOrderDispatchId = WorkOrderDispatchId;
            this.Equipment = Equipment;
            this.EquipmentId = EquipmentId;
            this.EquipmentPayload = EquipmentPayload;
            this.NewEquipmentId = NewEquipmentId;
            this.ItemsUsed = ItemsUsed;
            this.ItemsUsedPayload = ItemsUsedPayload;
            this.Status = Status;
            this.Activity = Activity;
            this.ActivityDate = ActivityDate;
            this.Latitude = Latitude;
            this.Longitude = Longitude;
            this.ExternalKey = ExternalKey;
            this.Notes = Notes;
            this.Tags = Tags;
            this.CreatedBy = CreatedBy;
            this.ModifiedBy = ModifiedBy;
            this.Hash = Hash;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Output Id if adding a new activity record.  May not be super important to anyone
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _ActionType;
        /// <summary>
        /// ActionType 1-6 is 1-Pending,2-Travel,3-Working,4-Complete,5-Off Job,6-Cancel, 25=arrival, 55= OnJob, 70=StartDay, 75=EndDay. 0=justadd action not also dispatchtech
        /// </summary>
        public int? ActionType
        {
            get => _ActionType;
            set => _ActionType = value;
        }

        private int? _WorkOrderDispatchTechId;
        /// <summary>
        /// WorkOrderDispatchTechId
        /// </summary>
        [Required]
        public int? WorkOrderDispatchTechId
        {
            get => _WorkOrderDispatchTechId;
            set => _WorkOrderDispatchTechId = value;
        }

        private int? _EmployeeId;
        /// <summary>
        /// EmployeeId
        /// </summary>
        [Required]
        public int? EmployeeId
        {
            get => _EmployeeId;
            set => _EmployeeId = value;
        }

        private int? _CustomerLocationId;
        /// <summary>
        /// CustomerId
        /// </summary>
        [Required]
        public int? CustomerLocationId
        {
            get => _CustomerLocationId;
            set => _CustomerLocationId = value;
        }

        private int? _WorkflowResultId;
        /// <summary>
        /// WorkflowResultId
        /// </summary>
        [Required]
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private int? _WorkflowStepResultId;
        /// <summary>
        /// WorkflowResultStepId
        /// </summary>
        [Required]
        public int? WorkflowStepResultId
        {
            get => _WorkflowStepResultId;
            set => _WorkflowStepResultId = value;
        }

        private int? _WorkOrderDispatchId;
        /// <summary>
        /// WorkOrderDispatchId
        /// </summary>
        [Required]
        public int? WorkOrderDispatchId
        {
            get => _WorkOrderDispatchId;
            set => _WorkOrderDispatchId = value;
        }

        private string? _Equipment;
        /// <summary>
        /// Maps to parameter @Equipment.
        /// </summary>
        public string? Equipment
        {
            get => _Equipment;
            set => _Equipment = value;
        }

        private int? _EquipmentId;
        /// <summary>
        /// EquipmentId
        /// </summary>
        [Required]
        public int? EquipmentId
        {
            get => _EquipmentId;
            set => _EquipmentId = value;
        }

        private string? _EquipmentPayload;
        /// <summary>
        /// EquipmentPayload with json of equipment
        /// </summary>
        public string? EquipmentPayload
        {
            get => _EquipmentPayload;
            set => _EquipmentPayload = value;
        }

        private Guid? _NewEquipmentId;
        /// <summary>
        /// GUID of new temp equipment
        /// </summary>
        public Guid? NewEquipmentId
        {
            get => _NewEquipmentId;
            set => _NewEquipmentId = value;
        }

        private string? _ItemsUsed;
        /// <summary>
        /// Maps to parameter @ItemsUsed.
        /// </summary>
        public string? ItemsUsed
        {
            get => _ItemsUsed;
            set => _ItemsUsed = value;
        }

        private string? _ItemsUsedPayload;
        /// <summary>
        /// Maps to parameter @ItemsUsedPayload.
        /// </summary>
        public string? ItemsUsedPayload
        {
            get => _ItemsUsedPayload;
            set => _ItemsUsedPayload = value;
        }

        private string? _Status;
        /// <summary>
        /// Status
        /// </summary>
        [MaxLength(36)]
        public string? Status
        {
            get => _Status;
            set => _Status = value;
        }

        private string? _Activity;
        /// <summary>
        /// Activity Detail or JSON
        /// </summary>
        public string? Activity
        {
            get => _Activity;
            set => _Activity = value;
        }

        private DateTimeOffset? _ActivityDate;
        /// <summary>
        /// ActivityDate
        /// </summary>
        [Required]
        public DateTimeOffset? ActivityDate
        {
            get => _ActivityDate;
            set => _ActivityDate = value;
        }

        private decimal? _Latitude;
        /// <summary>
        /// Latitude
        /// </summary>
        [Required]
        public decimal? Latitude
        {
            get => _Latitude;
            set => _Latitude = value;
        }

        private decimal? _Longitude;
        /// <summary>
        /// Longitude
        /// </summary>
        [Required]
        public decimal? Longitude
        {
            get => _Longitude;
            set => _Longitude = value;
        }

        private string? _ExternalKey;
        /// <summary>
        /// ExternalKey
        /// </summary>
        [MaxLength(50)]
        public string? ExternalKey
        {
            get => _ExternalKey;
            set => _ExternalKey = value;
        }

        private string? _Notes;
        /// <summary>
        /// Notes
        /// </summary>
        public string? Notes
        {
            get => _Notes;
            set => _Notes = value;
        }

        private string? _Tags;
        /// <summary>
        /// Tags
        /// </summary>
        public string? Tags
        {
            get => _Tags;
            set => _Tags = value;
        }

        private int? _CreatedBy;
        /// <summary>
        /// CreatedBy
        /// </summary>
        public int? CreatedBy
        {
            get => _CreatedBy;
            set => _CreatedBy = value;
        }

        private int? _ModifiedBy;
        /// <summary>
        /// ModifiedBy
        /// </summary>
        [Required]
        public int? ModifiedBy
        {
            get => _ModifiedBy;
            set => _ModifiedBy = value;
        }

        private int? _Hash;
        /// <summary>
        /// Hash
        /// </summary>
        [Required]
        public int? Hash
        {
            get => _Hash;
            set => _Hash = value;
        }

        #endregion

    }
}