// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStepResultResetShareExt
//     Last Modified On: 1/29/2025 3:19:33 AM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowStepResultResetShareExt service.
    /// </summary>
    public partial class WorkflowStepResultResetShareExtInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowStepResultResetShareExtInput.
        /// </summary>
        public WorkflowStepResultResetShareExtInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowStepResultResetShareExtInput.
        /// </summary>
        /// <param name="WorkflowId">WorkflowId</param>
        public WorkflowStepResultResetShareExtInput(int? WorkflowId)
        {
            this.WorkflowId = WorkflowId;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowId;
        /// <summary>
        /// WorkflowId
        /// </summary>
        [Required]
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        #endregion

    }
}