// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowJobManager
//     Last Modified On: 10/24/2024 3:08:36 AM
//     Written By: KirkyB
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowJobManager service.
    /// </summary>
    public partial class WorkflowJobManagerInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowJobManagerInput.
        /// </summary>
        public WorkflowJobManagerInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowJobManagerInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="JobId">Maps to parameter @JobId.</param>
        /// <param name="JobStatus">Maps to parameter @JobStatus.</param>
        /// <param name="JobStatusSet">Maps to parameter @JobStatusSet.</param>
        public WorkflowJobManagerInput(int? Id, int? JobId, int? JobStatus, int? JobStatusSet)
        {
            this.Id = Id;
            this.JobId = JobId;
            this.JobStatus = JobStatus;
            this.JobStatusSet = JobStatusSet;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _JobId;
        /// <summary>
        /// Maps to parameter @JobId.
        /// </summary>
        public int? JobId
        {
            get => _JobId;
            set => _JobId = value;
        }

        private int? _JobStatus;
        /// <summary>
        /// Maps to parameter @JobStatus.
        /// </summary>
        public int? JobStatus
        {
            get => _JobStatus;
            set => _JobStatus = value;
        }

        private int? _JobStatusSet;
        /// <summary>
        /// Maps to parameter @JobStatusSet.
        /// </summary>
        public int? JobStatusSet
        {
            get => _JobStatusSet;
            set => _JobStatusSet = value;
        }

        #endregion

    }
}