// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStageDelete
//     Last Modified On: 9/20/2024 2:03:33 AM
//     Written By: Kirk
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for WorkflowStageDelete service.
    /// </summary>
    public partial class WorkflowStageDeleteOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// No record was found for the given id in Stage.
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Stage Workflow and any associated steps and options deleted.
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
