// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowStagePublish
//     Last Modified On: 10/2/2024 6:33:30 PM
//     Written By: Alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowStagePublish service.
    /// </summary>
    public partial class WorkflowStagePublishInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowStagePublishInput.
        /// </summary>
        public WorkflowStagePublishInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowStagePublishInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        public WorkflowStagePublishInput(int? Id)
        {
            this.Id = Id;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        #endregion

    }
}