// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowNotificationGroupSave
//     Last Modified On: 12/29/2025 9:02:07 PM
//     Written By: alan
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowNotificationGroupSave service.
    /// </summary>
    public partial class WorkflowNotificationGroupSaveInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowNotificationGroupSaveInput.
        /// </summary>
        public WorkflowNotificationGroupSaveInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowNotificationGroupSaveInput.
        /// </summary>
        /// <param name="Id">Maps to parameter @Id.</param>
        /// <param name="Name">Maps to parameter @Name.</param>
        /// <param name="Recipients">Maps to parameter @Recipients.</param>
        /// <param name="Subject">Maps to parameter @Subject.</param>
        /// <param name="Body">Maps to parameter @Body.</param>
        /// <param name="Description">Maps to parameter @Description.</param>
        /// <param name="Active">Maps to parameter @Active.</param>
        /// <param name="RowUserId">Maps to parameter @RowUserId.</param>
        public WorkflowNotificationGroupSaveInput(int? Id, string? Name, string? Recipients, string? Subject, string? Body, string? Description, bool? Active, int? RowUserId)
        {
            this.Id = Id;
            this.Name = Name;
            this.Recipients = Recipients;
            this.Subject = Subject;
            this.Body = Body;
            this.Description = Description;
            this.Active = Active;
            this.RowUserId = RowUserId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private string? _Name;
        /// <summary>
        /// Maps to parameter @Name.
        /// </summary>
        [Required]
        [MaxLength(32)]
        public string? Name
        {
            get => _Name;
            set => _Name = value;
        }

        private string? _Recipients = null;
        /// <summary>
        /// Maps to parameter @Recipients.
        /// </summary>
        [MaxLength(512)]
        public string? Recipients
        {
            get => _Recipients;
            set => _Recipients = value;
        }

        private string? _Subject = null;
        /// <summary>
        /// Maps to parameter @Subject.
        /// </summary>
        [MaxLength(60)]
        public string? Subject
        {
            get => _Subject;
            set => _Subject = value;
        }

        private string? _Body = null;
        /// <summary>
        /// Maps to parameter @Body.
        /// </summary>
        public string? Body
        {
            get => _Body;
            set => _Body = value;
        }

        private string? _Description;
        /// <summary>
        /// Maps to parameter @Description.
        /// </summary>
        [Required]
        [MaxLength(128)]
        public string? Description
        {
            get => _Description;
            set => _Description = value;
        }

        private bool? _Active;
        /// <summary>
        /// Maps to parameter @Active.
        /// </summary>
        [Required]
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        private int? _RowUserId;
        /// <summary>
        /// Maps to parameter @RowUserId.
        /// </summary>
        [Required]
        public int? RowUserId
        {
            get => _RowUserId;
            set => _RowUserId = value;
        }

        #endregion

    }
}