// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowResultComplete
//     Last Modified On: 1/14/2025 10:45:34 PM
//     Written By: alan
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable
    /// <summary>
    /// Output object for WorkflowResultComplete service.
    /// </summary>
    public partial class WorkflowResultCompleteOutput
    {
        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @WorkflowId.
        /// </summary>
        public int? WorkflowId { set; get; }
        /// <summary>
        /// Maps to parameter @WorkflowTagId.
        /// </summary>
        public int? WorkflowTagId { set; get; }
        /// <summary>
        /// Maps to parameter @NotificationGroupId.
        /// </summary>
        public int? NotificationGroupId { set; get; }
        /// <summary>
        /// Maps to parameter @Latitude.
        /// </summary>
        public decimal? Latitude { set; get; }
        /// <summary>
        /// Maps to parameter @Longitude.
        /// </summary>
        public decimal? Longitude { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

    }





}
