// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowAssignmentUpsert
//     Last Modified On: 11/13/2023 11:34:11 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowAssignmentUpsert service.
    /// </summary>
    public partial class WorkflowAssignmentUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowAssignmentUpsertInput.
        /// </summary>
        public WorkflowAssignmentUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowAssignmentUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="WorkflowId">WorkflowNotificationGroupId</param>
        /// <param name="EntityTypeId">EntityTypeId</param>
        /// <param name="EntityId">EntityId</param>
        public WorkflowAssignmentUpsertInput(int? Id, int? WorkflowId, int? EntityTypeId, int? EntityId)
        {
            this.Id = Id;
            this.WorkflowId = WorkflowId;
            this.EntityTypeId = EntityTypeId;
            this.EntityId = EntityId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _WorkflowId;
        /// <summary>
        /// WorkflowNotificationGroupId
        /// </summary>
        [Required]
        public int? WorkflowId
        {
            get => _WorkflowId;
            set => _WorkflowId = value;
        }

        private int? _EntityTypeId;
        /// <summary>
        /// EntityTypeId
        /// </summary>
        [Required]
        public int? EntityTypeId
        {
            get => _EntityTypeId;
            set => _EntityTypeId = value;
        }

        private int? _EntityId;
        /// <summary>
        /// EntityId
        /// </summary>
        [Required]
        public int? EntityId
        {
            get => _EntityId;
            set => _EntityId = value;
        }

        #endregion

    }
}