// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowResultDeactivate
//     Last Modified On: 8/27/2024 4:05:28 PM
//     Written By: alan & kirk
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowResultDeactivate service.
    /// </summary>
    public partial class WorkflowResultDeactivateInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowResultDeactivateInput.
        /// </summary>
        public WorkflowResultDeactivateInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowResultDeactivateInput.
        /// </summary>
        /// <param name="WorkflowResultId">Maps to parameter @WorkflowResultId.</param>
        /// <param name="Active">Maps to parameter @Active.</param>
        public WorkflowResultDeactivateInput(int? WorkflowResultId, bool? Active)
        {
            this.WorkflowResultId = WorkflowResultId;
            this.Active = Active;
        }

        #endregion Constructors

        #region Fields

        private int? _WorkflowResultId;
        /// <summary>
        /// Maps to parameter @WorkflowResultId.
        /// </summary>
        [Required]
        public int? WorkflowResultId
        {
            get => _WorkflowResultId;
            set => _WorkflowResultId = value;
        }

        private bool? _Active;
        /// <summary>
        /// Maps to parameter @Active.
        /// </summary>
        public bool? Active
        {
            get => _Active;
            set => _Active = value;
        }

        #endregion

    }
}