// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkflowPermissionRuleUpsert
//     Last Modified On: 11/1/2024 6:29:17 PM
//     Written By: Kirk Barrett
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    #region usings

    using SqlPlusBase;
    using System.ComponentModel.DataAnnotations;

    #endregion usings

    /// <summary>
    /// Input object for the WorkflowPermissionRuleUpsert service.
    /// </summary>
    public partial class WorkflowPermissionRuleUpsertInput : ValidInput
    {
        #region Constructors

        /// <summary>
        /// Empty constructor for WorkflowPermissionRuleUpsertInput.
        /// </summary>
        public WorkflowPermissionRuleUpsertInput() { }

        /// <summary>
        /// Parameterized constructor for WorkflowPermissionRuleUpsertInput.
        /// </summary>
        /// <param name="Id">Id</param>
        /// <param name="PermissionId">See WorkflowPremissionType Table</param>
        /// <param name="EntityTypeId">EntityTypeId</param>
        /// <param name="EntityId">EntityId</param>
        /// <param name="RulePattern1">RulePattern1</param>
        /// <param name="RulePattern2">RulePattern2</param>
        /// <param name="RulePattern3">RulePattern3</param>
        /// <param name="RulePattern4">RulePattern4</param>
        /// <param name="RulePattern5">RulePattern5</param>
        /// <param name="RowUserId">RulePattern5</param>
        public WorkflowPermissionRuleUpsertInput(int? Id, int? PermissionId, int? EntityTypeId, int? EntityId, string? RulePattern1, string? RulePattern2, string? RulePattern3, string? RulePattern4, string? RulePattern5, int? RowUserId)
        {
            this.Id = Id;
            this.PermissionId = PermissionId;
            this.EntityTypeId = EntityTypeId;
            this.EntityId = EntityId;
            this.RulePattern1 = RulePattern1;
            this.RulePattern2 = RulePattern2;
            this.RulePattern3 = RulePattern3;
            this.RulePattern4 = RulePattern4;
            this.RulePattern5 = RulePattern5;
            this.RowUserId = RowUserId;
        }

        #endregion Constructors

        #region Fields

        private int? _Id;
        /// <summary>
        /// Id
        /// </summary>
        [Required]
        public int? Id
        {
            get => _Id;
            set => _Id = value;
        }

        private int? _PermissionId;
        /// <summary>
        /// See WorkflowPremissionType Table
        /// </summary>
        [Required]
        public int? PermissionId
        {
            get => _PermissionId;
            set => _PermissionId = value;
        }

        private int? _EntityTypeId;
        /// <summary>
        /// EntityTypeId
        /// </summary>
        [Required]
        public int? EntityTypeId
        {
            get => _EntityTypeId;
            set => _EntityTypeId = value;
        }

        private int? _EntityId;
        /// <summary>
        /// EntityId
        /// </summary>
        public int? EntityId
        {
            get => _EntityId;
            set => _EntityId = value;
        }

        private string? _RulePattern1;
        /// <summary>
        /// RulePattern1
        /// </summary>
        public string? RulePattern1
        {
            get => _RulePattern1;
            set => _RulePattern1 = value;
        }

        private string? _RulePattern2;
        /// <summary>
        /// RulePattern2
        /// </summary>
        public string? RulePattern2
        {
            get => _RulePattern2;
            set => _RulePattern2 = value;
        }

        private string? _RulePattern3;
        /// <summary>
        /// RulePattern3
        /// </summary>
        public string? RulePattern3
        {
            get => _RulePattern3;
            set => _RulePattern3 = value;
        }

        private string? _RulePattern4;
        /// <summary>
        /// RulePattern4
        /// </summary>
        public string? RulePattern4
        {
            get => _RulePattern4;
            set => _RulePattern4 = value;
        }

        private string? _RulePattern5;
        /// <summary>
        /// RulePattern5
        /// </summary>
        public string? RulePattern5
        {
            get => _RulePattern5;
            set => _RulePattern5 = value;
        }

        private int? _RowUserId;
        /// <summary>
        /// RulePattern5
        /// </summary>
        public int? RowUserId
        {
            get => _RowUserId;
            set => _RowUserId = value;
        }

        #endregion

    }
}