// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: WorkOrderDispatchTechActivityUpsert
//     Last Modified On: 11/20/2023 4:59:01 PM
//     Written By: Kirk Barrett
//     Select Type: NonQuery
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Commands.Models
{
    #nullable enable

    /// <summary>
    /// Output object for WorkOrderDispatchTechActivityUpsert service.
    /// </summary>
    public partial class WorkOrderDispatchTechActivityUpsertOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Output Parameters

        /// <summary>
        /// Maps to parameter @Id.
        /// </summary>
        public int? Id { set; get; }

	    #endregion Output Parameters

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value
    }









}
