// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL PLUS Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.Statics
{

    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Class for Static Query: WorkflowJumpConditionType
    /// </summary>
    public partial class StaticData
    {
        /// <summary>
        /// List for Data returned by Static Query: WorkflowJumpConditionType
        /// </summary>
        public static List<WorkflowJumpConditionType> WorkflowJumpConditionTypeList = new List<WorkflowJumpConditionType>()
        {
            new WorkflowJumpConditionType((int)0, @"None", @"No Jump Condition", @"No jump will happen regardless of the value entered."),
            new WorkflowJumpConditionType((int)1, @"Equals", @"Equals ( = )", @"Entered value matches target exactly."),
            new WorkflowJumpConditionType((int)2, @"NotEqual", @"Not Equal ( != )", @"Entered value does not match target."),
            new WorkflowJumpConditionType((int)3, @"GreaterThan", @"Greater Than ( > )", @"Entered value is greater than target."),
            new WorkflowJumpConditionType((int)4, @"LessThan", @"Less Than ( < )", @"Entered value is less than target."),
            new WorkflowJumpConditionType((int)5, @"StartsWith", @"Starts With ( ab = abc )", @"Target starts with entered value."),
            new WorkflowJumpConditionType((int)6, @"EndsWith", @"Ends With ( bc = abc)", @"Target ends with entered value."),
            new WorkflowJumpConditionType((int)7, @"Contains", @"Contains ( b = abc)", @"Target contains entered value."),
        };
    }

    /// <summary>
    /// Concrete class representation for Static Query: WorkflowJumpConditionType
    /// </summary>
    public class WorkflowJumpConditionType
    {
        #pragma warning disable 1591

        public WorkflowJumpConditionType(int Id, string Name, string DisplayName, string Description)
        {
            this.Id = Id;
            this.Name = Name;
            this.DisplayName = DisplayName;
            this.Description = Description;
        }
        
        #pragma warning restore 1591

        /// <summary>
        /// Result for Column: Id
        /// </summary>
        public int Id  { get; }

        /// <summary>
        /// Result for Column: Name
        /// </summary>
        public string Name  { get; }

        /// <summary>
        /// Result for Column: DisplayName
        /// </summary>
        public string DisplayName  { get; }

        /// <summary>
        /// Result for Column: Description
        /// </summary>
        public string Description  { get; }

    }
}