// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AuthorizedUserCommunications
//     Last Modified On: 7/26/2023 1:40:15 PM
//     Written By: alan@interiorcs.com
//     Select Type: MultiRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.AuthService.Models
{
    #nullable enable


    #region usings

    using System.Collections.Generic;

    #endregion usings

    /// <summary>
    /// Output object for AuthorizedUserCommunications service.
    /// </summary>
    public partial class AuthorizedUserCommunicationsOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 101,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1,
            /// <summary>
            /// Enumerated value for UnknownEntityType
            /// </summary>
             UnknownEntityType = 102
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// List of AuthorizedUserCommunicationsResult.
        /// </summary>
        public List<AuthorizedUserCommunicationsResult>? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for AuthorizedUserCommunications service.
    /// </summary>




    public partial class AuthorizedUserCommunicationsResult
	{
        /// <summary>
        /// Result set object for AuthorizedUserCommunications.
        /// </summary>
        /// <param name="CommunicationId">Maps to table value column CommunicationId.</param>
        /// <param name="CommunicationTypeId">Maps to table value column CommunicationTypeId.</param>
        /// <param name="Data">Maps to table value column Data.</param>
        public AuthorizedUserCommunicationsResult(int CommunicationId, byte CommunicationTypeId, string Data)
        {
             this.CommunicationId = CommunicationId;
             this.CommunicationTypeId = CommunicationTypeId;
             this.Data = Data;
        }


        /// <summary>
        /// Maps to table value column CommunicationId.
        /// </summary>
        public int CommunicationId { set; get; }

        /// <summary>
        /// Maps to table value column CommunicationTypeId.
        /// </summary>
        public byte CommunicationTypeId { set; get; }

        /// <summary>
        /// Maps to table value column Data.
        /// </summary>
        public string Data { set; get; }
    }


    #endregion Result Set Objects

}
