// --------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SQL  Code Generation Utility.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     Underlying Routine: AuthorizedUserSelect
//     Last Modified On: 7/31/2023 8:35:00 PM
//     Written By: alan@interiorcs.com
//     Select Type: SingleRow
//     Visit https://www.SQLPLUS.net for more information about the SQL Plus build time ORM.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------
namespace ICS.Portal.Data.AuthService.Models
{
    #nullable enable


    #region usings

    using System;

    #endregion usings

    /// <summary>
    /// Output object for AuthorizedUserSelect service.
    /// </summary>
    public partial class AuthorizedUserSelectOutput
    {

        #region Return Value Enumerations

        /// <summary>
        /// Enumerated return values based on the ReturnTags in the procedure.
        /// </summary>
        public enum Returns
        {
            /// <summary>
            /// Enumerated value for NotFound
            /// </summary>
             NotFound = 0,
            /// <summary>
            /// Enumerated value for Ok
            /// </summary>
             Ok = 1
        }

        #endregion Return Value Enumerations

        #region Return Value

        /// <summary>
        /// Enumerated return value.
        /// </summary>
        public Returns ReturnValue { set; get; }

        #endregion Return Value

        #region Result Data

        /// <summary>
        /// Single instance of AuthorizedUserSelectResult.
        /// </summary>
        public AuthorizedUserSelectResult? ResultData { set; get; }

        #endregion Result Data
    }



    #region Result Set Objects

    /// <summary>
    /// Result object for AuthorizedUserSelect service.
    /// </summary>




    public partial class AuthorizedUserSelectResult
	{
        /// <summary>
        /// Result set object for AuthorizedUserSelect.
        /// </summary>
        /// <param name="Id">Maps to table value column Id.</param>
        /// <param name="EntityTypeId">Maps to table value column EntityTypeId.</param>
        /// <param name="EntityId">Maps to table value column EntityId.</param>
        /// <param name="UserName">Maps to table value column UserName.</param>
        /// <param name="RoleFlag">Maps to table value column RoleFlag.</param>
        /// <param name="PasswordIterations">Maps to table value column PasswordIterations.</param>
        /// <param name="PasswordAlgorithm">Maps to table value column PasswordAlgorithm.</param>
        /// <param name="PasswordHash">Maps to table value column PasswordHash.</param>
        /// <param name="PasswordSalt">Maps to table value column PasswordSalt.</param>
        /// <param name="RowOwnerId">Maps to table value column RowOwnerId.</param>
        /// <param name="PasswordExpireDate">Maps to table value column PasswordExpireDate.</param>
        /// <param name="LockReasonId">Maps to table value column LockReasonId.</param>
        /// <param name="LockDate">Maps to table value column LockDate.</param>
        public AuthorizedUserSelectResult(int Id, byte EntityTypeId, int EntityId, string UserName, long RoleFlag, int PasswordIterations, string PasswordAlgorithm, byte[] PasswordHash, byte[] PasswordSalt, int RowOwnerId, DateTime PasswordExpireDate, byte? LockReasonId, DateTime? LockDate)
        {
             this.Id = Id;
             this.EntityTypeId = EntityTypeId;
             this.EntityId = EntityId;
             this.UserName = UserName;
             this.RoleFlag = RoleFlag;
             this.PasswordIterations = PasswordIterations;
             this.PasswordAlgorithm = PasswordAlgorithm;
             this.PasswordHash = PasswordHash;
             this.PasswordSalt = PasswordSalt;
             this.RowOwnerId = RowOwnerId;
             this.PasswordExpireDate = PasswordExpireDate;
             this.LockReasonId = LockReasonId;
             this.LockDate = LockDate;
        }


        /// <summary>
        /// Maps to table value column Id.
        /// </summary>
        public int Id { set; get; }

        /// <summary>
        /// Maps to table value column EntityTypeId.
        /// </summary>
        public byte EntityTypeId { set; get; }

        /// <summary>
        /// Maps to table value column EntityId.
        /// </summary>
        public int EntityId { set; get; }

        /// <summary>
        /// Maps to table value column UserName.
        /// </summary>
        public string UserName { set; get; }

        /// <summary>
        /// Maps to table value column RoleFlag.
        /// </summary>
        public long RoleFlag { set; get; }

        /// <summary>
        /// Maps to table value column PasswordIterations.
        /// </summary>
        public int PasswordIterations { set; get; }

        /// <summary>
        /// Maps to table value column PasswordAlgorithm.
        /// </summary>
        public string PasswordAlgorithm { set; get; }

        /// <summary>
        /// Maps to table value column PasswordHash.
        /// </summary>
        public byte[] PasswordHash { set; get; }

        /// <summary>
        /// Maps to table value column PasswordSalt.
        /// </summary>
        public byte[] PasswordSalt { set; get; }

        /// <summary>
        /// Maps to table value column RowOwnerId.
        /// </summary>
        public int RowOwnerId { set; get; }

        /// <summary>
        /// Maps to table value column PasswordExpireDate.
        /// </summary>
        public DateTime PasswordExpireDate { set; get; }

        /// <summary>
        /// Maps to table value column LockReasonId.
        /// </summary>
        public byte? LockReasonId { set; get; }

        /// <summary>
        /// Maps to table value column LockDate.
        /// </summary>
        public DateTime? LockDate { set; get; }
    }


    #endregion Result Set Objects

}
